/* GENERATED by qrts/tools/gen_memmap.py -- do not edit. */
#ifndef DVCON_MEMMAP_H
#define DVCON_MEMMAP_H

#include <stdint.h>

#define DVCON_SDRAM_BYTES  134217728u

/* model blob: 32-byte header + 181 x 64 B descriptors + weights */
#define DVCON_MODEL_BASE  0x00000000u
#define DVCON_MODEL_SIZE  4194304u
/* input frame, INT8 CHW 3x640x640 = 1,228,800 B */
#define DVCON_FRAME_BASE  0x00400000u
#define DVCON_FRAME_SIZE  2097152u
/* box list: 300 x 16-byte records, Q12.4 */
#define DVCON_BOXES_BASE  0x00600000u
#define DVCON_BOXES_SIZE  65536u
/* feature-map arena (exporter --fmap-base) */
#define DVCON_ARENA_BASE  0x00800000u
#define DVCON_ARENA_SIZE  58720256u
/* second frame buffer, for double buffering */
#define DVCON_FRAME2_BASE  0x04000000u
#define DVCON_FRAME2_SIZE  67108864u

#define DVCON_ETHERTYPE    0x88B5u
#define DVCON_HDR_BYTES    16u
#define DVCON_MAX_PAYLOAD  1408u
#define DVCON_ACK_WINDOW   64u

#define DVCON_OP_WRITE_MEM  0x01u  /* payload -> SDRAM at addr */
#define DVCON_OP_ACK_REQ  0x06u  /* reply with the 64-bit received bitmap */
#define DVCON_OP_ACK  0x10u  /* FPGA -> host: the bitmap */

#define DVCON_REG_CTRL  0x00u  /* bit0 START, bit1 soft reset, bit2 ucode mode */
#define DVCON_REG_STATUS  0x01u  /* bit0 busy, bit1 done, bit2 error */
#define DVCON_REG_DESC_ADDR  0x06u  /* descriptor table base */
#define DVCON_REG_IMG_ADDR  0x07u  /* input frame base */
#define DVCON_REG_BOX_ADDR  0x08u  /* box list base */
#define DVCON_REG_CONF_THRESH  0x09u  /* INT8 confidence threshold */
#define DVCON_REG_NUM_BOXES  0x0Au  /* boxes written by the last frame */
#define DVCON_REG_IDENT  0x0Fu  /* 0xDC, ARRAY_SIZE, build id */
#define DVCON_REG_ETH_GOOD  0x3Au  /* ethernet frames with a good FCS */
#define DVCON_REG_ETH_BAD  0x3Bu  /* ethernet frames that failed FCS */
#define DVCON_REG_ETH_CMD  0x3Cu  /* command frames accepted */
#define DVCON_REG_ETH_BITMAP  0x3Du  /* low 32 bits of the ACK window bitmap */
#define DVCON_REG_MEMADDR  0x3Eu  /* SDRAM read cursor (write) */
#define DVCON_REG_MEMDATA  0x3Fu  /* word at the cursor; post-increments (read) */

/* Command header, big endian on the wire. */
struct dvcon_hdr {
    uint8_t  ver;
    uint8_t  opcode;
    uint8_t  flags;
    uint8_t  rsv;
    uint32_t seq;
    uint32_t addr;
    uint16_t len;
    uint16_t rsv2;
};

#endif /* DVCON_MEMMAP_H */
