// -----------------------------------------------------------------------------
// GENERATED by qrts/tools/port_rtl.py -- DO NOT EDIT THIS COPY.
//
// Source: DVCon_2026/DVCon_SoC_SRC/ACCELERATOR_IP/accel_dma_seq.sv
//
// Edit the source and re-run the porter:
//     python qrts/tools/port_rtl.py
//
// Xilinx synthesis attributes have been rewritten for Quartus. See the porter
// for what is rewritten and what still needs hand work.
// -----------------------------------------------------------------------------
// =============================================================================
// accel_dma_seq.sv — DMA sequencer bridging DDR memory <-> system_top
//
// system_top's `input_data` bus has NO ready/valid/stall — during
// loading_weights/streaming_acts it must be fed valid data every single
// cycle. A bursty AXI4 read can stall, so this sequencer prefetches the
// FULL weight tile + activation stream into local buffers first, then plays
// them out in lockstep with system_top's own phase strobes (mirrors the
// reference tb_system_top.sv's forcing block, just data-driven from memory
// instead of hardcoded identity/const-2).
//
// Fixed shape for this integration (per design decision): ARRAY_SIZE=32,
// K=96 activation rows. K=96 (not 32) is required, not a free choice —
// empirically verified against tb_system_top.sv: this legacy datapath's
// systolic wavefront needs the STREAM phase to run for enough cycles to
// fully drain (K must be well above ARRAY_SIZE). K=32 was tried first and
// broke even the original, already-passing reference testbench when swapped
// in unmodified — confirming it's an inherent pipeline-depth requirement of
// this datapath, not an integration bug. K=96 matches the reference exactly.
// CPU's IMG_DIM register is accepted but not used to vary shape; this
// sequencer always drives a fixed 32x96 run. Extending to CPU-configurable
// K is future work, not needed for this fixed-shape integration test.
//
// Memory layout expected at the addresses the CPU programs:
//   weight_addr : 1024 contiguous bytes, 32x32 int8, row-major
//   src_addr    : 3072 contiguous bytes, 96x32 int8, row-major
//   dst_addr    : 128 contiguous bytes, 32x int32 (one per output column)
// =============================================================================
`timescale 1ns/1ps

module accel_dma_seq #(
    parameter integer ARRAY_SIZE = 32,
    parameter integer DATA_WIDTH = 8,
    parameter integer K          = 32
)(
    input  wire        clk,
    input  wire        rst_n,

    // ---- from register file ----
    input  wire         start_pulse,
    input  wire [31:0]  src_addr,
    input  wire [31:0]  dst_addr,
    input  wire [31:0]  weight_addr,
    // img_dim intentionally unused (fixed shape, see header)

    // ---- to register file (status) ----
    output reg          busy,
    output reg          done,
    output reg          error,
    output reg  [3:0]   fsm_state,

    // ---- axi4_master: read side ----
    output reg          rd_start,
    output reg  [63:0]  rd_addr,
    output reg  [7:0]   rd_len,
    input  wire [63:0]  rd_data,
    input  wire         rd_data_valid,
    input  wire         rd_done,
    input  wire         rd_error,

    // ---- axi4_master: write side ----
    output reg          wr_start,
    output reg  [63:0]  wr_addr,
    output reg  [7:0]   wr_len,
    output wire [63:0]  wr_data,
    input  wire         wr_data_ready,
    input  wire         wr_done,
    input  wire         wr_error,

    // ---- system_top datapath ----
    output reg signed [DATA_WIDTH-1:0] input_data [0:ARRAY_SIZE-1],
    input  wire                        loading_weights,
    input  wire                        streaming_acts,
    input  wire                        sys_busy,
    input  wire                        sys_done,
    input  wire signed [ARRAY_SIZE*32-1:0] output_data,

    // ---- internal AXI4-Lite BFM driving system_top's own config port ----
    output reg          s_awvalid,
    output reg  [63:0]  s_awaddr,
    output reg          s_wvalid,
    output reg  [31:0]  s_wdata,
    output reg  [3:0]   s_wstrb,
    input  wire         s_awready,
    input  wire         s_wready,
    output reg          s_bready,
    input  wire         s_bvalid,
    input  wire [1:0]   s_bresp,
    output wire         s_arvalid,
    output wire [63:0]  s_araddr,
    input  wire         s_arready,
    output wire         s_rready,
    input  wire         s_rvalid,
    input  wire [31:0]  s_rdata,
    input  wire [1:0]   s_rresp
);

    localparam integer BUF_BYTES  = ARRAY_SIZE*ARRAY_SIZE; // 1024 (weight tile)
    localparam integer ACT_BYTES  = ARRAY_SIZE*K;           // 3072 (activation stream)
    localparam integer BEATS_BUF  = BUF_BYTES/8;            // 128
    localparam integer BEATS_RES  = ARRAY_SIZE/2;            // 16 (2x int32 / beat)
    // AXI4 arlen is 8-bit (max 256 beats/burst) — chunk the activation read
    // into CHUNK-beat bursts (weight tile fits in one chunk already).
    //
    // The FSM issues ACT_NUM_CHUNKS identical bursts of CHUNK_BEATS, so the
    // chunk size must divide ACT_BEATS_TOTAL exactly. A fixed 128 only does so
    // when ARRAY_SIZE=32; at 28 it leaves 80 beats that the loop never reads,
    // silently truncating the activation stream. Derive the chunk count first
    // and let the size follow, so every chunk stays equal for any ARRAY_SIZE.
    localparam integer ACT_BEATS_TOTAL = ACT_BYTES/8;                    // 336 @28
    localparam integer ACT_NUM_CHUNKS  = (ACT_BEATS_TOTAL + 255) / 256;  // 2 @28
    localparam integer CHUNK_BEATS     = ACT_BEATS_TOTAL/ACT_NUM_CHUNKS; // 168 @28

    // Fail loudly at elaboration if a future ARRAY_SIZE/K pair does not divide
    // evenly — the failure mode otherwise is silently short activation reads.
    initial begin
        if (CHUNK_BEATS*ACT_NUM_CHUNKS != ACT_BEATS_TOTAL) begin
            $fatal(1, "accel_dma_seq: ACT_BEATS_TOTAL=%0d not divisible into %0d equal chunks",
                   ACT_BEATS_TOTAL, ACT_NUM_CHUNKS);
        end
    end

    // system_top never gets read back through the internal lite bus
    assign s_arvalid = 1'b0;
    assign s_araddr  = 64'h0;
    assign s_rready  = 1'b0;

    // =========================================================================
    // Local buffers
    // =========================================================================
    reg [7:0]  weight_buf [0:BUF_BYTES-1];
    reg [7:0]  act_buf    [0:ACT_BYTES-1];
    reg [31:0] result_buf [0:ARRAY_SIZE-1];

    // =========================================================================
    // Free-running row counters mirroring tb_system_top's forcing block
    // =========================================================================
    reg [$clog2(ARRAY_SIZE)-1:0] w_row_idx;
    reg [$clog2(K)-1:0]          a_row_idx;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n)                    w_row_idx <= '0;
        else if (loading_weights)      w_row_idx <= w_row_idx + 1'b1;
        else                           w_row_idx <= '0;
    end

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n)                    a_row_idx <= '0;
        else if (streaming_acts)       a_row_idx <= a_row_idx + 1'b1;
        else                           a_row_idx <= '0;
    end

    integer di;
    always @(*) begin
        for (di = 0; di < ARRAY_SIZE; di = di + 1) input_data[di] = 8'sd0;
        if (loading_weights) begin
            for (di = 0; di < ARRAY_SIZE; di = di + 1)
                input_data[di] = weight_buf[w_row_idx*ARRAY_SIZE + di];
        end else if (streaming_acts) begin
            for (di = 0; di < ARRAY_SIZE; di = di + 1)
                input_data[di] = act_buf[a_row_idx*ARRAY_SIZE + di];
        end
    end

    // =========================================================================
    // Result write-data forwarding (2x int32 packed per 64-bit beat)
    // =========================================================================
    reg [7:0] wr_beat_cnt;
    // wr_beat_cnt runs 0..BEATS_RES inclusive, so at the end of a burst the raw
    // index would be result_buf[2*BEATS_RES+1] = [33] -- past the end of a
    // [0:31] array, which reads as X. Together with the array being
    // uninitialised before the first run, that left m_wdata sitting at X for
    // the whole simulation except the ~320 ns burst itself. AXI only samples
    // WDATA under WVALID so it was harmless, but it made the top-level
    // acc_m_axi_wdata trace unreadable. Drive a defined value outside the
    // valid beat range instead. Beats 0..BEATS_RES-1 are unchanged.
    reg res_valid;
    assign wr_data = (res_valid && (wr_beat_cnt < BEATS_RES))
                   ? {result_buf[wr_beat_cnt*2+1], result_buf[wr_beat_cnt*2]}
                   : 64'h0;

    // =========================================================================
    // Main sequencer FSM
    // =========================================================================
    localparam [3:0]
        S_IDLE           = 4'd0,
        S_RDW_WAIT       = 4'd1,
        S_RDA_WAIT       = 4'd2,
        S_CFG_IMG_ASSERT = 4'd3,
        S_CFG_IMG_WAIT   = 4'd4,
        S_CFG_IMG_WAITB  = 4'd5,
        S_CFG_CTRL_ASSERT= 4'd6,
        S_CFG_CTRL_WAIT  = 4'd7,
        S_CFG_CTRL_WAITB = 4'd8,
        S_RUN_WAIT       = 4'd9,
        S_RUN_DRAIN      = 4'd11,
        S_WRR_WAIT       = 4'd10;

    reg [3:0]  state;
    reg [7:0]  rdbeat_cnt;      // within-chunk beat index (0..127)
    reg [15:0] act_beat_abs;    // absolute beat index into act_buf (0..383)
    reg [3:0]  act_chunk_idx;   // which 128-beat chunk (0..ACT_NUM_CHUNKS-1)
    reg [31:0] dst_addr_lat;
    reg        aw_done_r, w_done_r;
    reg [2:0]  drain_cnt;
    integer    ri;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state        <= S_IDLE;
            rd_start     <= 1'b0; rd_addr <= 64'h0; rd_len <= 8'h0;
            wr_start     <= 1'b0; wr_addr <= 64'h0; wr_len <= 8'h0;
            rdbeat_cnt   <= 8'd0; wr_beat_cnt <= 8'd0; res_valid <= 1'b0;
            busy         <= 1'b0; done <= 1'b0; error <= 1'b0; fsm_state <= 4'd0;
            s_awvalid    <= 1'b0; s_awaddr <= 64'h0;
            s_wvalid     <= 1'b0; s_wdata  <= 32'h0; s_wstrb <= 4'h0;
            s_bready     <= 1'b0;
            aw_done_r    <= 1'b0; w_done_r <= 1'b0;
            dst_addr_lat <= 32'h0;
            drain_cnt    <= 3'd0;
            act_beat_abs <= 16'd0;
            act_chunk_idx<= 4'd0;
        end else begin
            rd_start  <= 1'b0;
            wr_start  <= 1'b0;
            fsm_state <= state;

            case (state)
                // ------------------------------------------------------------
                S_IDLE: begin
                    busy <= 1'b0;
                    if (start_pulse) begin
                        dst_addr_lat <= dst_addr;
                        busy         <= 1'b1;
                        done         <= 1'b0;
                        error        <= 1'b0;
                        rdbeat_cnt   <= 8'd0;
                        rd_addr      <= {32'h0, weight_addr};
                        rd_len       <= BEATS_BUF[7:0];
                        rd_start     <= 1'b1;
                        state        <= S_RDW_WAIT;
                    end
                end

                // ------------------------------------------------------------
                S_RDW_WAIT: begin
                    if (rd_data_valid) begin
                        weight_buf[rdbeat_cnt*8+0] <= rd_data[7:0];
                        weight_buf[rdbeat_cnt*8+1] <= rd_data[15:8];
                        weight_buf[rdbeat_cnt*8+2] <= rd_data[23:16];
                        weight_buf[rdbeat_cnt*8+3] <= rd_data[31:24];
                        weight_buf[rdbeat_cnt*8+4] <= rd_data[39:32];
                        weight_buf[rdbeat_cnt*8+5] <= rd_data[47:40];
                        weight_buf[rdbeat_cnt*8+6] <= rd_data[55:48];
                        weight_buf[rdbeat_cnt*8+7] <= rd_data[63:56];
                        rdbeat_cnt <= rdbeat_cnt + 8'd1;
                    end
                    if (rd_done) begin
                        if (rd_error) error <= 1'b1;
                        rdbeat_cnt    <= 8'd0;
                        act_beat_abs  <= 16'd0;
                        act_chunk_idx <= 4'd0;
                        rd_addr       <= {32'h0, src_addr};
                        rd_len        <= CHUNK_BEATS[7:0];
                        rd_start      <= 1'b1;
                        state         <= S_RDA_WAIT;
                    end
                end

                // ------------------------------------------------------------
                // Activation read: chunked into CHUNK_BEATS-beat bursts since
                // AXI4 arlen (8-bit, max 256) can't cover ACT_BEATS_TOTAL in one go.
                S_RDA_WAIT: begin
                    if (rd_data_valid) begin
                        act_buf[act_beat_abs*8+0] <= rd_data[7:0];
                        act_buf[act_beat_abs*8+1] <= rd_data[15:8];
                        act_buf[act_beat_abs*8+2] <= rd_data[23:16];
                        act_buf[act_beat_abs*8+3] <= rd_data[31:24];
                        act_buf[act_beat_abs*8+4] <= rd_data[39:32];
                        act_buf[act_beat_abs*8+5] <= rd_data[47:40];
                        act_buf[act_beat_abs*8+6] <= rd_data[55:48];
                        act_buf[act_beat_abs*8+7] <= rd_data[63:56];
                        act_beat_abs <= act_beat_abs + 16'd1;
                    end
                    if (rd_done) begin
                        if (rd_error) error <= 1'b1;
                        if (act_chunk_idx == ACT_NUM_CHUNKS-1) begin
                            state <= S_CFG_IMG_ASSERT;
                        end else begin
                            act_chunk_idx <= act_chunk_idx + 4'd1;
                            rd_addr       <= {32'h0, src_addr} + (act_beat_abs*8);
                            rd_len        <= CHUNK_BEATS[7:0];
                            rd_start      <= 1'b1;
                        end
                    end
                end

                // ------------------------------------------------------------
                // Drive system_top's own AXI4-Lite port: IMG_DIM then CTRL=1
                // ------------------------------------------------------------
                S_CFG_IMG_ASSERT: begin
                    s_awaddr  <= 64'h0000_0000_0000_0010; // REG_IMG_DIM
                    s_wdata   <= {K[15:0], ARRAY_SIZE[15:0]}; // rows=K, cols=ARRAY_SIZE
                    s_wstrb   <= 4'hF;
                    s_awvalid <= 1'b1;
                    s_wvalid  <= 1'b1;
                    aw_done_r <= 1'b0;
                    w_done_r  <= 1'b0;
                    state     <= S_CFG_IMG_WAIT;
                end
                S_CFG_IMG_WAIT: begin
                    if (s_awvalid && s_awready) begin s_awvalid <= 1'b0; aw_done_r <= 1'b1; end
                    if (s_wvalid  && s_wready)  begin s_wvalid  <= 1'b0; w_done_r  <= 1'b1; end
                    if ((aw_done_r || (s_awvalid && s_awready)) &&
                        (w_done_r  || (s_wvalid  && s_wready))) begin
                        s_bready <= 1'b1;
                        state    <= S_CFG_IMG_WAITB;
                    end
                end
                S_CFG_IMG_WAITB: begin
                    if (s_bvalid && s_bready) begin
                        s_bready <= 1'b0;
                        state    <= S_CFG_CTRL_ASSERT;
                    end
                end

                S_CFG_CTRL_ASSERT: begin
                    s_awaddr  <= 64'h0000_0000_0000_0000; // REG_CTRL
                    s_wdata   <= 32'h0000_0001;            // START
                    s_wstrb   <= 4'hF;
                    s_awvalid <= 1'b1;
                    s_wvalid  <= 1'b1;
                    aw_done_r <= 1'b0;
                    w_done_r  <= 1'b0;
                    state     <= S_CFG_CTRL_WAIT;
                end
                S_CFG_CTRL_WAIT: begin
                    if (s_awvalid && s_awready) begin s_awvalid <= 1'b0; aw_done_r <= 1'b1; end
                    if (s_wvalid  && s_wready)  begin s_wvalid  <= 1'b0; w_done_r  <= 1'b1; end
                    if ((aw_done_r || (s_awvalid && s_awready)) &&
                        (w_done_r  || (s_wvalid  && s_wready))) begin
                        s_bready <= 1'b1;
                        state    <= S_CFG_CTRL_WAITB;
                    end
                end
                S_CFG_CTRL_WAITB: begin
                    if (s_bvalid && s_bready) begin
                        s_bready <= 1'b0;
                        state    <= S_RUN_WAIT;
                    end
                end

                // ------------------------------------------------------------
                S_RUN_WAIT: begin
                    if (sys_done) begin
                        drain_cnt <= 3'd0;
                        state     <= S_RUN_DRAIN;
                    end
                end

                // output_data lags a few cycles behind sys_done (register_bank
                // pipeline latency) — tb_system_top.sv's own reference check
                // waits 4 cycles past sys_done before trusting output_data.
                S_RUN_DRAIN: begin
                    if (drain_cnt == 3'd4) begin
                        for (ri = 0; ri < ARRAY_SIZE; ri = ri + 1)
                            result_buf[ri] <= output_data[ri*32 +: 32];
                        res_valid   <= 1'b1;
                        wr_beat_cnt <= 8'd0;
                        wr_addr     <= {32'h0, dst_addr_lat};
                        wr_len      <= BEATS_RES[7:0];
                        wr_start    <= 1'b1;
                        state       <= S_WRR_WAIT;
                    end else begin
                        drain_cnt <= drain_cnt + 3'd1;
                    end
                end

                // ------------------------------------------------------------
                S_WRR_WAIT: begin
                    if (wr_data_ready) wr_beat_cnt <= wr_beat_cnt + 8'd1;
                    if (wr_done) begin
                        if (wr_error) error <= 1'b1;
                        busy  <= 1'b0;
                        done  <= 1'b1;
                        state <= S_IDLE;
                    end
                end

                default: state <= S_IDLE;
            endcase
        end
    end

endmodule
