// -----------------------------------------------------------------------------
// GENERATED by qrts/tools/port_rtl.py -- DO NOT EDIT THIS COPY.
//
// Source: DVCFinal/rtl/Accelerator_Top.sv
//
// Edit the source and re-run the porter:
//     python qrts/tools/port_rtl.py
//
// Xilinx synthesis attributes have been rewritten for Quartus. See the porter
// for what is rewritten and what still needs hand work.
// -----------------------------------------------------------------------------
// =============================================================================
// Accelerator_Top.sv — DVCFinal: whole-network YOLO26n accelerator
//
// Port list matches Top.vhd's `component Accelerator_Top` EXACTLY, so Top.vhd
// is still never edited -- same socket as Stage 3A/3B.
//
// What changed versus Stage 3B: the accelerator no longer runs one GEMM tile
// per START. It walks the entire YOLO26n graph autonomously.
//
//   s_axi_*  -> yolo_axi4_slave_regs   CPU config (superset of the 3B map)
//   m_axi_*  -> axi4_master            one DDR port, shared via yolo_axi_arbiter
//
//                       ┌─ yolo_layer_sequencer  (descriptor walk)
//   yolo_axi_arbiter ───┼─ yolo_conv_engine      (tiled GEMM -> system_top)
//                       ├─ yolo_elem_engine      (concat/add/upsample/pool)
//                       └─ yolo_detect_engine    (decode, no NMS)
//
//   system_top (USE_BRAM_PATH=0, ARRAY_SIZE x ARRAY_SIZE INT8 systolic array)
//
// GEMM compatibility mode is retained: CTRL bit1 = 0 selects the Stage 3B
// single-tile path (accel_dma_seq), so the existing 24x24 identity test app
// still runs unmodified against this bitstream. That matters for bring-up --
// it isolates "the array works" from "the sequencer works".
//
// ---------------------------------------------------------------------------
// ARRAY_SIZE defaults to 24, which is the xc7k325t value: 840 DSP with 60 used
// by the base SoC leaves 780, one DSP per PE means 24x24 = 576 (636 total,
// 76%), and 28x28 = 784 would be 844 -- over. Do not raise it without
// re-checking GEN_BIT_OUT/report_utilization_summary.rpt. See PORT-NOTES.md
// change 1.
//
// It is a PARAMETER, not a localparam, because the DE2-115 build overrides it
// to 16 (EP4CE115 has 532 9-bit multiplier elements, two per 18x18 block, so
// 16x16 = 256 fits and 24x24 = 576 does not). It was a localparam until a
// dvcon_top synthesis run reported 462,600 logic elements against a
// 114,480-LE part: the override reached dvcon_regs and stopped here, and
// Analysis & Synthesis still called that "successful, 0 errors".
//
// Changing it is not a hardware-only decision -- export_yolo26n.py emits
// weight tiles in this engine's exact loop order, so a model exported for one
// value reads the wrong tile at any other, silently.
// ---------------------------------------------------------------------------
`timescale 1ns/1ps

`include "ucode_pkg.svh"

module Accelerator_Top #(
    // The systolic array's edge. NOT a hardware-only knob: export_yolo26n.py
    // emits weight tiles in the engine's exact loop order, so a model exported
    // for one value reads the wrong tile at any other. 24 is the Kintex-7
    // value; the DE2-115 build passes 16, which is what its model is exported
    // for. It was a localparam until a dvcon_top synthesis run reported
    // 462,600 logic elements against a 114,480-LE part -- the parameter on
    // dvcon_top reached dvcon_regs and stopped here.
    parameter integer ARRAY_SIZE = 24
) (
    input  wire         s_axi_aclk,
    input  wire         s_axi_aresetn,

    // ----- Master (DDR-facing DMA) -----
    output wire         m_axi_awvalid,
    output wire [11:0]  m_axi_awid,
    output wire [7:0]   m_axi_awlen,
    output wire [2:0]   m_axi_awsize,
    output wire [1:0]   m_axi_awburst,
    output wire [0:0]   m_axi_awlock,
    output wire [3:0]   m_axi_awcache,
    output wire [3:0]   m_axi_awqos,
    output wire [63:0]  m_axi_awaddr,
    output wire [2:0]   m_axi_awprot,
    input  wire         m_axi_awready,

    output wire         m_axi_wvalid,
    output wire         m_axi_wlast,
    output wire [63:0]  m_axi_wdata,
    output wire [7:0]   m_axi_wstrb,
    input  wire         m_axi_wready,

    output wire         m_axi_bready,
    input  wire         m_axi_bvalid,
    input  wire [11:0]  m_axi_bid,
    input  wire [1:0]   m_axi_bresp,

    output wire         m_axi_arvalid,
    output wire [11:0]  m_axi_arid,
    output wire [7:0]   m_axi_arlen,
    output wire [2:0]   m_axi_arsize,
    output wire [1:0]   m_axi_arburst,
    output wire [0:0]   m_axi_arlock,
    output wire [3:0]   m_axi_arcache,
    output wire [3:0]   m_axi_arqos,
    output wire [63:0]  m_axi_araddr,
    output wire [2:0]   m_axi_arprot,
    input  wire         m_axi_arready,

    output wire         m_axi_rready,
    input  wire         m_axi_rvalid,
    input  wire [11:0]  m_axi_rid,
    input  wire         m_axi_rlast,
    input  wire [1:0]   m_axi_rresp,
    input  wire [63:0]  m_axi_rdata,

    // ----- Slave (CPU config) -----
    input  wire [11:0]  s_axi_awid,
    input  wire [63:0]  s_axi_awaddr,
    input  wire [7:0]   s_axi_awlen,
    input  wire [2:0]   s_axi_awsize,
    input  wire [1:0]   s_axi_awburst,
    input  wire         s_axi_awlock,
    input  wire [3:0]   s_axi_awcache,
    input  wire [2:0]   s_axi_awprot,
    input  wire [3:0]   s_axi_awqos,
    input  wire         s_axi_awvalid,
    output wire         s_axi_awready,

    input  wire [63:0]  s_axi_wdata,
    input  wire [7:0]   s_axi_wstrb,
    input  wire         s_axi_wlast,
    input  wire         s_axi_wvalid,
    output wire         s_axi_wready,

    input  wire         s_axi_bready,
    output wire [11:0]  s_axi_bid,
    output wire [1:0]   s_axi_bresp,
    output wire         s_axi_bvalid,

    input  wire [11:0]  s_axi_arid,
    input  wire [63:0]  s_axi_araddr,
    input  wire [7:0]   s_axi_arlen,
    input  wire [2:0]   s_axi_arsize,
    input  wire [1:0]   s_axi_arburst,
    input  wire         s_axi_arlock,
    input  wire [3:0]   s_axi_arcache,
    input  wire [2:0]   s_axi_arprot,
    input  wire [3:0]   s_axi_arqos,
    input  wire         s_axi_arvalid,
    output wire         s_axi_arready,

    input  wire         s_axi_rready,
    output wire [11:0]  s_axi_rid,
    output wire [63:0]  s_axi_rdata,
    output wire [1:0]   s_axi_rresp,
    output wire         s_axi_rlast,
    output wire         s_axi_rvalid
);

    localparam integer DATA_WIDTH = 8;
    localparam integer ACC_WIDTH  = 32;

    wire clk   = s_axi_aclk;
    wire rst_n = s_axi_aresetn;

    // =========================================================================
    // CPU register file
    // =========================================================================
    wire        start_pulse, mode_yolo, mode_ucode;
    wire [31:0] src_addr, dst_addr, img_dim, weight_addr;
    wire [31:0] desc_addr, img_addr, box_addr;
    wire signed [7:0] conf_thresh;

    // Microcode RAM write port (register file -> ucode_engine) and the PC it
    // reports back. Declared before first use so nothing is implicitly wired.
    wire        ucode_we;
    wire [9:0]  ucode_waddr;
    wire [63:0] ucode_wdata;
    wire [15:0] uc_pc;
    wire        gm_start, gm_done, gm_error;

    // Status is muxed from whichever path CTRL bit1 selected.
    wire        seq_busy, seq_done, seq_error;
    wire [3:0]  seq_fsm;
    wire [15:0] seq_layer, seq_boxes;
    wire        gemm_busy, gemm_done, gemm_error;
    wire [3:0]  gemm_fsm;

    wire        st_busy  = mode_yolo ? seq_busy  : gemm_busy;
    wire        st_done  = mode_yolo ? seq_done  : gemm_done;
    wire        st_error = mode_yolo ? seq_error : gemm_error;
    wire [3:0]  st_fsm   = mode_yolo ? seq_fsm   : gemm_fsm;

    yolo_axi4_slave_regs #(.ID_WIDTH(12), .ADDR_WIDTH(64), .DATA_WIDTH(64)) u_regs (
        .clk(clk), .rst_n(rst_n),
        .s_axi_awid(s_axi_awid), .s_axi_awaddr(s_axi_awaddr), .s_axi_awlen(s_axi_awlen),
        .s_axi_awsize(s_axi_awsize), .s_axi_awburst(s_axi_awburst), .s_axi_awlock(s_axi_awlock),
        .s_axi_awcache(s_axi_awcache), .s_axi_awprot(s_axi_awprot), .s_axi_awqos(s_axi_awqos),
        .s_axi_awvalid(s_axi_awvalid), .s_axi_awready(s_axi_awready),
        .s_axi_wdata(s_axi_wdata), .s_axi_wstrb(s_axi_wstrb), .s_axi_wlast(s_axi_wlast),
        .s_axi_wvalid(s_axi_wvalid), .s_axi_wready(s_axi_wready),
        .s_axi_bready(s_axi_bready), .s_axi_bid(s_axi_bid), .s_axi_bresp(s_axi_bresp),
        .s_axi_bvalid(s_axi_bvalid),
        .s_axi_arid(s_axi_arid), .s_axi_araddr(s_axi_araddr), .s_axi_arlen(s_axi_arlen),
        .s_axi_arsize(s_axi_arsize), .s_axi_arburst(s_axi_arburst), .s_axi_arlock(s_axi_arlock),
        .s_axi_arcache(s_axi_arcache), .s_axi_arprot(s_axi_arprot), .s_axi_arqos(s_axi_arqos),
        .s_axi_arvalid(s_axi_arvalid), .s_axi_arready(s_axi_arready),
        .s_axi_rready(s_axi_rready), .s_axi_rid(s_axi_rid), .s_axi_rdata(s_axi_rdata),
        .s_axi_rresp(s_axi_rresp), .s_axi_rlast(s_axi_rlast), .s_axi_rvalid(s_axi_rvalid),
        .start_pulse(start_pulse), .mode_yolo(mode_yolo),
        .mode_ucode(mode_ucode),
        .src_addr(src_addr), .dst_addr(dst_addr),
        .img_dim(img_dim), .weight_addr(weight_addr),
        .desc_addr(desc_addr), .img_addr(img_addr), .box_addr(box_addr),
        .conf_thresh(conf_thresh),
        .busy_in(st_busy), .done_in(st_done), .error_in(st_error), .fsm_in(st_fsm),
        .num_boxes_in(seq_boxes), .layer_idx_in(seq_layer),
        .ucode_pc_in(uc_pc),
        .ucode_we(ucode_we), .ucode_waddr(ucode_waddr), .ucode_wdata(ucode_wdata)
    );

    // START is steered to exactly one consumer so both paths cannot run at once.
    wire start_yolo = start_pulse &&  mode_yolo;
    wire start_gemm = start_pulse && !mode_yolo;

    // =========================================================================
    // Single AXI4 master, fed by the arbiter
    // =========================================================================
    wire         m_rd_start; wire [63:0] m_rd_addr; wire [7:0] m_rd_len;
    wire [63:0]  m_rd_data;  wire m_rd_data_valid, m_rd_done, m_rd_error;
    wire         m_wr_start; wire [63:0] m_wr_addr; wire [7:0] m_wr_len;
    wire [63:0]  m_wr_data;  wire m_wr_data_ready, m_wr_done, m_wr_error;
    wire [7:0]   m_wr_strb;

    axi4_master #(.ADDR_WIDTH(64), .DATA_WIDTH(64), .ID_WIDTH(12)) u_axi4_master (
        .clk(clk), .rst_n(rst_n),
        .m_arid(m_axi_arid), .m_araddr(m_axi_araddr), .m_arlen(m_axi_arlen),
        .m_arsize(m_axi_arsize), .m_arburst(m_axi_arburst), .m_arprot(m_axi_arprot),
        .m_arvalid(m_axi_arvalid), .m_arready(m_axi_arready),
        .m_rid(m_axi_rid), .m_rdata(m_axi_rdata), .m_rresp(m_axi_rresp),
        .m_rlast(m_axi_rlast), .m_rvalid(m_axi_rvalid), .m_rready(m_axi_rready),
        .m_awid(m_axi_awid), .m_awaddr(m_axi_awaddr), .m_awlen(m_axi_awlen),
        .m_awsize(m_axi_awsize), .m_awburst(m_axi_awburst), .m_awprot(m_axi_awprot),
        .m_awvalid(m_axi_awvalid), .m_awready(m_axi_awready),
        .m_wdata(m_axi_wdata), .m_wstrb(m_axi_wstrb), .m_wlast(m_axi_wlast),
        .m_wvalid(m_axi_wvalid), .m_wready(m_axi_wready),
        .m_bready(m_axi_bready), .m_bvalid(m_axi_bvalid), .m_bid(m_axi_bid),
        .m_bresp(m_axi_bresp),
        .rd_start(m_rd_start), .rd_addr(m_rd_addr), .rd_len(m_rd_len),
        .rd_data(m_rd_data), .rd_data_valid(m_rd_data_valid),
        .rd_done(m_rd_done), .rd_error(m_rd_error),
        .wr_start(m_wr_start), .wr_addr(m_wr_addr), .wr_len(m_wr_len),
        .wr_data(m_wr_data), .wr_strb(m_wr_strb), .wr_data_ready(m_wr_data_ready),
        .wr_done(m_wr_done), .wr_error(m_wr_error)
    );

    assign m_axi_awlock  = 1'b0;
    assign m_axi_arlock  = 1'b0;
    // Non-cacheable, non-bufferable: firmware flushes the DMA buffers before
    // START. Driven explicitly so they are not high-Z in simulation.
    assign m_axi_awcache = 4'b0000;
    assign m_axi_arcache = 4'b0000;
    assign m_axi_awqos   = 4'b0000;
    assign m_axi_arqos   = 4'b0000;

    // =========================================================================
    // Arbiter fan-in
    // =========================================================================
    // 0 = sequencer, 1 = conv, 2 = elementwise, 3 = detect, 4 = legacy GEMM DMA.
    // The legacy path shares slot 1 with the conv engine because CTRL bit1
    // guarantees they are never active in the same frame.
    wire        a0_rd_start, a0_wr_start; wire [63:0] a0_rd_addr, a0_wr_addr;
    wire [7:0]  a0_rd_len, a0_wr_len; wire [63:0] a0_wr_data;
    wire [7:0]  a0_wr_strb;
    wire [63:0] a0_rd_data; wire a0_rd_data_valid, a0_rd_done, a0_rd_error;
    wire        a0_wr_data_ready, a0_wr_done, a0_wr_error;

    wire        a1_rd_start, a1_wr_start; wire [63:0] a1_rd_addr, a1_wr_addr;
    wire [7:0]  a1_rd_len, a1_wr_len; wire [63:0] a1_wr_data;
    wire [7:0]  a1_wr_strb;
    wire [63:0] a1_rd_data; wire a1_rd_data_valid, a1_rd_done, a1_rd_error;
    wire        a1_wr_data_ready, a1_wr_done, a1_wr_error;

    wire        a2_rd_start, a2_wr_start; wire [63:0] a2_rd_addr, a2_wr_addr;
    wire [7:0]  a2_rd_len, a2_wr_len; wire [63:0] a2_wr_data;
    wire [7:0]  a2_wr_strb;
    wire [63:0] a2_rd_data; wire a2_rd_data_valid, a2_rd_done, a2_rd_error;
    wire        a2_wr_data_ready, a2_wr_done, a2_wr_error;

    wire        a3_rd_start, a3_wr_start; wire [63:0] a3_rd_addr, a3_wr_addr;
    wire [7:0]  a3_rd_len, a3_wr_len; wire [63:0] a3_wr_data;
    wire [7:0]  a3_wr_strb;
    wire [63:0] a3_rd_data; wire a3_rd_data_valid, a3_rd_done, a3_rd_error;
    wire        a3_wr_data_ready, a3_wr_done, a3_wr_error;

    // Conv engine and the legacy GEMM sequencer both drive slot 1.
    wire        cv_rd_start, cv_wr_start; wire [63:0] cv_rd_addr, cv_wr_addr;
    wire [7:0]  cv_rd_len, cv_wr_len; wire [63:0] cv_wr_data;
    wire [7:0]  cv_wr_strb;
    wire        lg_rd_start, lg_wr_start; wire [63:0] lg_rd_addr, lg_wr_addr;
    wire [7:0]  lg_rd_len, lg_wr_len; wire [63:0] lg_wr_data;
    // The legacy GEMM path writes whole 8-byte beats, so every lane is live.
    wire [7:0]  lg_wr_strb = 8'hFF;

    assign a1_rd_start = mode_yolo ? cv_rd_start : lg_rd_start;
    assign a1_rd_addr  = mode_yolo ? cv_rd_addr  : lg_rd_addr;
    assign a1_rd_len   = mode_yolo ? cv_rd_len   : lg_rd_len;
    assign a1_wr_start = mode_yolo ? cv_wr_start : lg_wr_start;
    assign a1_wr_addr  = mode_yolo ? cv_wr_addr  : lg_wr_addr;
    assign a1_wr_len   = mode_yolo ? cv_wr_len   : lg_wr_len;
    assign a1_wr_data  = mode_yolo ? cv_wr_data  : lg_wr_data;
    assign a1_wr_strb  = mode_yolo ? cv_wr_strb  : lg_wr_strb;

    yolo_axi_arbiter u_arb (
        .clk(clk), .rst_n(rst_n),
        .s0_rd_start(a0_rd_start), .s0_rd_addr(a0_rd_addr), .s0_rd_len(a0_rd_len),
        .s0_rd_data(a0_rd_data), .s0_rd_data_valid(a0_rd_data_valid),
        .s0_rd_done(a0_rd_done), .s0_rd_error(a0_rd_error),
        .s0_wr_start(a0_wr_start), .s0_wr_addr(a0_wr_addr), .s0_wr_len(a0_wr_len),
        .s0_wr_data(a0_wr_data), .s0_wr_strb(a0_wr_strb), .s0_wr_data_ready(a0_wr_data_ready),
        .s0_wr_done(a0_wr_done), .s0_wr_error(a0_wr_error),

        .s1_rd_start(a1_rd_start), .s1_rd_addr(a1_rd_addr), .s1_rd_len(a1_rd_len),
        .s1_rd_data(a1_rd_data), .s1_rd_data_valid(a1_rd_data_valid),
        .s1_rd_done(a1_rd_done), .s1_rd_error(a1_rd_error),
        .s1_wr_start(a1_wr_start), .s1_wr_addr(a1_wr_addr), .s1_wr_len(a1_wr_len),
        .s1_wr_data(a1_wr_data), .s1_wr_strb(a1_wr_strb), .s1_wr_data_ready(a1_wr_data_ready),
        .s1_wr_done(a1_wr_done), .s1_wr_error(a1_wr_error),

        .s2_rd_start(a2_rd_start), .s2_rd_addr(a2_rd_addr), .s2_rd_len(a2_rd_len),
        .s2_rd_data(a2_rd_data), .s2_rd_data_valid(a2_rd_data_valid),
        .s2_rd_done(a2_rd_done), .s2_rd_error(a2_rd_error),
        .s2_wr_start(a2_wr_start), .s2_wr_addr(a2_wr_addr), .s2_wr_len(a2_wr_len),
        .s2_wr_data(a2_wr_data), .s2_wr_strb(a2_wr_strb), .s2_wr_data_ready(a2_wr_data_ready),
        .s2_wr_done(a2_wr_done), .s2_wr_error(a2_wr_error),

        .s3_rd_start(a3_rd_start), .s3_rd_addr(a3_rd_addr), .s3_rd_len(a3_rd_len),
        .s3_rd_data(a3_rd_data), .s3_rd_data_valid(a3_rd_data_valid),
        .s3_rd_done(a3_rd_done), .s3_rd_error(a3_rd_error),
        .s3_wr_start(a3_wr_start), .s3_wr_addr(a3_wr_addr), .s3_wr_len(a3_wr_len),
        .s3_wr_data(a3_wr_data), .s3_wr_strb(a3_wr_strb), .s3_wr_data_ready(a3_wr_data_ready),
        .s3_wr_done(a3_wr_done), .s3_wr_error(a3_wr_error),

        .m_rd_start(m_rd_start), .m_rd_addr(m_rd_addr), .m_rd_len(m_rd_len),
        .m_rd_data(m_rd_data), .m_rd_data_valid(m_rd_data_valid),
        .m_rd_done(m_rd_done), .m_rd_error(m_rd_error),
        .m_wr_start(m_wr_start), .m_wr_addr(m_wr_addr), .m_wr_len(m_wr_len),
        .m_wr_data(m_wr_data), .m_wr_strb(m_wr_strb), .m_wr_data_ready(m_wr_data_ready),
        .m_wr_done(m_wr_done), .m_wr_error(m_wr_error)
    );

    // =========================================================================
    // system_top datapath (shared by the conv engine and the legacy GEMM path)
    // =========================================================================
    wire signed [DATA_WIDTH-1:0] input_data [0:ARRAY_SIZE-1];
    wire signed [ARRAY_SIZE*32-1:0] output_data;
    wire [31:0] perf_cycles;
    wire        perf_valid;
    wire [ARRAY_SIZE-1:0] result_valid;
    wire        loading_weights, streaming_acts, sys_busy, sys_done;
    wire [31:0] st_src_addr, st_dst_addr, st_weight_addr;
    wire signed [DATA_WIDTH-1:0] out_vec [0:ARRAY_SIZE-1];
    wire        out_rd_valid;

    // system_top's own AXI4-Lite config port, driven by conv engine or legacy.
    wire        i_s_awvalid; wire [63:0] i_s_awaddr;
    wire        i_s_wvalid;  wire [31:0] i_s_wdata; wire [3:0] i_s_wstrb;
    wire        i_s_awready, i_s_wready;
    wire        i_s_bready;  wire i_s_bvalid; wire [1:0] i_s_bresp;

    wire        cv_awvalid, cv_wvalid, cv_bready;
    wire [63:0] cv_awaddr;  wire [31:0] cv_wdata; wire [3:0] cv_wstrb;
    wire        lg_awvalid, lg_wvalid, lg_bready;
    wire [63:0] lg_awaddr;  wire [31:0] lg_wdata; wire [3:0] lg_wstrb;

    assign i_s_awvalid = mode_yolo ? cv_awvalid : lg_awvalid;
    assign i_s_awaddr  = mode_yolo ? cv_awaddr  : lg_awaddr;
    assign i_s_wvalid  = mode_yolo ? cv_wvalid  : lg_wvalid;
    assign i_s_wdata   = mode_yolo ? cv_wdata   : lg_wdata;
    assign i_s_wstrb   = mode_yolo ? cv_wstrb   : lg_wstrb;
    assign i_s_bready  = mode_yolo ? cv_bready  : lg_bready;

    // input_data likewise comes from whichever path owns the array.
    wire signed [DATA_WIDTH-1:0] cv_input_data [0:ARRAY_SIZE-1];
    wire signed [DATA_WIDTH-1:0] lg_input_data [0:ARRAY_SIZE-1];
    genvar gi;
    generate
        for (gi = 0; gi < ARRAY_SIZE; gi = gi + 1) begin : g_idmux
            assign input_data[gi] = mode_yolo ? cv_input_data[gi]
                                              : lg_input_data[gi];
        end
    endgenerate

    system_top #(
        .ARRAY_SIZE(ARRAY_SIZE), .DATA_WIDTH(DATA_WIDTH),
        .ADDR_WIDTH(64), .AXI_DATA_W(32), .ACCUM_WIDTH(ACC_WIDTH),
        .USE_BRAM_PATH(0)
    ) u_system_top (
        .clk(clk), .rst_n(rst_n),
        .s_awvalid(i_s_awvalid), .s_awready(i_s_awready), .s_awaddr(i_s_awaddr),
        .s_wvalid(i_s_wvalid), .s_wready(i_s_wready), .s_wdata(i_s_wdata),
        .s_wstrb(i_s_wstrb),
        .s_bvalid(i_s_bvalid), .s_bready(i_s_bready), .s_bresp(i_s_bresp),
        .s_arvalid(1'b0), .s_arready(), .s_araddr(64'h0),
        .s_rvalid(), .s_rready(1'b0), .s_rdata(), .s_rresp(),
        .input_data(input_data),
        .output_data(output_data),
        .perf_cycles(perf_cycles), .perf_valid(perf_valid),
        .result_valid(result_valid),
        .out_vec(out_vec), .out_rd_valid(out_rd_valid),
        .loading_weights(loading_weights), .streaming_acts(streaming_acts),
        .sys_busy(sys_busy), .sys_done(sys_done),
        .src_addr(st_src_addr), .dst_addr(st_dst_addr),
        .weight_addr(st_weight_addr)
    );

    // =========================================================================
    // Layer sequencer (slot 0)
    // =========================================================================
    wire        ce_start, ce_busy, ce_done, ce_error;
    wire [31:0] ce_src, ce_dst, ce_wgt, ce_bias;
    wire [15:0] ce_in_w, ce_in_h, ce_in_c, ce_out_w, ce_out_h, ce_out_c;
    wire [3:0]  ce_k, ce_s, ce_p, ce_act;
    wire [15:0] ce_rqm; wire [4:0] ce_rqs; wire ce_dw;
    wire [15:0] ce_ascale;

    wire        ee_start, ee_busy, ee_done, ee_error;
    wire [31:0] ee_op, ee_src0, ee_src1, ee_dst, ee_aux0, ee_aux1;
    wire [15:0] ee_in_w, ee_in_h, ee_in_c, ee_in_c1, ee_out_w, ee_out_h, ee_out_c;

    wire        de_start, de_busy, de_done, de_error, de_flush;
    wire [31:0] de_src, de_dst, de_level_stride;
    wire [15:0] de_in_w, de_in_h, de_in_c, de_nbox, de_rqm;
    wire [4:0]  de_rqs;


    // =========================================================================
    // Two YOLO-mode control paths, selected by CTRL bit2 (mode_ucode)
    //
    //   0 (default)  yolo_layer_sequencer -- walks the 181-descriptor table in
    //                DRAM. No instruction-count ceiling, the exporter already
    //                emits its table, and sw/yolo_model.h already mirrors the
    //                64-byte record.
    //   1            ucode_engine -- experimental. Its instruction RAM holds
    //                1024 words and no program for this network exists, so
    //                starting it runs whatever was last loaded.
    //
    // The sequencer is the reason DESC_ADDR/IMG_ADDR/BOX_ADDR exist. Until it
    // was instantiated those three registers were write-only dead ends: the
    // host could set them, read them back, and nothing consumed them.
    // =========================================================================

    // ---- sequencer (path 0) outputs ----
    wire        sq_busy, sq_done, sq_error;
    wire [3:0]  sq_fsm;
    wire [15:0] sq_layer, sq_boxes;
    wire        sq_ce_start, sq_ee_start, sq_de_start, sq_de_flush;
    wire [31:0] sq_ce_src, sq_ce_dst, sq_ce_wgt, sq_ce_bias;
    wire [15:0] sq_ce_in_w, sq_ce_in_h, sq_ce_in_c;
    wire [15:0] sq_ce_out_w, sq_ce_out_h, sq_ce_out_c;
    wire [3:0]  sq_ce_k, sq_ce_s, sq_ce_p, sq_ce_act;
    wire [15:0] sq_ce_rqm; wire [4:0] sq_ce_rqs; wire sq_ce_dw;
    wire [15:0] sq_ce_ascale;
    wire [31:0] sq_ee_op, sq_ee_src0, sq_ee_src1, sq_ee_dst;
    wire [31:0] sq_ee_aux0, sq_ee_aux1;
    wire [15:0] sq_ee_in_w, sq_ee_in_h, sq_ee_in_c, sq_ee_in_c1;
    wire [15:0] sq_ee_out_w, sq_ee_out_h, sq_ee_out_c;
    wire [31:0] sq_de_src, sq_de_dst, sq_de_level_stride;
    wire [15:0] sq_de_in_w, sq_de_in_h, sq_de_in_c, sq_de_rqm;
    wire [4:0]  sq_de_rqs;

    // ---- microcode engine (path 1) outputs ----
    wire        uc_busy, uc_done, uc_error;
    wire [3:0]  uc_fsm;
    wire [15:0] uc_boxes;
    wire        uc_ce_start, uc_ee_start, uc_de_start, uc_de_flush;
    wire [31:0] uc_ce_src, uc_ce_dst, uc_ce_wgt, uc_ce_bias;
    wire [15:0] uc_ce_in_w, uc_ce_in_h, uc_ce_in_c;
    wire [15:0] uc_ce_out_w, uc_ce_out_h, uc_ce_out_c;
    wire [3:0]  uc_ce_k, uc_ce_s, uc_ce_p, uc_ce_act;
    wire [15:0] uc_ce_rqm; wire [4:0] uc_ce_rqs;
    wire [31:0] uc_ee_op, uc_ee_src1, uc_ee_aux0, uc_ee_aux1;
    wire [15:0] uc_ee_in_c1;
    wire [15:0] p_groups;

    // START reaches exactly one of them.
    wire start_seq   = start_yolo && !mode_ucode;
    wire start_ucode = start_yolo &&  mode_ucode;

    yolo_layer_sequencer #(
        .ARRAY_SIZE(ARRAY_SIZE), .DATA_WIDTH(DATA_WIDTH), .ACC_WIDTH(ACC_WIDTH)
    ) u_seq (
        .clk(clk), .rst_n(rst_n),
        .start_pulse(start_seq),
        .desc_base(desc_addr), .img_addr(img_addr), .out_addr(box_addr),
        .busy(sq_busy), .done(sq_done), .error(sq_error),
        .fsm_state(sq_fsm), .layer_idx(sq_layer), .num_boxes(sq_boxes),
        // The sequencer fetches descriptors itself -- arbiter slot 0 exists
        // for exactly this and was parked while it was uninstantiated.
        .rd_start(a0_rd_start), .rd_addr(a0_rd_addr), .rd_len(a0_rd_len),
        .rd_data(a0_rd_data), .rd_data_valid(a0_rd_data_valid),
        .rd_done(a0_rd_done), .rd_error(a0_rd_error),
        .wr_start(a0_wr_start), .wr_addr(a0_wr_addr), .wr_len(a0_wr_len),
        .wr_data(a0_wr_data), .wr_data_ready(a0_wr_data_ready),
        .wr_done(a0_wr_done), .wr_error(a0_wr_error),
        .ce_start(sq_ce_start),
        .ce_src_addr(sq_ce_src), .ce_dst_addr(sq_ce_dst),
        .ce_wgt_addr(sq_ce_wgt), .ce_bias_addr(sq_ce_bias),
        .ce_in_w(sq_ce_in_w), .ce_in_h(sq_ce_in_h), .ce_in_c(sq_ce_in_c),
        .ce_out_w(sq_ce_out_w), .ce_out_h(sq_ce_out_h), .ce_out_c(sq_ce_out_c),
        .ce_kernel(sq_ce_k), .ce_stride(sq_ce_s), .ce_pad(sq_ce_p),
        .ce_act(sq_ce_act),
        .ce_rq_mult(sq_ce_rqm), .ce_rq_shift(sq_ce_rqs),
        .ce_act_scale(sq_ce_ascale),
        .ce_depthwise(sq_ce_dw),
        .ce_busy(ce_busy), .ce_done(ce_done), .ce_error(ce_error),
        .ee_start(sq_ee_start), .ee_op(sq_ee_op),
        .ee_src0(sq_ee_src0), .ee_src1(sq_ee_src1), .ee_dst(sq_ee_dst),
        .ee_in_w(sq_ee_in_w), .ee_in_h(sq_ee_in_h),
        .ee_in_c(sq_ee_in_c), .ee_in_c1(sq_ee_in_c1),
        .ee_out_w(sq_ee_out_w), .ee_out_h(sq_ee_out_h), .ee_out_c(sq_ee_out_c),
        .ee_aux0(sq_ee_aux0), .ee_aux1(sq_ee_aux1),
        .ee_busy(ee_busy), .ee_done(ee_done), .ee_error(ee_error),
        .de_start(sq_de_start), .de_src(sq_de_src), .de_dst(sq_de_dst),
        .de_in_w(sq_de_in_w), .de_in_h(sq_de_in_h), .de_in_c(sq_de_in_c),
        .de_level_stride(sq_de_level_stride),
        .de_rq_mult(sq_de_rqm), .de_rq_shift(sq_de_rqs),
        .de_flush(sq_de_flush),
        .de_busy(de_busy), .de_done(de_done), .de_num_boxes(de_nbox),
        .de_error(de_error)
    );

    ucode_engine #(
        .DEPTH(UCODE_DEPTH), .AW(UCODE_AW)
    ) u_ucode (
        .clk(clk), .rst_n(rst_n),
        .start_pulse(start_ucode),
        .busy(uc_busy), .done(uc_done), .error(uc_error),
        .fsm_state(uc_fsm), .pc_out(uc_pc),
        .ucode_we(ucode_we), .ucode_waddr(ucode_waddr), .ucode_wdata(ucode_wdata),
        // parameter block -> every engine
        .p_src0(uc_ce_src), .p_src1(uc_ee_src1), .p_dst(uc_ce_dst),
        .p_wgt(uc_ce_wgt), .p_bias(uc_ce_bias),
        .p_in_w(uc_ce_in_w), .p_in_h(uc_ce_in_h), .p_in_c(uc_ce_in_c),
        .p_in_c1(uc_ee_in_c1),
        .p_out_w(uc_ce_out_w), .p_out_h(uc_ce_out_h), .p_out_c(uc_ce_out_c),
        .p_groups(p_groups),
        .p_kernel(uc_ce_k), .p_stride(uc_ce_s), .p_pad(uc_ce_p), .p_act(uc_ce_act),
        .p_rq_mult(uc_ce_rqm), .p_rq_shift(uc_ce_rqs),
        .p_aux0(uc_ee_aux0), .p_aux1(uc_ee_aux1),
        // dispatch
        .ce_start(uc_ce_start), .ce_done(ce_done), .ce_error(ce_error),
        .ee_start(uc_ee_start), .ee_done(ee_done), .ee_error(ee_error),
        .ee_op(uc_ee_op),
        .de_start(uc_de_start), .de_done(de_done), .de_error(de_error),
        .de_flush(uc_de_flush), .de_num_boxes(de_nbox),
        .gm_start(gm_start), .gm_done(gm_done), .gm_error(gm_error),
        .num_boxes(uc_boxes)
    );

    // =========================================================================
    // Engine parameter bundle: whichever control path owns YOLO mode drives it
    // =========================================================================
    assign seq_busy  = mode_ucode ? uc_busy  : sq_busy;
    assign seq_done  = mode_ucode ? uc_done  : sq_done;
    assign seq_error = mode_ucode ? uc_error : sq_error;
    assign seq_fsm   = mode_ucode ? uc_fsm   : sq_fsm;
    assign seq_boxes = mode_ucode ? uc_boxes : sq_boxes;

    // REG_LAYER_IDX means what its name says on the sequencer path: which of
    // the 181 descriptors is executing. It used to be hardwired to the
    // microcode PC regardless of mode, so a host polling for progress read a
    // program counter for a program that was not running.
    assign seq_layer = mode_ucode ? uc_pc : sq_layer;

    assign ce_start = mode_ucode ? uc_ce_start : sq_ce_start;
    assign ce_src   = mode_ucode ? uc_ce_src   : sq_ce_src;
    assign ce_dst   = mode_ucode ? uc_ce_dst   : sq_ce_dst;
    assign ce_wgt   = mode_ucode ? uc_ce_wgt   : sq_ce_wgt;
    assign ce_bias  = mode_ucode ? uc_ce_bias  : sq_ce_bias;
    assign ce_in_w  = mode_ucode ? uc_ce_in_w  : sq_ce_in_w;
    assign ce_in_h  = mode_ucode ? uc_ce_in_h  : sq_ce_in_h;
    assign ce_in_c  = mode_ucode ? uc_ce_in_c  : sq_ce_in_c;
    assign ce_out_w = mode_ucode ? uc_ce_out_w : sq_ce_out_w;
    assign ce_out_h = mode_ucode ? uc_ce_out_h : sq_ce_out_h;
    assign ce_out_c = mode_ucode ? uc_ce_out_c : sq_ce_out_c;
    assign ce_k     = mode_ucode ? uc_ce_k     : sq_ce_k;
    assign ce_s     = mode_ucode ? uc_ce_s     : sq_ce_s;
    assign ce_p     = mode_ucode ? uc_ce_p     : sq_ce_p;
    assign ce_act   = mode_ucode ? uc_ce_act   : sq_ce_act;
    assign ce_rqm   = mode_ucode ? uc_ce_rqm   : sq_ce_rqm;
    assign ce_rqs   = mode_ucode ? uc_ce_rqs   : sq_ce_rqs;
    // The microcode ISA has no field for it, so that path leaves SiLU
    // unscaled; it is the experimental path and carries no YOLO26n program.
    assign ce_ascale = mode_ucode ? 16'h0 : sq_ce_ascale;

    // Depthwise: the microcode path derives it from the parameter block groups
    // field (groups == out_c is one group per output channel), while the
    // sequencer decodes LAYER_F_DEPTHWISE from the descriptor directly.
    //
    // The microcode form was briefly tied to 0, which would have made every
    // depthwise conv reduce over k*k*in_c instead of k*k -- wrong numbers, no
    // error flag.
    assign ce_dw    = mode_ucode ? ((p_groups != 16'd0) &&
                                    (p_groups == ce_out_c))
                                 : sq_ce_dw;

    // The microcode path shares one geometry across all three engines (it has
    // no per-engine SET_* opcodes, which keeps the ISA small). The sequencer
    // carries a full parameter set per descriptor, so it drives each engine
    // independently.
    assign ee_start = mode_ucode ? uc_ee_start : sq_ee_start;
    assign ee_op    = mode_ucode ? uc_ee_op    : sq_ee_op;
    assign ee_src0  = mode_ucode ? uc_ce_src   : sq_ee_src0;
    assign ee_src1  = mode_ucode ? uc_ee_src1  : sq_ee_src1;
    assign ee_dst   = mode_ucode ? uc_ce_dst   : sq_ee_dst;
    assign ee_in_w  = mode_ucode ? uc_ce_in_w  : sq_ee_in_w;
    assign ee_in_h  = mode_ucode ? uc_ce_in_h  : sq_ee_in_h;
    assign ee_in_c  = mode_ucode ? uc_ce_in_c  : sq_ee_in_c;
    assign ee_in_c1 = mode_ucode ? uc_ee_in_c1 : sq_ee_in_c1;
    assign ee_out_w = mode_ucode ? uc_ce_out_w : sq_ee_out_w;
    assign ee_out_h = mode_ucode ? uc_ce_out_h : sq_ee_out_h;
    assign ee_out_c = mode_ucode ? uc_ce_out_c : sq_ee_out_c;
    assign ee_aux0  = mode_ucode ? uc_ee_aux0  : sq_ee_aux0;
    assign ee_aux1  = mode_ucode ? uc_ee_aux1  : sq_ee_aux1;

    assign de_start = mode_ucode ? uc_de_start : sq_de_start;
    assign de_flush = mode_ucode ? uc_de_flush : sq_de_flush;
    assign de_src   = mode_ucode ? uc_ce_src   : sq_de_src;
    assign de_dst   = mode_ucode ? uc_ce_dst   : sq_de_dst;
    assign de_in_w  = mode_ucode ? uc_ce_in_w  : sq_de_in_w;
    assign de_in_h  = mode_ucode ? uc_ce_in_h  : sq_de_in_h;
    assign de_in_c  = mode_ucode ? uc_ce_in_c  : sq_de_in_c;
    assign de_level_stride = mode_ucode ? uc_ee_aux0 : sq_de_level_stride;
    assign de_rqm   = mode_ucode ? uc_ce_rqm  : sq_de_rqm;
    assign de_rqs   = mode_ucode ? uc_ce_rqs  : sq_de_rqs;

    // UOP_GEMM reuses the legacy single-tile sequencer, so the microcode
    // completion handshake is that sequencer done/error.
    assign gm_done  = gemm_done;
    assign gm_error = gemm_error;

    // Arbiter slot 0 belongs to the sequencer descriptor fetch. It carries
    // whole 8-byte beats, so every lane is live.
    assign a0_wr_strb = 8'hFF;

    // =========================================================================
    // Conv engine (slot 1, YOLO mode)
    // =========================================================================
    yolo_conv_engine #(
        .ARRAY_SIZE(ARRAY_SIZE), .DATA_WIDTH(DATA_WIDTH), .ACC_WIDTH(ACC_WIDTH)
    ) u_conv (
        .clk(clk), .rst_n(rst_n),
        .start(ce_start),
        .src_addr(ce_src), .dst_addr(ce_dst), .wgt_addr(ce_wgt),
        .bias_addr(ce_bias),
        .in_w(ce_in_w), .in_h(ce_in_h), .in_c(ce_in_c),
        .out_w(ce_out_w), .out_h(ce_out_h), .out_c(ce_out_c),
        .kernel(ce_k), .stride(ce_s), .pad(ce_p), .act_type(ce_act),
        .rq_mult(ce_rqm), .rq_shift(ce_rqs), .depthwise(ce_dw),
        .act_scale(ce_ascale),
        .busy(ce_busy), .done(ce_done), .error(ce_error), .fsm_state(),
        .rd_start(cv_rd_start), .rd_addr(cv_rd_addr), .rd_len(cv_rd_len),
        .rd_data(a1_rd_data), .rd_data_valid(a1_rd_data_valid),
        .rd_done(a1_rd_done), .rd_error(a1_rd_error),
        .wr_start(cv_wr_start), .wr_addr(cv_wr_addr), .wr_len(cv_wr_len),
        .wr_data(cv_wr_data), .wr_strb(cv_wr_strb), .wr_data_ready(a1_wr_data_ready),
        .wr_done(a1_wr_done), .wr_error(a1_wr_error),
        .input_data(cv_input_data),
        .loading_weights(loading_weights), .streaming_acts(streaming_acts),
        .sys_busy(sys_busy), .sys_done(sys_done), .output_data(output_data),
        .s_awvalid(cv_awvalid), .s_awaddr(cv_awaddr),
        .s_wvalid(cv_wvalid), .s_wdata(cv_wdata), .s_wstrb(cv_wstrb),
        .s_awready(i_s_awready), .s_wready(i_s_wready),
        .s_bready(cv_bready), .s_bvalid(i_s_bvalid), .s_bresp(i_s_bresp)
    );

    // =========================================================================
    // Elementwise engine (slot 2)
    // =========================================================================
    yolo_elem_engine #(.DATA_WIDTH(DATA_WIDTH)) u_elem (
        .clk(clk), .rst_n(rst_n),
        .start(ee_start), .op(ee_op),
        .src0(ee_src0), .src1(ee_src1), .dst(ee_dst),
        .in_w(ee_in_w), .in_h(ee_in_h), .in_c(ee_in_c), .in_c1(ee_in_c1),
        .out_w(ee_out_w), .out_h(ee_out_h), .out_c(ee_out_c),
        .aux0(ee_aux0), .aux1(ee_aux1),
        .busy(ee_busy), .done(ee_done), .error(ee_error), .fsm_state(),
        .rd_start(a2_rd_start), .rd_addr(a2_rd_addr), .rd_len(a2_rd_len),
        .rd_data(a2_rd_data), .rd_data_valid(a2_rd_data_valid),
        .rd_done(a2_rd_done), .rd_error(a2_rd_error),
        .wr_start(a2_wr_start), .wr_addr(a2_wr_addr), .wr_len(a2_wr_len),
        .wr_data(a2_wr_data), .wr_strb(a2_wr_strb), .wr_data_ready(a2_wr_data_ready),
        .wr_done(a2_wr_done), .wr_error(a2_wr_error)
    );

    // =========================================================================
    // Detect engine (slot 3)
    // =========================================================================
    yolo_detect_engine #(
        .NUM_CLASSES(80), .MAX_BOXES(300), .BOX_BYTES(16)
    ) u_detect (
        .clk(clk), .rst_n(rst_n),
        .start(de_start), .src(de_src), .dst(de_dst),
        .in_w(de_in_w), .in_h(de_in_h), .in_c(de_in_c),
        .level_stride(de_level_stride),
        .rq_mult(de_rqm), .rq_shift(de_rqs), .flush(de_flush),
        .busy(de_busy), .done(de_done), .error(de_error), .fsm_state(),
        .num_boxes(de_nbox), .conf_thresh(conf_thresh),
        .rd_start(a3_rd_start), .rd_addr(a3_rd_addr), .rd_len(a3_rd_len),
        .rd_data(a3_rd_data), .rd_data_valid(a3_rd_data_valid),
        .rd_done(a3_rd_done), .rd_error(a3_rd_error),
        .wr_start(a3_wr_start), .wr_addr(a3_wr_addr), .wr_len(a3_wr_len),
        .wr_data(a3_wr_data), .wr_strb(a3_wr_strb), .wr_data_ready(a3_wr_data_ready),
        .wr_done(a3_wr_done), .wr_error(a3_wr_error)
    );

    // =========================================================================
    // Legacy single-tile GEMM path (CTRL bit1 = 0) — kept for bring-up
    // =========================================================================
    accel_dma_seq #(
        .ARRAY_SIZE(ARRAY_SIZE), .DATA_WIDTH(DATA_WIDTH), .K(96)
    ) u_legacy (
        .clk(clk), .rst_n(rst_n),
        .start_pulse(start_gemm | gm_start), .src_addr(src_addr), .dst_addr(dst_addr),
        .weight_addr(weight_addr),
        .busy(gemm_busy), .done(gemm_done), .error(gemm_error),
        .fsm_state(gemm_fsm),
        .rd_start(lg_rd_start), .rd_addr(lg_rd_addr), .rd_len(lg_rd_len),
        .rd_data(a1_rd_data), .rd_data_valid(a1_rd_data_valid),
        .rd_done(a1_rd_done), .rd_error(a1_rd_error),
        .wr_start(lg_wr_start), .wr_addr(lg_wr_addr), .wr_len(lg_wr_len),
        .wr_data(lg_wr_data), .wr_data_ready(a1_wr_data_ready),
        .wr_done(a1_wr_done), .wr_error(a1_wr_error),
        .input_data(lg_input_data),
        .loading_weights(loading_weights), .streaming_acts(streaming_acts),
        .sys_busy(sys_busy), .sys_done(sys_done), .output_data(output_data),
        .s_awvalid(lg_awvalid), .s_awaddr(lg_awaddr),
        .s_wvalid(lg_wvalid), .s_wdata(lg_wdata), .s_wstrb(lg_wstrb),
        .s_awready(i_s_awready), .s_wready(i_s_wready),
        .s_bready(lg_bready), .s_bvalid(i_s_bvalid), .s_bresp(i_s_bresp),
        .s_arvalid(), .s_araddr(), .s_arready(1'b0),
        .s_rready(), .s_rvalid(1'b0), .s_rdata(32'h0), .s_rresp(2'b00)
    );

endmodule
