// -----------------------------------------------------------------------------
// GENERATED by qrts/tools/port_rtl.py -- DO NOT EDIT THIS COPY.
//
// Source: DVCon_2026/DVCon_SoC_SRC/ACCELERATOR_IP/axi4_master.sv
//
// Edit the source and re-run the porter:
//     python qrts/tools/port_rtl.py
//
// Xilinx synthesis attributes have been rewritten for Quartus. See the porter
// for what is rewritten and what still needs hand work.
// -----------------------------------------------------------------------------
// =============================================================================
// axi4_master.sv — AXI4 full burst master (DDR-facing DMA engine)
//
// Per axi_interface.md §1: 64-bit addr/data, INCR bursts only, fixed ID=0
// (single master, no outstanding-ID tracking). Independent read/write FSMs —
// one transaction in flight at a time on each side, driven by a simple
// internal start/done handshake so a sequencer can issue back-to-back bursts.
//
// Write-data contract: wr_data is forwarded combinationally (no internal
// latch) — the caller must present the CURRENT beat's data whenever
// wr_data_ready is high, and update to the NEXT beat's data by the following
// cycle (standard "consumed, advance" producer/consumer pattern).
// =============================================================================
`timescale 1ns/1ps

module axi4_master #(
    parameter integer ADDR_WIDTH = 64,
    parameter integer DATA_WIDTH = 64,
    parameter integer ID_WIDTH   = 12
)(
    input  wire                        clk,
    input  wire                        rst_n,

    // ---------------- AXI4 master: AR/R ----------------
    output reg  [ID_WIDTH-1:0]         m_arid,
    output reg  [ADDR_WIDTH-1:0]       m_araddr,
    output reg  [7:0]                  m_arlen,
    output wire [2:0]                  m_arsize,
    output wire [1:0]                  m_arburst,
    output wire [2:0]                  m_arprot,
    output reg                         m_arvalid,
    input  wire                        m_arready,

    input  wire [ID_WIDTH-1:0]         m_rid,
    input  wire [DATA_WIDTH-1:0]       m_rdata,
    input  wire [1:0]                  m_rresp,
    input  wire                        m_rlast,
    input  wire                        m_rvalid,
    output reg                         m_rready,

    // ---------------- AXI4 master: AW/W/B ----------------
    output reg  [ID_WIDTH-1:0]         m_awid,
    output reg  [ADDR_WIDTH-1:0]       m_awaddr,
    output reg  [7:0]                  m_awlen,
    output wire [2:0]                  m_awsize,
    output wire [1:0]                  m_awburst,
    output wire [2:0]                  m_awprot,
    output reg                         m_awvalid,
    input  wire                        m_awready,

    output wire [DATA_WIDTH-1:0]       m_wdata,
    output wire [DATA_WIDTH/8-1:0]     m_wstrb,
    output wire                        m_wlast,
    output reg                         m_wvalid,
    input  wire                        m_wready,

    output reg                         m_bready,
    input  wire                        m_bvalid,
    input  wire [ID_WIDTH-1:0]         m_bid,
    input  wire [1:0]                  m_bresp,

    // ---------------- internal handshake: READ ----------------
    input  wire                        rd_start,
    input  wire [ADDR_WIDTH-1:0]       rd_addr,
    input  wire [7:0]                  rd_len,      // # beats (1-256)
    output reg  [DATA_WIDTH-1:0]       rd_data,      // valid one cycle after R handshake
    output reg                         rd_data_valid,
    output reg                         rd_done,
    output reg                         rd_error,

    // ---------------- internal handshake: WRITE ----------------
    input  wire                        wr_start,
    input  wire [ADDR_WIDTH-1:0]       wr_addr,
    input  wire [7:0]                  wr_len,       // # beats
    input  wire [DATA_WIDTH-1:0]       wr_data,       // current beat, forwarded combinationally
    // Byte enables for the current beat, forwarded combinationally alongside
    // wr_data. Callers that write whole beats tie this to all-ones; the conv
    // and detect engines write a SINGLE BYTE per beat and must drive the one
    // lane they mean. It used to be hardwired to all-ones here, which made
    // every byte-granular store write its 7 neighbours as zero -- the stores
    // are sequential, so each one erased the bytes the next ones had just
    // written and the output map came out almost entirely zero.
    input  wire [DATA_WIDTH/8-1:0]     wr_strb,
    output wire                        wr_data_ready, // pulses when a beat is accepted -> advance to next
    output reg                         wr_done,
    output reg                         wr_error
);

    assign m_arsize  = 3'b011;   // 8B/beat
    assign m_arburst = 2'b01;    // INCR
    assign m_arprot  = 3'b000;
    assign m_awsize  = 3'b011;
    assign m_awburst = 2'b01;
    assign m_awprot  = 3'b000;

    // =========================================================================
    // Read FSM
    // =========================================================================
    localparam [1:0] RD_IDLE=2'd0, RD_ADDR=2'd1, RD_DATA=2'd2, RD_DONE=2'd3;
    reg [1:0] rd_state;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            rd_state      <= RD_IDLE;
            m_arvalid     <= 1'b0;
            m_arid        <= {ID_WIDTH{1'b0}};
            m_araddr      <= {ADDR_WIDTH{1'b0}};
            m_arlen       <= 8'd0;
            m_rready      <= 1'b0;
            rd_data       <= {DATA_WIDTH{1'b0}};
            rd_data_valid <= 1'b0;
            rd_done       <= 1'b0;
            rd_error      <= 1'b0;
        end else begin
            rd_done       <= 1'b0;
            rd_data_valid <= 1'b0;
            case (rd_state)
                RD_IDLE: begin
                    m_arvalid <= 1'b0;
                    m_rready  <= 1'b0;
                    if (rd_start) begin
                        m_arid    <= {ID_WIDTH{1'b0}};
                        m_araddr  <= rd_addr;
                        m_arlen   <= rd_len - 8'd1;
                        m_arvalid <= 1'b1;
                        rd_error  <= 1'b0;
                        rd_state  <= RD_ADDR;
                    end
                end
                RD_ADDR: begin
                    if (m_arvalid && m_arready) begin
                        m_arvalid <= 1'b0;
                        m_rready  <= 1'b1;
                        rd_state  <= RD_DATA;
                    end
                end
                RD_DATA: begin
                    if (m_rvalid && m_rready) begin
                        rd_data       <= m_rdata;
                        rd_data_valid <= 1'b1;
                        if (m_rresp != 2'b00) rd_error <= 1'b1;
                        if (m_rlast) begin
                            m_rready <= 1'b0;
                            rd_state <= RD_DONE;
                        end
                    end
                end
                RD_DONE: begin
                    rd_done  <= 1'b1;
                    rd_state <= RD_IDLE;
                end
                default: rd_state <= RD_IDLE;
            endcase
        end
    end

    // =========================================================================
    // Write FSM  — m_wdata/m_wstrb/m_wlast/wr_data_ready are combinational
    // =========================================================================
    localparam [2:0] WR_IDLE=3'd0, WR_ADDR=3'd1, WR_DATA=3'd2, WR_RESP=3'd3, WR_DONE=3'd4;
    reg [2:0] wr_state;
    reg [7:0] wr_beat_cnt;
    reg [7:0] wr_len_lat;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            wr_state    <= WR_IDLE;
            m_awvalid   <= 1'b0;
            m_awid      <= {ID_WIDTH{1'b0}};
            m_awaddr    <= {ADDR_WIDTH{1'b0}};
            m_awlen     <= 8'd0;
            m_wvalid    <= 1'b0;
            m_bready    <= 1'b0;
            wr_beat_cnt <= 8'd0;
            wr_len_lat  <= 8'd0;
            wr_done     <= 1'b0;
            wr_error    <= 1'b0;
        end else begin
            wr_done <= 1'b0;
            case (wr_state)
                WR_IDLE: begin
                    m_awvalid <= 1'b0;
                    m_wvalid  <= 1'b0;
                    if (wr_start) begin
                        m_awid      <= {ID_WIDTH{1'b0}};
                        m_awaddr    <= wr_addr;
                        m_awlen     <= wr_len - 8'd1;
                        wr_len_lat  <= wr_len;
                        m_awvalid   <= 1'b1;
                        wr_beat_cnt <= 8'd0;
                        wr_error    <= 1'b0;
                        wr_state    <= WR_ADDR;
                    end
                end
                WR_ADDR: begin
                    if (m_awvalid && m_awready) begin
                        m_awvalid <= 1'b0;
                        m_wvalid  <= 1'b1;
                        wr_state  <= WR_DATA;
                    end
                end
                WR_DATA: begin
                    if (m_wvalid && m_wready) begin
                        if (wr_beat_cnt == wr_len_lat - 8'd1) begin
                            m_wvalid <= 1'b0;
                            m_bready <= 1'b1;
                            wr_state <= WR_RESP;
                        end else begin
                            wr_beat_cnt <= wr_beat_cnt + 8'd1;
                        end
                    end
                end
                WR_RESP: begin
                    if (m_bvalid && m_bready) begin
                        m_bready <= 1'b0;
                        if (m_bresp != 2'b00) wr_error <= 1'b1;
                        wr_state <= WR_DONE;
                    end
                end
                WR_DONE: begin
                    wr_done  <= 1'b1;
                    wr_state <= WR_IDLE;
                end
                default: wr_state <= WR_IDLE;
            endcase
        end
    end

    assign m_wdata        = wr_data;
    assign m_wstrb         = wr_strb;
    assign m_wlast         = (wr_state == WR_DATA) && (wr_beat_cnt == wr_len_lat - 8'd1);
    assign wr_data_ready   = (wr_state == WR_DATA) && m_wvalid && m_wready;

endmodule
