// -----------------------------------------------------------------------------
// GENERATED by qrts/tools/port_rtl.py -- DO NOT EDIT THIS COPY.
//
// Source: DVCon_2026/DVCon_SoC_SRC/ACCELERATOR_IP/dvc_generic_mux.sv
//
// Edit the source and re-run the porter:
//     python qrts/tools/port_rtl.py
//
// Xilinx synthesis attributes have been rewritten for Quartus. See the porter
// for what is rewritten and what still needs hand work.
// -----------------------------------------------------------------------------
// Scalable N-to-1 Multiplexer
//
// Named dvc_generic_mux, not generic_mux: Quartus has a built-in primitive of
// the latter name, and an instance of ours resolves to THAT instead --
//   Error (12004): Port "in" does not exist in primitive "generic_mux"
// which reads as a port-name problem and is really a name collision. Renaming
// the module is the fix; renaming the ports would not help.
`timescale 1ns/1ps

module dvc_generic_mux #(
    parameter integer WIDTH = 32,
    parameter integer NUM_INPUTS = 4
)(
    input  wire [(WIDTH * NUM_INPUTS)-1:0] in,
    input  wire [$clog2(NUM_INPUTS)-1:0]   sel,
    output wire [WIDTH-1:0]                out
);
    assign out = in[sel * WIDTH +: WIDTH];
endmodule
