// -----------------------------------------------------------------------------
// GENERATED by qrts/tools/port_rtl.py -- DO NOT EDIT THIS COPY.
//
// Source: DVCFinal/rtl/silu_unit.sv
//
// Edit the source and re-run the porter:
//     python qrts/tools/port_rtl.py
//
// Xilinx synthesis attributes have been rewritten for Quartus. See the porter
// for what is rewritten and what still needs hand work.
// -----------------------------------------------------------------------------
// =============================================================================
// silu_unit.sv — SiLU activation for INT8 codes with a per-layer scale
//
// SiLU(x) = x * sigmoid(x), applied to the requantized INT8 output of a conv.
//
// Why this replaces silu_lut.sv
// -----------------------------
// silu_lut.sv bakes ONE activation scale into the ROM at elaboration
// (`parameter real SCALE`), computed with $exp/$rtoi in an initial block. Two
// problems, either of which is fatal here:
//
//   * Every layer has its own activation scale. The exporter picks
//     out_scale = amax/127 per layer (pick_act_scale), so an INT8 code means a
//     different real value in every layer. A single-scale ROM is only correct
//     for whichever layer happened to match the parameter.
//   * Quartus does not fold $exp/$rtoi at elaboration the way Vivado does, so
//     that ROM would come up undefined on Cyclone IV.
//
// The fix for both: tabulate sigmoid ONCE in a fixed, scale-free domain and
// apply the layer's scale arithmetically around it.
//
// How it works
// ------------
// The INT8 code c represents the real value  v = c / s, where s is the layer's
// codes-per-unit (s = 127/amax, the reciprocal of the exporter's out_scale).
// The descriptor carries s as Q8.8 in the spare bits of the requant word.
//
//     SiLU(v) = v * sigmoid(v)
//     result code = SiLU(v) * s = c * sigmoid(c / s)
//
// so the only thing that needs a table is sigmoid, evaluated at v = c/s. The
// table is indexed by v in a fixed Q4.4 domain covering [-8, +8), which is
// where sigmoid does all its work: below -8 it is < 0.00034 and above +8 it is
// > 0.99966, both of which round to the endpoints at INT8 precision. Outside
// the table the unit saturates to 0 and to c, which is exactly the limit.
//
// The ROM holds sigmoid in Q0.8 (0..255 for 0.0..~1.0), 256 entries, built by
// an offline generator into a .mif/.hex rather than by real math in an initial
// block -- see tools/gen_silu_mif.py. That is what makes it portable.
// =============================================================================
`timescale 1ns/1ps

module silu_unit #(
    // Q0.8 sigmoid table, 256 entries over v in [-8, +8) at 1/16 steps.
    parameter        SIG_MIF = "silu_sigmoid.mem"
)(
    input  wire                clk,
    input  wire                rst_n,

    input  wire signed  [7:0]  x,        // requantized INT8 code
    // Codes per unit, Q8.8. 0 disables the unit (pass-through), which keeps a
    // descriptor that forgot to set it from silently producing zeros.
    input  wire        [15:0]  scale_q88,
    input  wire                valid_in,

    output reg  signed  [7:0]  y,
    output reg                 valid_out
);

    // (* ramstyle *) is rewritten from the Xilinx spelling by
    // qrts/tools/port_rtl.py; the Vivado build reads (* rom_style *).
    (* romstyle = "M9K" *) reg [7:0] sigmoid_rom [0:255];

    initial begin
        // Loaded from a generated file, NOT computed here: Quartus will not
        // evaluate $exp/$rtoi at elaboration, so a self-initialising ROM comes
        // up undefined on Cyclone IV. tools/gen_silu_mif.py writes this.
        $readmemh(SIG_MIF, sigmoid_rom);
    end

    // ---- stage 1: v = x / s, in the table's Q4.4 domain ---------------------
    //
    // The table index counts sixteenths of a unit, offset so index 0 is
    // v = -8.0:
    //
    //     sixteenths = round(v * 16) = round(x * 16 / s)
    //     idx        = sixteenths + 128
    //
    // With s carried as Q8.8 (scale_q88 = s * 256):
    //
    //     sixteenths = x * 16 / (scale_q88 / 256) = x * 4096 / scale_q88
    //
    // The divide is by a per-LAYER value, not a per-element one, so it is
    // hoisted: recip = (1 << 20) / scale_q88 is computed once when the scale
    // changes, and the per-element path becomes
    //
    //     sixteenths = (x * recip) >> 8
    //
    // because (1 << 20) / 4096 == 1 << 8.
    reg [15:0] scale_lat;
    reg [19:0] recip;
    reg        recip_valid;

    // Restoring division, one bit per cycle, most significant first.
    //
    // Kept explicit rather than written as `(1<<20)/scale_q88`: a variable
    // divide left to the tool lands a full combinational divider in the
    // design, and this is the same class of construct that put a 148-level
    // path in the conv engine. It runs ONCE per layer -- while the conv engine
    // is loading a weight tile -- so 21 cycles cost nothing.
    //
    // Dividend is 1 << 20 exactly. Iteration i (from 20 down to 0) brings down
    // bit i of the dividend, which is 1 only for i == 20.
    reg [5:0]  div_i;
    reg [36:0] div_rem;
    reg [19:0] div_quot;
    reg        div_run;

    wire [36:0] div_shifted = {div_rem[35:0], (div_i == 6'd20) ? 1'b1 : 1'b0};
    wire        div_fits    = (div_shifted >= {21'h0, scale_lat});

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            scale_lat   <= 16'h0;
            recip       <= 20'h0;
            recip_valid <= 1'b0;
            div_i       <= 6'd0;
            div_rem     <= 37'h0;
            div_quot    <= 20'h0;
            div_run     <= 1'b0;
        end else if (scale_q88 != scale_lat) begin
            scale_lat   <= scale_q88;
            recip_valid <= 1'b0;
            div_quot    <= 20'h0;
            div_rem     <= 37'h0;
            div_i       <= 6'd20;
            div_run     <= (scale_q88 != 16'h0);
        end else if (div_run) begin
            div_rem  <= div_fits ? (div_shifted - {21'h0, scale_lat})
                                 : div_shifted;
            div_quot <= {div_quot[18:0], div_fits};
            if (div_i == 6'd0) begin
                div_run     <= 1'b0;
                recip       <= {div_quot[18:0], div_fits};
                recip_valid <= 1'b1;
            end else begin
                div_i <= div_i - 6'd1;
            end
        end
    end

    // recip is unsigned; widen it so the product keeps x's sign, then shift
    // ARITHMETICALLY. A bit-select like scaled[28:8] truncates toward minus
    // infinity for negative values in a way that does not match >>> and put
    // the whole negative half of the sweep one code out.
    wire signed [28:0] scaled     = $signed(x) * $signed({1'b0, recip});
    wire signed [28:0] sixteenths = scaled >>> 8;    // v * 16, signed

    // ---- stage 2: table lookup + saturation ---------------------------------
    reg signed [7:0]  x_d1;
    reg               sat_lo_d1, sat_hi_d1, valid_d1;
    reg [7:0]         rom_idx;

    // The table spans v in [-8, +8): sixteenths in [-128, +127].
    wire below = (sixteenths < -29'sd128);
    wire above = (sixteenths >  29'sd127);
    wire [7:0] idx_calc = sixteenths[7:0] + 8'd128;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            x_d1 <= 8'sd0; sat_lo_d1 <= 1'b0; sat_hi_d1 <= 1'b0;
            valid_d1 <= 1'b0; rom_idx <= 8'd0;
        end else begin
            x_d1      <= x;
            sat_lo_d1 <= below;
            sat_hi_d1 <= above;
            rom_idx   <= idx_calc;
            // A layer whose scale has not resolved yet must not emit a result.
            valid_d1  <= valid_in && recip_valid && (scale_q88 != 16'h0);
        end
    end

    reg [7:0] sig_q08;
    always @(posedge clk) sig_q08 <= sigmoid_rom[rom_idx];

    reg signed [7:0] x_d2;
    reg              sat_lo_d2, sat_hi_d2, valid_d2;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            x_d2 <= 8'sd0; sat_lo_d2 <= 1'b0; sat_hi_d2 <= 1'b0; valid_d2 <= 1'b0;
        end else begin
            x_d2      <= x_d1;
            sat_lo_d2 <= sat_lo_d1;
            sat_hi_d2 <= sat_hi_d1;
            valid_d2  <= valid_d1;
        end
    end

    // ---- stage 3: y = x * sigmoid(v), rounded and clamped -------------------
    //
    // sigmoid is Q0.8, so the product is Q8.8 of the code; round to nearest by
    // adding half an LSB before the shift. Below the table sigmoid -> 0 (y=0);
    // above it sigmoid -> 1 (y=x). Those are the true limits, not a fallback.
    wire signed [16:0] prod  = $signed(x_d2) * $signed({1'b0, sig_q08});
    wire signed [16:0] round = prod + 17'sd128;
    wire signed [8:0]  shifted = round[16:8];

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            y <= 8'sd0;
            valid_out <= 1'b0;
        end else begin
            valid_out <= valid_d2;
            if (sat_lo_d2)      y <= 8'sd0;
            else if (sat_hi_d2) y <= x_d2;
            else if (shifted >  9'sd127)  y <=  8'sd127;
            else if (shifted < -9'sd128)  y <= -8'sd128;
            else                          y <= shifted[7:0];
        end
    end

endmodule
