// -----------------------------------------------------------------------------
// GENERATED by qrts/tools/port_rtl.py -- DO NOT EDIT THIS COPY.
//
// Source: DVCFinal/rtl/ucode_pkg.svh
//
// Edit the source and re-run the porter:
//     python qrts/tools/port_rtl.py
//
// Xilinx synthesis attributes have been rewritten for Quartus. See the porter
// for what is rewritten and what still needs hand work.
// -----------------------------------------------------------------------------
// =============================================================================
// ucode_pkg.svh — microcode ISA for the reprogrammable sequencer
//
// The CPU loads a program into an on-chip instruction RAM over AXI, then hits
// START. The sequencer fetches, decodes and executes it. Changing what the
// accelerator DOES therefore costs a memory write, not a 90-minute resynthesis.
//
// One 64-bit word per instruction, so a fetch is exactly one beat on the
// 64-bit AXI/BRAM path and the PC is a plain word index. Fixed width also
// means no multi-word decode state, which keeps the fetch stage single-cycle.
//
// ---------------------------------------------------------------------------
// Word layout (bit 63 .. 0)
// ---------------------------------------------------------------------------
//   [63:58]  opcode      UOP_*
//   [57:56]  flags       {irq, reserved}
//   [55:52]  dst_sel     which engine/register bank the result targets
//   [51:32]  imm_hi      20-bit immediate (loop counts, addresses>>6, ...)
//   [31:0]   imm_lo      32-bit immediate (full addresses, dimensions)
//
// Register-form operands (ALU ops) reuse the immediate fields:
//   [51:48]  ra          source register A  (R0..R15)
//   [47:44]  rb          source register B
//   [43:40]  rd          destination register
//
// The 16 general registers are 32-bit scratch used for loop counters and
// computed addresses, so a program can walk a layer table without the CPU.
// =============================================================================
`ifndef UCODE_PKG_SVH
`define UCODE_PKG_SVH

localparam integer UCODE_WORD_BITS = 64;
localparam integer UCODE_DEPTH     = 1024;              // 8 KB of BRAM
localparam integer UCODE_AW        = $clog2(UCODE_DEPTH);
localparam integer UCODE_NREG      = 16;

// ---- opcodes ---------------------------------------------------------------
// Deliberately small and orthogonal. Everything the existing engines can do is
// reachable, and control flow is enough to express the layer walk.
localparam [5:0]
    UOP_NOP        = 6'd0,
    UOP_HALT       = 6'd1,   // stop, raise done
    // --- register / immediate ---
    UOP_LDI        = 6'd2,   // rd <- imm_lo
    UOP_MOV        = 6'd3,   // rd <- ra
    UOP_ADD        = 6'd4,   // rd <- ra + rb
    UOP_SUB        = 6'd5,   // rd <- ra - rb
    UOP_SHL        = 6'd6,   // rd <- ra << imm_lo
    UOP_SHR        = 6'd7,   // rd <- ra >> imm_lo
    UOP_ADDI       = 6'd8,   // rd <- ra + imm_lo
    // --- control flow ---
    UOP_JMP        = 6'd9,   // pc <- imm_lo
    UOP_JNZ        = 6'd10,  // if (ra != 0) pc <- imm_lo
    UOP_JZ         = 6'd11,  // if (ra == 0) pc <- imm_lo
    UOP_LOOP       = 6'd12,  // rd <- rd-1; if (rd != 0) pc <- imm_lo
    // --- configuration writes into the engine parameter block ---
    UOP_SET_SRC    = 6'd16,  // engine src  <- ra or imm_lo
    UOP_SET_DST    = 6'd17,
    UOP_SET_WGT    = 6'd18,
    UOP_SET_BIAS   = 6'd19,
    UOP_SET_DIM    = 6'd20,  // {in_h,in_w}   from imm_lo
    UOP_SET_CHAN   = 6'd21,  // {in_c1,in_c}  from imm_lo
    UOP_SET_ODIM   = 6'd22,  // {out_h,out_w}
    UOP_SET_OCHAN  = 6'd23,  // {groups,out_c}
    UOP_SET_KSPA   = 6'd24,  // kernel/stride/pad/act packed
    UOP_SET_RQ     = 6'd25,  // {rq_mult, rq_shift}
    UOP_SET_AUX    = 6'd26,  // aux0 (imm_lo), aux1 (imm_hi)
    // --- engine dispatch (blocking: waits for that engine's done) ---
    UOP_CONV       = 6'd32,  // run the conv engine with the current params
    UOP_ELEM       = 6'd33,  // run the elementwise engine, op in imm_hi[5:0]
    UOP_DETECT     = 6'd34,  // run the detect engine
    UOP_TOPK       = 6'd35,  // detect engine in flush mode
    UOP_GEMM       = 6'd36,  // legacy single-tile GEMM (bring-up / self-test)
    // --- raw memory move, for staging and tests ---
    UOP_MEMCPY     = 6'd40;  // ra bytes from rb -> rd

// ---- flag bits -------------------------------------------------------------
localparam integer UF_IRQ = 57;   // raise the done pulse when this retires

// ---- field extraction ------------------------------------------------------
// Kept as macros in one place so the decoder and the assembler cannot drift.
`define UC_OP(w)      (w[63:58])
`define UC_FLAGS(w)   (w[57:56])
`define UC_DSTSEL(w)  (w[55:52])
`define UC_IMMHI(w)   (w[51:32])
`define UC_IMMLO(w)   (w[31:0])
`define UC_RA(w)      (w[51:48])
`define UC_RB(w)      (w[47:44])
`define UC_RD(w)      (w[43:40])

`endif
