// -----------------------------------------------------------------------------
// GENERATED by qrts/tools/port_rtl.py -- DO NOT EDIT THIS COPY.
//
// Source: DVCFinal/rtl/ucode_engine.sv
//
// Edit the source and re-run the porter:
//     python qrts/tools/port_rtl.py
//
// Xilinx synthesis attributes have been rewritten for Quartus. See the porter
// for what is rewritten and what still needs hand work.
// -----------------------------------------------------------------------------
// =============================================================================
// ucode_engine.sv — reprogrammable sequencer
//
// Replaces the hardwired descriptor walk with a fetch/decode/execute loop over
// an on-chip instruction RAM the CPU can rewrite at runtime. The accelerator's
// behaviour becomes a software property.
//
//   CPU: write program into UCODE RAM (AXI, 0x1000..0x2FFF) -> START
//   HW : PC=0; fetch -> decode -> execute -> ... -> HALT -> done
//
// ---------------------------------------------------------------------------
// Timing notes (this is the part that bites on a 24x24 build at 50 MHz)
// ---------------------------------------------------------------------------
// 1. The instruction RAM is a synchronous BRAM: address out on cycle N, data
//    valid on N+1. The FSM therefore has a distinct FETCH and DECODE state
//    rather than combinationally decoding ram[pc]. Skipping that costs a full
//    BRAM-output-to-decode-logic path in one cycle and will not close timing.
// 2. Register reads are registered into ra_val/rb_val before the ALU, so the
//    critical path is BRAM -> regfile mux -> adder, not BRAM -> adder -> mux
//    -> writeback in a single cycle.
// 3. Engine dispatch is a handshake (start pulse, wait for done). No engine
//    result feeds combinationally back into the next instruction's decode.
// 4. Every branch target is registered; there is no combinational path from
//    the fetched word to the RAM address input.
// =============================================================================
`timescale 1ns/1ps

`include "ucode_pkg.svh"

module ucode_engine #(
    parameter integer DEPTH = UCODE_DEPTH,
    parameter integer AW    = UCODE_AW
)(
    input  wire        clk,
    input  wire        rst_n,

    // ---- control ----
    input  wire        start_pulse,
    output reg         busy,
    output reg         done,
    output reg         error,
    output reg  [3:0]  fsm_state,
    output reg  [15:0] pc_out,        // observability: where the program is

    // ---- instruction RAM write port (from the CPU register file) ----
    input  wire            ucode_we,
    input  wire [AW-1:0]   ucode_waddr,
    input  wire [63:0]     ucode_wdata,

    // ---- engine parameter block (shared by all engines) ----
    output reg  [31:0] p_src0, p_src1, p_dst, p_wgt, p_bias,
    output reg  [15:0] p_in_w, p_in_h, p_in_c, p_in_c1,
    output reg  [15:0] p_out_w, p_out_h, p_out_c, p_groups,
    output reg  [3:0]  p_kernel, p_stride, p_pad, p_act,
    output reg  [15:0] p_rq_mult,
    output reg  [4:0]  p_rq_shift,
    output reg  [31:0] p_aux0, p_aux1,

    // ---- engine dispatch ----
    output reg         ce_start,   input wire ce_done, input wire ce_error,
    output reg         ee_start,   input wire ee_done, input wire ee_error,
    output reg  [31:0] ee_op,
    output reg         de_start,   input wire de_done, input wire de_error,
    output reg         de_flush,
    input  wire [15:0] de_num_boxes,
    output reg         gm_start,   input wire gm_done, input wire gm_error,

    output reg  [15:0] num_boxes
);

    // =========================================================================
    // Instruction RAM.
    //
    // Simple dual port: CPU writes on port A, the sequencer reads on port B.
    // Deliberately NOT reset -- an async reset in the same always block blocks
    // BRAM inference in Vivado (Stage 3A trap, cost hours on the Basys3 port).
    // =========================================================================
    (* ramstyle = "M9K" *)
    reg [63:0] ucode_ram [0:DEPTH-1];

    reg [63:0] ir;            // fetched instruction (BRAM output, registered)
    reg [AW-1:0] pc, next_pc;

    always @(posedge clk) begin
        if (ucode_we) ucode_ram[ucode_waddr] <= ucode_wdata;
    end

    // Read address is next_pc, and the result is consumed in U_DECODE -- one
    // cycle after U_FETCH latches pc <= next_pc. The BRAM's registered output
    // therefore lines up with the state that decodes it. Addressing this with
    // `pc` instead would present the word a cycle late and decode the previous
    // instruction.
    always @(posedge clk) begin
        ir <= ucode_ram[next_pc];
    end

    // =========================================================================
    // Register file
    // =========================================================================
    reg [31:0] regs [0:UCODE_NREG-1];
    reg [31:0] ra_val, rb_val;

    wire [3:0] ra_idx = `UC_RA(ir);
    wire [3:0] rb_idx = `UC_RB(ir);
    wire [3:0] rd_idx = `UC_RD(ir);
    wire [5:0] opcode = `UC_OP(ir);
    wire [31:0] imm_lo = `UC_IMMLO(ir);
    wire [19:0] imm_hi = `UC_IMMHI(ir);

    // =========================================================================
    // FSM
    // =========================================================================
    localparam [3:0]
        U_IDLE   = 4'd0,
        U_FETCH  = 4'd1,   // address presented, BRAM data next cycle
        U_DECODE = 4'd2,   // ir valid, read regs
        U_EXEC   = 4'd3,   // ALU / config write / issue engine
        U_WAIT   = 4'd4,   // blocking on an engine
        U_DONE   = 4'd5,
        U_ERR    = 4'd6;

    reg [3:0] state;
    reg [2:0] pending;      // which engine we are waiting on
    localparam [2:0] W_NONE=3'd0, W_CONV=3'd1, W_ELEM=3'd2, W_DET=3'd3, W_GEMM=3'd4;

    integer i;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state    <= U_IDLE;
            pc       <= '0;
            next_pc  <= '0;
            busy     <= 1'b0; done <= 1'b0; error <= 1'b0;
            fsm_state<= 4'd0; pc_out <= 16'd0;
            ce_start <= 1'b0; ee_start <= 1'b0; de_start <= 1'b0; gm_start <= 1'b0;
            de_flush <= 1'b0; ee_op <= 32'd0;
            pending  <= W_NONE;
            num_boxes<= 16'd0;
            p_src0<=0; p_src1<=0; p_dst<=0; p_wgt<=0; p_bias<=0;
            p_in_w<=0; p_in_h<=0; p_in_c<=0; p_in_c1<=0;
            p_out_w<=0; p_out_h<=0; p_out_c<=0; p_groups<=1;
            p_kernel<=1; p_stride<=1; p_pad<=0; p_act<=0;
            p_rq_mult<=0; p_rq_shift<=0; p_aux0<=0; p_aux1<=0;
            for (i = 0; i < UCODE_NREG; i = i + 1) regs[i] <= 32'd0;
        end else begin
            ce_start <= 1'b0;
            ee_start <= 1'b0;
            de_start <= 1'b0;
            gm_start <= 1'b0;
            fsm_state<= state;
            pc_out   <= {{(16-AW){1'b0}}, pc};

            case (state)
            // ------------------------------------------------------------
            U_IDLE: begin
                busy <= 1'b0;
                if (start_pulse) begin
                    // next_pc drives the RAM read this cycle, so word 0 lands
                    // in `ir` at the start of U_FETCH; U_FETCH then commits
                    // pc and U_DECODE consumes the word. One extra cycle of
                    // startup latency buys a clean single-owner fetch path.
                    pc      <= '0;
                    next_pc <= '0;
                    busy    <= 1'b1;
                    done    <= 1'b0;
                    error   <= 1'b0;
                    state   <= U_FETCH;
                end
            end

            // The BRAM registers its output, so the word addressed by next_pc
            // is only valid in `ir` one cycle AFTER this state -- i.e. during
            // U_DECODE. Committing pc here and decoding in the next state
            // keeps the address, the fetched word and the decode aligned.
            //
            // Getting this off by one is the classic version of this bug: the
            // engine then decodes the PREVIOUS instruction (or, on the first
            // fetch, an uninitialised word) and silently executes a NOP where
            // the program's first real instruction should be.
            U_FETCH: begin
                // `ir` already holds ucode_ram[next_pc] (the RAM read was
                // issued in the previous cycle), so commit the PC and let
                // U_DECODE read the registers this instruction names.
                pc      <= next_pc;
                ra_val  <= regs[`UC_RA(ir)];
                rb_val  <= regs[`UC_RB(ir)];
                state   <= U_DECODE;
            end

            // ra_val/rb_val were captured in U_FETCH; compute the fall-through
            // target from the PC this instruction actually lives at. Keeping
            // this as its own state means the BRAM output never feeds the ALU
            // and the branch adder in the same cycle.
            U_DECODE: begin
                next_pc <= pc + 1'b1;      // default: fall through
                state   <= U_EXEC;
            end

            // ------------------------------------------------------------
            U_EXEC: begin
                state <= U_FETCH;          // overridden by jumps / waits

                case (opcode)
                UOP_NOP:  ;
                UOP_HALT: state <= U_DONE;

                // ---- register ops ----
                UOP_LDI:  regs[rd_idx] <= imm_lo;
                UOP_MOV:  regs[rd_idx] <= ra_val;
                UOP_ADD:  regs[rd_idx] <= ra_val + rb_val;
                UOP_SUB:  regs[rd_idx] <= ra_val - rb_val;
                UOP_ADDI: regs[rd_idx] <= ra_val + imm_lo;
                UOP_SHL:  regs[rd_idx] <= ra_val << imm_lo[4:0];
                UOP_SHR:  regs[rd_idx] <= ra_val >> imm_lo[4:0];

                // ---- control flow ----
                UOP_JMP:  next_pc <= imm_lo[AW-1:0];
                UOP_JNZ:  if (ra_val != 32'd0) next_pc <= imm_lo[AW-1:0];
                UOP_JZ:   if (ra_val == 32'd0) next_pc <= imm_lo[AW-1:0];
                UOP_LOOP: begin
                    // Decrement-and-branch. The comparison uses the value read
                    // in DECODE, so the branch decision and the writeback stay
                    // consistent within this single cycle.
                    regs[rd_idx] <= regs[rd_idx] - 32'd1;
                    if (regs[rd_idx] - 32'd1 != 32'd0)
                        next_pc <= imm_lo[AW-1:0];
                end

                // ---- parameter block ----
                // dst_sel bit 0 selects register-form (ra) over immediate, so
                // one opcode covers both without doubling the ISA.
                UOP_SET_SRC:  begin
                    if (`UC_DSTSEL(ir) == 4'd1) p_src1 <= (imm_hi[0] ? ra_val : imm_lo);
                    else                        p_src0 <= (imm_hi[0] ? ra_val : imm_lo);
                end
                UOP_SET_DST:  p_dst  <= (imm_hi[0] ? ra_val : imm_lo);
                UOP_SET_WGT:  p_wgt  <= (imm_hi[0] ? ra_val : imm_lo);
                UOP_SET_BIAS: p_bias <= (imm_hi[0] ? ra_val : imm_lo);
                UOP_SET_DIM:  begin p_in_w  <= imm_lo[15:0];  p_in_h  <= imm_lo[31:16]; end
                UOP_SET_CHAN: begin p_in_c  <= imm_lo[15:0];  p_in_c1 <= imm_lo[31:16]; end
                UOP_SET_ODIM: begin p_out_w <= imm_lo[15:0];  p_out_h <= imm_lo[31:16]; end
                UOP_SET_OCHAN:begin p_out_c <= imm_lo[15:0];  p_groups<= imm_lo[31:16]; end
                UOP_SET_KSPA: begin
                    p_kernel <= imm_lo[3:0];
                    p_stride <= imm_lo[7:4];
                    p_pad    <= imm_lo[11:8];
                    p_act    <= imm_lo[15:12];
                end
                UOP_SET_RQ:   begin
                    p_rq_mult  <= imm_lo[31:16];
                    p_rq_shift <= imm_lo[4:0];
                end
                UOP_SET_AUX:  begin
                    p_aux0 <= imm_lo;
                    p_aux1 <= {12'd0, imm_hi};
                end

                // ---- blocking engine dispatch ----
                UOP_CONV:   begin ce_start <= 1'b1; pending <= W_CONV; state <= U_WAIT; end
                UOP_ELEM:   begin
                    ee_op    <= {26'd0, imm_hi[5:0]};
                    ee_start <= 1'b1; pending <= W_ELEM; state <= U_WAIT;
                end
                UOP_DETECT: begin
                    de_flush <= 1'b0;
                    de_start <= 1'b1; pending <= W_DET;  state <= U_WAIT;
                end
                UOP_TOPK:   begin
                    de_flush <= 1'b1;
                    de_start <= 1'b1; pending <= W_DET;  state <= U_WAIT;
                end
                UOP_GEMM:   begin gm_start <= 1'b1; pending <= W_GEMM; state <= U_WAIT; end

                default: begin
                    // Unknown opcode means the program is corrupt or the
                    // assembler and RTL have drifted. Fail loudly rather than
                    // executing something arbitrary.
                    error <= 1'b1;
                    state <= U_ERR;
                end
                endcase
            end

            // ------------------------------------------------------------
            U_WAIT: begin
                case (pending)
                W_CONV: if (ce_done) begin
                            if (ce_error) begin error<=1'b1; state<=U_ERR; end
                            else                state <= U_FETCH;
                            pending <= W_NONE;
                        end
                W_ELEM: if (ee_done) begin
                            if (ee_error) begin error<=1'b1; state<=U_ERR; end
                            else                state <= U_FETCH;
                            pending <= W_NONE;
                        end
                W_DET:  if (de_done) begin
                            if (de_error) begin error<=1'b1; state<=U_ERR; end
                            else begin num_boxes <= de_num_boxes; state <= U_FETCH; end
                            pending <= W_NONE;
                        end
                W_GEMM: if (gm_done) begin
                            if (gm_error) begin error<=1'b1; state<=U_ERR; end
                            else                state <= U_FETCH;
                            pending <= W_NONE;
                        end
                default: state <= U_FETCH;
                endcase
            end

            // ------------------------------------------------------------
            U_DONE: begin
                busy  <= 1'b0;
                done  <= 1'b1;
                state <= U_IDLE;
            end

            U_ERR: begin
                busy  <= 1'b0;
                done  <= 1'b1;   // done+error so a CPU poll always terminates
                state <= U_IDLE;
            end

            default: state <= U_IDLE;
            endcase
        end
    end

endmodule
