// -----------------------------------------------------------------------------
// GENERATED by qrts/tools/port_rtl.py -- DO NOT EDIT THIS COPY.
//
// Source: DVCFinal/rtl/yolo_axi4_slave_regs.sv
//
// Edit the source and re-run the porter:
//     python qrts/tools/port_rtl.py
//
// Xilinx synthesis attributes have been rewritten for Quartus. See the porter
// for what is rewritten and what still needs hand work.
// -----------------------------------------------------------------------------
// =============================================================================
// yolo_axi4_slave_regs.sv — CPU-facing register file for the YOLO accelerator
//
// Extends the Stage 3B soc_axi4_slave_regs map with the registers the whole-
// network mode needs. The original six registers keep their offsets so the old
// single-GEMM test app still works unmodified against this file.
//
//   0x00 CTRL        bit0 START (self-clearing), bit1 MODE (0=GEMM, 1=YOLO)
//                    bit2 ENGINE within YOLO mode:
//                         0 = yolo_layer_sequencer (descriptor walk, default)
//                         1 = ucode_engine (experimental microcode path)
//                    reads back STATUS
//   0x04 STATUS      [0]busy [1]done [2]error [7:4]fsm
//   0x08 SRC_ADDR    GEMM activations
//   0x0C DST_ADDR    GEMM results
//   0x10 IMG_DIM     {K, ARRAY_SIZE}
//   0x14 WEIGHT_ADDR GEMM weights
//   -- new for whole-network mode --
//   0x18 DESC_ADDR   layer descriptor table base
//   0x1C IMG_ADDR    input bitmap base (INT8 CHW 3x640x640)
//   0x20 BOX_ADDR    output box list base
//   0x24 CONF        [7:0] confidence threshold (INT8, signed)
//   0x28 NUM_BOXES   read-only, boxes written by the last frame
//   0x2C LAYER_IDX   read-only, which descriptor is executing (progress/debug)
//
// ---------------------------------------------------------------------------
// The WSTRB decode is carried over from Stage 3A and is load-bearing.
// A 64-bit AXI master addresses in 8-byte words and selects the half with
// WSTRB, so a 32-bit store to 0x0C legally arrives as AWADDR=0x08, WSTRB=0xF0.
// Decoding AWADDR[5:0] raw aliases 0x04/0x0C/0x14 onto 0x00/0x08/0x10 and
// silently drops half the map -- that bug cost hours and presented as
// dst_addr=0. Confirmed against the Rapid Guide p.9 waveform. Do not
// "simplify" this back to a raw byte decode.
// ---------------------------------------------------------------------------
`timescale 1ns/1ps

module yolo_axi4_slave_regs #(
    parameter integer ID_WIDTH   = 12,
    parameter integer ADDR_WIDTH = 64,
    parameter integer DATA_WIDTH = 64
)(
    input  wire                        clk,
    input  wire                        rst_n,

    // ---- AXI4 slave: AW/W/B ----
    input  wire [ID_WIDTH-1:0]         s_axi_awid,
    input  wire [ADDR_WIDTH-1:0]       s_axi_awaddr,
    input  wire [7:0]                  s_axi_awlen,
    input  wire [2:0]                  s_axi_awsize,
    input  wire [1:0]                  s_axi_awburst,
    input  wire                        s_axi_awlock,
    input  wire [3:0]                  s_axi_awcache,
    input  wire [2:0]                  s_axi_awprot,
    input  wire [3:0]                  s_axi_awqos,
    input  wire                        s_axi_awvalid,
    output reg                         s_axi_awready,

    input  wire [DATA_WIDTH-1:0]       s_axi_wdata,
    input  wire [DATA_WIDTH/8-1:0]     s_axi_wstrb,
    input  wire                        s_axi_wlast,
    input  wire                        s_axi_wvalid,
    output reg                         s_axi_wready,

    input  wire                        s_axi_bready,
    output reg  [ID_WIDTH-1:0]         s_axi_bid,
    output reg  [1:0]                  s_axi_bresp,
    output reg                         s_axi_bvalid,

    // ---- AXI4 slave: AR/R ----
    input  wire [ID_WIDTH-1:0]         s_axi_arid,
    input  wire [ADDR_WIDTH-1:0]       s_axi_araddr,
    input  wire [7:0]                  s_axi_arlen,
    input  wire [2:0]                  s_axi_arsize,
    input  wire [1:0]                  s_axi_arburst,
    input  wire                        s_axi_arlock,
    input  wire [3:0]                  s_axi_arcache,
    input  wire [2:0]                  s_axi_arprot,
    input  wire [3:0]                  s_axi_arqos,
    input  wire                        s_axi_arvalid,
    output reg                         s_axi_arready,

    input  wire                        s_axi_rready,
    output reg  [ID_WIDTH-1:0]         s_axi_rid,
    output reg  [DATA_WIDTH-1:0]       s_axi_rdata,
    output reg  [1:0]                  s_axi_rresp,
    output reg                         s_axi_rlast,
    output reg                         s_axi_rvalid,

    // ---- to the datapath ----
    output reg                         start_pulse,
    output reg                         mode_yolo,
    // CTRL bit2. Selects which engine executes YOLO mode. The sequencer walks
    // the descriptor table in DRAM and has no instruction-count ceiling; the
    // microcode engine is kept as the experimental path because its RAM holds
    // only 1024 words and no program for this network exists.
    output reg                         mode_ucode,
    output reg  [31:0]                 src_addr,
    output reg  [31:0]                 dst_addr,
    output reg  [31:0]                 img_dim,
    output reg  [31:0]                 weight_addr,
    output reg  [31:0]                 desc_addr,
    output reg  [31:0]                 img_addr,
    output reg  [31:0]                 box_addr,
    output reg  signed [7:0]           conf_thresh,

    // ---- microcode instruction RAM write port ----
    // The CPU stages a program here before START. Writes land at
    // UCODE_WIN_BASE + word*8; two 32-bit stores (or one 64-bit store) make
    // one instruction word, so a 32-bit CPU can load the program without a
    // 64-bit access path.
    output reg                         ucode_we,
    output reg  [9:0]                  ucode_waddr,
    output reg  [63:0]                 ucode_wdata,

    input  wire                        busy_in,
    input  wire                        done_in,
    input  wire                        error_in,
    input  wire [3:0]                  fsm_in,
    input  wire [15:0]                 num_boxes_in,
    input  wire [15:0]                 layer_idx_in,
    input  wire [15:0]                 ucode_pc_in
);

    localparam [5:0] OFF_CTRL   = 6'h00;
    localparam [5:0] OFF_STATUS = 6'h04;
    localparam [5:0] OFF_SRC    = 6'h08;
    localparam [5:0] OFF_DST    = 6'h0C;
    localparam [5:0] OFF_IMG    = 6'h10;
    localparam [5:0] OFF_WT     = 6'h14;
    localparam [5:0] OFF_DESC   = 6'h18;
    localparam [5:0] OFF_IMGA   = 6'h1C;
    localparam [5:0] OFF_BOX    = 6'h20;
    localparam [5:0] OFF_CONF   = 6'h24;
    localparam [5:0] OFF_NBOX   = 6'h28;
    localparam [5:0] OFF_LAYER  = 6'h2C;
    localparam [5:0] OFF_UCPC   = 6'h30;   // read-only: microcode PC

    // Microcode RAM aperture. Anything at or above this in the slave's address
    // space is an instruction-RAM write rather than a register access. 0x1000
    // is clear of the 0x00..0x3F register block with room to spare, and
    // 1024 instructions * 8 B = 8 KB fits in 0x1000..0x2FFF.
    localparam [19:0] UCODE_WIN_BASE = 20'h01000;
    localparam [19:0] UCODE_WIN_END  = 20'h03000;

    // =========================================================================
    // Write channel
    // =========================================================================
    localparam [1:0] W_IDLE=2'd0, W_DATA=2'd1, W_RESP=2'd2;
    reg [1:0]           wstate;
    reg [ID_WIDTH-1:0]  awid_lat;
    reg [5:0]           awoff_lat;
    // Full low-order address, needed because the microcode aperture is far
    // larger than the 6-bit register offset can express.
    reg [19:0]          awfull_lat;

    wire [5:0] wr_off_lo = {awoff_lat[5:3], 3'b000};
    wire [5:0] wr_off_hi = {awoff_lat[5:3], 3'b100};
    wire       wr_en_lo  = |s_axi_wstrb[3:0];
    wire       wr_en_hi  = |s_axi_wstrb[7:4];

    wire       is_ucode  = (awfull_lat >= UCODE_WIN_BASE) &&
                           (awfull_lat <  UCODE_WIN_END);
    // 8 bytes per instruction word -> word index is the byte offset >> 3.
    wire [9:0] ucode_idx = (awfull_lat - UCODE_WIN_BASE) >> 3;

    task automatic write_reg(input [5:0] off, input [31:0] data);
        begin
            case (off)
                OFF_CTRL: begin
                    if (data[0]) start_pulse <= 1'b1;
                    mode_yolo  <= data[1];
                    mode_ucode <= data[2];
                end
                OFF_SRC:  src_addr    <= data;
                OFF_DST:  dst_addr    <= data;
                OFF_IMG:  img_dim     <= data;
                OFF_WT:   weight_addr <= data;
                OFF_DESC: desc_addr   <= data;
                OFF_IMGA: img_addr    <= data;
                OFF_BOX:  box_addr    <= data;
                OFF_CONF: conf_thresh <= data[7:0];
                default: ;
            endcase
        end
    endtask

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            wstate        <= W_IDLE;
            s_axi_awready <= 1'b0;
            s_axi_wready  <= 1'b0;
            s_axi_bvalid  <= 1'b0;
            s_axi_bresp   <= 2'b00;
            s_axi_bid     <= {ID_WIDTH{1'b0}};
            start_pulse   <= 1'b0;
            mode_yolo     <= 1'b0;
            mode_ucode    <= 1'b0;
            src_addr      <= 32'h0;
            dst_addr      <= 32'h0;
            img_dim       <= 32'h0;
            weight_addr   <= 32'h0;
            desc_addr     <= 32'h0;
            img_addr      <= 32'h0;
            box_addr      <= 32'h0;
            conf_thresh   <= 8'sd0;
            awfull_lat    <= 20'h0;
            ucode_we      <= 1'b0;
            ucode_waddr   <= 10'd0;
            ucode_wdata   <= 64'd0;
        end else begin
            start_pulse <= 1'b0;
            ucode_we    <= 1'b0;      // single-cycle write strobe
            case (wstate)
                W_IDLE: begin
                    s_axi_awready <= 1'b1;
                    if (s_axi_awvalid && s_axi_awready) begin
                        awid_lat      <= s_axi_awid;
                        awoff_lat     <= s_axi_awaddr[5:0];
                        awfull_lat    <= s_axi_awaddr[19:0];
                        s_axi_awready <= 1'b0;
                        s_axi_wready  <= 1'b1;
                        wstate        <= W_DATA;
                    end
                end
                W_DATA: begin
                    if (s_axi_wvalid && s_axi_wready) begin
                        s_axi_wready <= 1'b0;
                        if (is_ucode) begin
                            // Instruction word. A 64-bit master writes both
                            // lanes at once; a 32-bit CPU writes the low half
                            // then the high half, and only the second store
                            // (WSTRB high lanes set) commits the word. The
                            // low half is held so the pair lands atomically --
                            // committing on each half would execute a
                            // half-written instruction if START raced the load.
                            if (wr_en_lo && wr_en_hi) begin
                                ucode_wdata <= s_axi_wdata;
                                ucode_waddr <= ucode_idx;
                                ucode_we    <= 1'b1;
                            end else if (wr_en_lo) begin
                                ucode_wdata[31:0] <= s_axi_wdata[31:0];
                            end else if (wr_en_hi) begin
                                ucode_wdata[63:32] <= s_axi_wdata[63:32];
                                ucode_waddr        <= ucode_idx;
                                ucode_we           <= 1'b1;
                            end
                        end else begin
                            if (wr_en_lo) write_reg(wr_off_lo, s_axi_wdata[31:0]);
                            if (wr_en_hi) write_reg(wr_off_hi, s_axi_wdata[63:32]);
                        end
                        s_axi_bid    <= awid_lat;
                        s_axi_bresp  <= 2'b00;
                        s_axi_bvalid <= 1'b1;
                        wstate       <= W_RESP;
                    end
                end
                W_RESP: begin
                    if (s_axi_bvalid && s_axi_bready) begin
                        s_axi_bvalid <= 1'b0;
                        wstate       <= W_IDLE;
                    end
                end
                default: wstate <= W_IDLE;
            endcase
        end
    end

    // =========================================================================
    // Read channel
    // =========================================================================
    localparam W_R_IDLE=1'd0, W_R_DATA=1'd1;
    reg                r_state;
    reg [ID_WIDTH-1:0] arid_lat;
    reg [5:0]          aroff_lat;

    wire [31:0] status_val;
    assign status_val[0]    = busy_in;
    assign status_val[1]    = done_in;
    assign status_val[2]    = error_in;
    assign status_val[3]    = 1'b0;
    assign status_val[7:4]  = fsm_in;
    assign status_val[31:8] = 24'b0;

    function automatic [31:0] read_reg(input [5:0] off);
        case (off)
            OFF_CTRL:   read_reg = status_val;   // CTRL is write-only in effect
            OFF_STATUS: read_reg = status_val;
            OFF_SRC:    read_reg = src_addr;
            OFF_DST:    read_reg = dst_addr;
            OFF_IMG:    read_reg = img_dim;
            OFF_WT:     read_reg = weight_addr;
            OFF_DESC:   read_reg = desc_addr;
            OFF_IMGA:   read_reg = img_addr;
            OFF_BOX:    read_reg = box_addr;
            OFF_CONF:   read_reg = {24'h0, conf_thresh};
            OFF_NBOX:   read_reg = {16'h0, num_boxes_in};
            OFF_LAYER:  read_reg = {16'h0, layer_idx_in};
            OFF_UCPC:   read_reg = {16'h0, ucode_pc_in};
            default:    read_reg = 32'hDEAD_BEEF;
        endcase
    endfunction

    // Both registers of the addressed 8-byte word are driven onto their natural
    // lanes. Mirroring one value onto both halves (as the DVCon reference
    // netlist does) is NOT equivalent -- STATUS at 0x04 is a high-lane read and
    // mirroring breaks it. See PORT-NOTES.md.
    wire [5:0]  rd_off_lo  = {aroff_lat[5:3], 3'b000};
    wire [5:0]  rd_off_hi  = {aroff_lat[5:3], 3'b100};
    wire [63:0] read_pair  = {read_reg(rd_off_hi), read_reg(rd_off_lo)};

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            r_state       <= W_R_IDLE;
            s_axi_arready <= 1'b0;
            s_axi_rvalid  <= 1'b0;
            s_axi_rid     <= {ID_WIDTH{1'b0}};
            s_axi_rresp   <= 2'b00;
            s_axi_rlast   <= 1'b0;
            s_axi_rdata   <= {DATA_WIDTH{1'b0}};
        end else begin
            case (r_state)
                W_R_IDLE: begin
                    s_axi_arready <= 1'b1;
                    if (s_axi_arvalid && s_axi_arready) begin
                        arid_lat      <= s_axi_arid;
                        aroff_lat     <= s_axi_araddr[5:0];
                        s_axi_arready <= 1'b0;
                        r_state       <= W_R_DATA;
                    end
                end
                W_R_DATA: begin
                    if (!s_axi_rvalid) begin
                        s_axi_rid    <= arid_lat;
                        s_axi_rresp  <= 2'b00;
                        s_axi_rlast  <= 1'b1;
                        s_axi_rdata  <= read_pair;
                        s_axi_rvalid <= 1'b1;
                    end else if (s_axi_rvalid && s_axi_rready) begin
                        s_axi_rvalid <= 1'b0;
                        r_state      <= W_R_IDLE;
                    end
                end
                default: r_state <= W_R_IDLE;
            endcase
        end
    end

endmodule
