// -----------------------------------------------------------------------------
// GENERATED by qrts/tools/port_rtl.py -- DO NOT EDIT THIS COPY.
//
// Source: DVCFinal/rtl/yolo_conv_engine.sv
//
// Edit the source and re-run the porter:
//     python qrts/tools/port_rtl.py
//
// Xilinx synthesis attributes have been rewritten for Quartus. See the porter
// for what is rewritten and what still needs hand work.
// -----------------------------------------------------------------------------
// =============================================================================
// yolo_conv_engine.sv — tiled INT8 convolution over the systolic array
//
// The array is ARRAY_SIZE x ARRAY_SIZE. Real YOLO26n layers are up to
// 256 in-channels x 256 out-channels over a 160x160 map, so every layer is a
// three-level tile loop:
//
//   for oc_tile in ceil(out_c / ARRAY_SIZE):        <- weight tile columns
//     for ic_tile in ceil(k*k*in_c / ARRAY_SIZE):   <- reduction depth
//       load weight tile (ARRAY_SIZE x ARRAY_SIZE INT8)
//       for each output position (out_w * out_h):
//         stream the lowered activation column, MAC into the accumulator
//     requantize the ARRAY_SIZE accumulators -> INT8, write out
//
// Accumulators live in the output BRAM at INT32 across the whole ic_tile loop
// and are only requantized on the LAST ic_tile. Requantizing per tile would
// clamp mid-reduction and silently change the numerics -- see the note in
// yolo_layer_sequencer.sv.
//
// Weight layout the exporter must produce (GEMM layout, not PyTorch layout):
//   for each oc_tile, for each ic_tile: an ARRAY_SIZE x ARRAY_SIZE INT8 tile,
//   row = reduction index (k*k*in_c), column = output channel, row-major,
//   zero padded when the layer does not fill the tile.
// Emitting these in the loop order above means the engine reads weights
// strictly sequentially and never seeks -- worth the exporter complexity.
//
// Depthwise convs (LAYER_F_DEPTHWISE) reduce over k*k only, with out_c == in_c
// and one group per channel. The exporter still emits square tiles; the engine
// just uses a different reduction extent.
// =============================================================================
`timescale 1ns/1ps

module yolo_conv_engine #(
    parameter integer ARRAY_SIZE = 24,
    parameter integer DATA_WIDTH = 8,
    parameter integer ACC_WIDTH  = 32,
    parameter integer MAX_IMG_W  = 640
)(
    input  wire        clk,
    input  wire        rst_n,

    // ---- job from the sequencer ----
    input  wire        start,
    input  wire [31:0] src_addr,
    input  wire [31:0] dst_addr,
    input  wire [31:0] wgt_addr,
    input  wire [31:0] bias_addr,
    input  wire [15:0] in_w, in_h, in_c,
    input  wire [15:0] out_w, out_h, out_c,
    input  wire [3:0]  kernel, stride, pad, act_type,
    input  wire [15:0] rq_mult,
    input  wire [4:0]  rq_shift,
    input  wire        depthwise,
    // Codes-per-unit for this layer's output activations, Q8.8. Only used when
    // act_type is SILU: the INT8 code -> real value mapping differs per layer,
    // so the activation cannot be a single fixed table. 0 means "not set",
    // which silu_unit treats as pass-through rather than emitting zeros.
    input  wire [15:0] act_scale,

    output reg         busy,
    // Debug taps. The descriptor fetch is fixed and the walk now reaches layer
    // 6 and stalls inside CONV_W, which from outside is indistinguishable
    // between "the engine is waiting on memory" and "the engine's own loop is
    // not advancing". These two words tell those apart from the host.
    output wire [31:0] dbg_conv0,   // {beat_cnt, 3'b0, state}
    output wire [31:0] dbg_conv1,   // {oc_tile, ic_tile}
    output reg         done,
    output reg         error,
    // 5 bits: the encoding outgrew a nibble when the requantize was split
    // across two states. At 4, C_REQ_M (16) would truncate to 0 and the debug
    // register would report C_IDLE mid-requantize.
    output reg  [4:0]  fsm_state,

    // ---- AXI4 master read ----
    output reg         rd_start,
    output reg  [63:0] rd_addr,
    output reg  [7:0]  rd_len,
    input  wire [63:0] rd_data,
    input  wire        rd_data_valid,
    input  wire        rd_done,
    input  wire        rd_error,

    // ---- AXI4 master write ----
    output reg         wr_start,
    output reg  [63:0] wr_addr,
    output reg  [7:0]  wr_len,
    output reg  [63:0] wr_data,
    output reg  [7:0]  wr_strb,
    input  wire        wr_data_ready,
    input  wire        wr_done,
    input  wire        wr_error,

    // ---- systolic array (system_top legacy phase interface) ----
    output reg signed [DATA_WIDTH-1:0] input_data [0:ARRAY_SIZE-1],
    input  wire                        loading_weights,
    input  wire                        streaming_acts,
    input  wire                        sys_busy,
    input  wire                        sys_done,
    input  wire signed [ARRAY_SIZE*ACC_WIDTH-1:0] output_data,

    // ---- system_top AXI4-Lite config (driven by this engine) ----
    output reg         s_awvalid,
    output reg  [63:0] s_awaddr,
    output reg         s_wvalid,
    output reg  [31:0] s_wdata,
    output reg  [3:0]  s_wstrb,
    input  wire        s_awready,
    input  wire        s_wready,
    output reg         s_bready,
    input  wire        s_bvalid,
    input  wire [1:0]  s_bresp
);

    localparam integer WTILE_BYTES = ARRAY_SIZE*ARRAY_SIZE;
    localparam integer WTILE_BEATS = WTILE_BYTES/8;

    // =========================================================================
    // Geometry, latched at start
    // =========================================================================
    reg [15:0] g_in_w, g_in_h, g_in_c, g_out_w, g_out_h, g_out_c;
    reg [3:0]  g_k, g_s, g_p, g_act;
    reg [15:0] g_rq_mult;
    reg [4:0]  g_rq_shift;
    reg        g_dw;
    reg [15:0] g_act_scale;
    reg [31:0] g_src, g_dst, g_wgt, g_bias;

    // Reduction extent in elements: k*k*in_c dense, k*k depthwise.
    wire [31:0] reduce_len = g_dw ? (g_k*g_k)
                                  : (g_k*g_k*g_in_c);

    // Tile counts (ceil division).
    // Dense packs ARRAY_SIZE output channels into one pass (one per array
    // column). Depthwise cannot: every output channel reduces over its OWN
    // input plane, but the array broadcasts one activation per reduction row
    // across all columns, so a pass can only serve one channel. Depthwise
    // therefore takes out_c passes, with the channel index carried in oc_tile
    // and only lane 0 meaningful.
    //
    // The exporter already emits depthwise tiles with row = window tap and
    // column = output channel, so the weights for pass `oc_tile` are the ones
    // this pass needs in column oc_tile%ARRAY_SIZE -- see dw_col below.
    wire [15:0] n_oc_tiles = g_dw ? g_out_c
                                  : ((g_out_c + ARRAY_SIZE-1) / ARRAY_SIZE);
    wire [15:0] n_ic_tiles = (reduce_len + ARRAY_SIZE-1) / ARRAY_SIZE;

    // Flat index of the weight tile for (wgt_oc_tile, ic_tile), maintained
    // incrementally rather than recomputed as a multiply inside the address.
    //
    // Written as `(wgt_oc_tile*n_ic_tiles + ic_tile) * WTILE_BYTES` this was
    // the design's critical path at -2.9 ns: n_ic_tiles is itself derived from
    // g_k through reduce_len, so the multiply sat at the end of a long
    // combinational chain from the layer geometry registers.
    //
    // The loop nest is oc_tile -> pos -> ic_tile, so ic_tile RESTARTS at zero
    // for every output position and the flat index is not a simple counter.
    // What is constant across a whole output channel is the row base
    // wgt_oc_tile*n_ic_tiles, so that is registered once when the channel
    // changes, and the index is just base + ic_tile.
    reg [31:0] wtile_base;
    wire [31:0] n_pos      = g_out_w * g_out_h;

    reg [15:0] oc_tile, ic_tile;

    // Flat weight-tile index: the registered per-channel base plus the inner
    // loop counter. See wtile_base above.
    wire [31:0] wtile_idx = wtile_base + {16'h0, ic_tile};

    // Depthwise walks one channel per pass, so oc_tile is a CHANNEL index and
    // the weight tile it lives in is oc_tile/ARRAY_SIZE, at column
    // oc_tile%ARRAY_SIZE. Dense keeps oc_tile as the tile index and lane j is
    // channel oc_tile*ARRAY_SIZE+j.
    wire [15:0] wgt_oc_tile = g_dw ? (oc_tile / ARRAY_SIZE) : oc_tile;
    wire [15:0] dw_col      = g_dw ? (oc_tile % ARRAY_SIZE) : 16'd0;

    // Lanes this pass actually produces: all ARRAY_SIZE columns for dense, just
    // the one column dw_col selects for depthwise.
    wire [15:0] n_lanes = g_dw ? 16'd1 : ARRAY_SIZE[15:0];

    // Which bias block bias_buf currently holds, and whether it holds one.
    reg [15:0] bias_tile;
    reg        bias_tile_valid;
    reg [31:0] pos;
    wire is_last_ic = (ic_tile == n_ic_tiles - 1);

    // =========================================================================
    // Local buffers
    //
    // weight_buf holds one ARRAY_SIZE^2 INT8 tile. act_col holds one lowered
    // activation column. acc_buf holds ARRAY_SIZE INT32 partial sums for the
    // output position currently in flight.
    //
    // Deliberately NOT reset -- an async reset in the same always block blocks
    // Vivado RAM inference (Stage 3A trap 5.x, cost hours on the Basys3 port).
    // =========================================================================
    reg [7:0]  weight_buf [0:WTILE_BYTES-1];
    reg [7:0]  act_col    [0:ARRAY_SIZE-1];
    // Stable copy of act_col, captured when the array is started and held for
    // the whole run. See the input_data mux below.
    reg [7:0]  act_shadow [0:ARRAY_SIZE-1];
    reg signed [ACC_WIDTH-1:0] acc_buf [0:ARRAY_SIZE-1];

    // Registered product between the two halves of the requantize.
    reg signed [63:0] rq_prod;
    reg signed [ACC_WIDTH-1:0] bias_buf[0:ARRAY_SIZE-1];

    // =========================================================================
    // Phase-locked feed into the array (mirrors accel_dma_seq's proven form)
    // =========================================================================
    reg [$clog2(ARRAY_SIZE)-1:0] w_row_idx;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n)               w_row_idx <= '0;
        else if (loading_weights) w_row_idx <= w_row_idx + 1'b1;
        else                      w_row_idx <= '0;
    end

    integer di;
    always @(*) begin
        for (di = 0; di < ARRAY_SIZE; di = di + 1) input_data[di] = 8'sd0;
        if (loading_weights) begin
            // The weight path REVERSES row order. shift_reg_buffer pushes one
            // row per cycle and exposes stage d+1 as connect_wires_out[d*W+w]
            // (shift_reg_buffer.sv:70-76); after ARRAY_SIZE pushes, stage d+1
            // holds the row pushed ARRAY_SIZE-1-d cycles ago, so the array's
            // weight_reg[wr][wc] receives reduction row ARRAY_SIZE-1-wr.
            //
            // Feed the rows back-to-front so they land the right way up. The
            // alternative -- having the exporter emit reversed tiles -- moves a
            // hardware quirk into the model blob, where nothing checks it.
            //
            // Measured, not assumed: tb_array_probe drives system_top directly
            // with a random tile and only the reversed feed reproduces the
            // reference dot product. The existing tb_system_top_fix bench does
            // NOT catch this because it uses identity and one-hot tiles, which
            // are symmetric under row reversal.
            for (di = 0; di < ARRAY_SIZE; di = di + 1)
                input_data[di] =
                    weight_buf[(ARRAY_SIZE-1 - w_row_idx)*ARRAY_SIZE + di];
        end else if (streaming_acts) begin
            // Stream from the SHADOW copy, not from act_col.
            //
            // act_col is refilled by C_ACT one element at a time, and the array
            // keeps streaming for num_acts cycles after the FSM has moved on.
            // Feeding act_col directly let the next position's gather bleed
            // into the run still in flight, so a tile now and then MACed a
            // half-updated column -- one wrong ic_tile per output position,
            // the rest correct, which is exactly how it presented.
            for (di = 0; di < ARRAY_SIZE; di = di + 1)
                input_data[di] = act_shadow[di];
        end
    end

    // =========================================================================
    // im2col address generation
    //
    // Rather than a streaming line buffer, this walks the source map directly:
    // for output position (oy,ox) and reduction index r, the source element is
    //   c  = r / (k*k)          input channel
    //   kk = r % (k*k)          position in the window
    //   iy = oy*s - p + kk/k
    //   ix = ox*s - p + kk%k
    // Out-of-range -> zero (padding). One AXI read per element is slow but
    // correct; the burst-coalescing optimization is listed in docs as future
    // work rather than attempted here, because a wrong address generator is
    // much harder to debug than a slow one.
    // =========================================================================
    // -------------------------------------------------------------------------
    // Address generation without dividers.
    //
    // The natural way to write this is oy = pos / out_w, kk = r % (k*k), and so
    // on. Those are VARIABLE divides and modulos: on a 7-series part each one
    // synthesises into a large combinational divider (and the multiplies pull
    // in DSPs), which cost ~94 DSP and put a long path in the middle of an
    // address calculation. The provided design already ships WNS -0.034, so it
    // has no margin to spend on that.
    //
    // Every one of these quantities is walked in order, so each is maintained
    // as a counter that increments alongside its driver instead. Same
    // addresses, no dividers, and the only multiplies left are by g_in_w /
    // g_in_h, which the tool maps to a small number of DSPs.
    // -------------------------------------------------------------------------
    reg  [15:0] req_idx;                   // lane being requantized (serialized)
    reg  [31:0] plane_sz;                  // g_in_h  * g_in_w,  computed once
    reg  [31:0] oplane_sz;                 // g_out_h * g_out_w, computed once
    reg  [15:0] oy, ox;                    // output position, tracked with pos
    reg  [15:0] r_idx;                     // reduction index within the tile
    reg  [31:0] r_abs;                     // absolute reduction index
    reg  [15:0] kk;                        // window offset  (r_abs % k*k)
    reg  [15:0] cc;                        // input channel  (r_abs / k*k)
    reg  [3:0]  kk_y, kk_x;                // kk / g_k, kk % g_k
    reg  [15:0] k_sq;                      // g_k * g_k, latched at start

    // ---- A1: cached reduction seed, and the serial divider that fills it ----
    // seed_* hold the decomposition of the FIRST element of ic tile
    // `seed_tile`: r_abs = seed_tile*ARRAY_SIZE, and (cc,kk,kk_y,kk_x) its
    // (channel, window, ky, kx) decomposition. seed_reduction() restores them.
    reg  [31:0] seed_r_abs;
    reg  [15:0] seed_kk, seed_cc;
    reg  [3:0]  seed_kk_y, seed_kk_x;

    // Divider state. sd_busy is high while a seed is being computed; the FSM
    // waits on it before entering any state that consumes seed_*.
    //
    // Restoring subtraction, one subtract per cycle. The quotients are small
    // -- base/k_sq is at most in_c (<=1024) and kk_seed/g_k at most g_k (<=7)
    // -- and this runs once per ic_tile, overlapped with the weight-tile burst
    // read in C_WLOAD, so the cycles are free.
    reg         sd_busy;
    reg  [1:0]  sd_phase;
    reg  [31:0] sd_num;     // running remainder
    reg  [15:0] sd_quot;    // running quotient
    reg  [31:0] sd_base;    // tile*ARRAY_SIZE, the value being decomposed
    // rd_done is a single-cycle pulse. C_WLOAD may have to wait on the seed
    // divider after the burst has already finished, so the pulse is latched
    // rather than tested directly -- testing it directly loses it and hangs.
    reg         wload_rd_done, wload_rd_err;
    // One read may be outstanding at a time. See the note on the C_WLOAD /
    // C_BLOAD request guards below.
    reg         rd_inflight;

    // oy*g_s - g_p and ox*g_s - g_p depend only on the OUTPUT POSITION, which
    // advances in C_NEXT -- and C_NEXT is always followed by C_WLOAD, a
    // multi-beat burst read, before any gather uses these. So they are
    // registered once per position rather than recomputed per gather element.
    //
    // This is the invariant an earlier attempt got wrong: it tried to register
    // the whole row address cc*plane_sz + iy*g_in_w, which depends on cc and
    // kk_y and therefore changes EVERY element. That produced 2784 wrong
    // outputs out of 3560.
    reg signed [31:0] oy_base, ox_base;

    wire signed [31:0] iy = oy_base + $signed({28'h0, kk_y});
    wire signed [31:0] ix = ox_base + $signed({28'h0, kk_x});
    wire in_range = (iy >= 0) && (iy < $signed({16'h0, g_in_h})) &&
                    (ix >= 0) && (ix < $signed({16'h0, g_in_w})) &&
                    (r_abs < reduce_len);
    // CHW layout: element (c,y,x) at c*H*W + y*W + x
    //
    // plane_sz is c*H*W computed once per layer, so that multiply is already
    // out of the per-element path. The two that remain -- cc*plane_sz and
    // iy*g_in_w -- are DEPENDENT, because iy is itself oy*g_s - g_p + kk_y.
    // The chain g_s -> iy -> iy*g_in_w -> +cc*plane_sz -> rd_addr was the last
    // failing path at -0.5 ns.
    //
    // src_row is that sum registered: everything above the innermost term.
    // It is recomputed whenever the row or channel changes, which is far less
    // often than every element, and src_off is then a single add.
    // NOT registered. An attempt to pipeline this -- holding
    // cc*plane_sz + iy*g_in_w in a register one cycle behind, so src_off would
    // be a single add -- produced 2784 wrong outputs out of 3560. The reasoning
    // was that C_ACT always passes through C_ACT_W between reduction steps and
    // so leaves a spare cycle; that is not true on every path through the
    // gather, and a stale row address reads the wrong activation silently.
    //
    // The chain g_s -> iy -> iy*g_in_w -> +cc*plane_sz is therefore still the
    // critical path, at -0.5 ns in the slow 85C corner. Fixing it properly
    // means restructuring the gather loop so the row address is computed once
    // per row rather than per element -- a real change, with the numerics
    // bench as the gate.
    wire [31:0] src_off = cc*plane_sz + iy*g_in_w + ix;

    // Advance the reduction cursor and the (kk, cc) decomposition together.
    task automatic step_reduction;
        begin
            r_abs <= r_abs + 32'd1;
            if (g_dw) begin
                // Depthwise reduces over the window only; cc is the tile index.
                if (kk_x == g_k - 1) begin
                    kk_x <= 4'd0;
                    kk_y <= kk_y + 4'd1;
                end else begin
                    kk_x <= kk_x + 4'd1;
                end
                kk <= kk + 16'd1;
            end else begin
                if (kk == k_sq - 1) begin
                    kk   <= 16'd0;
                    kk_y <= 4'd0;
                    kk_x <= 4'd0;
                    cc   <= cc + 16'd1;     // next input channel
                end else begin
                    kk <= kk + 16'd1;
                    if (kk_x == g_k - 1) begin
                        kk_x <= 4'd0;
                        kk_y <= kk_y + 4'd1;
                    end else begin
                        kk_x <= kk_x + 4'd1;
                    end
                end
            end
        end
    endtask

    // Kick off the seed computation for `tile`. Non-blocking, like everything
    // else in this always block; the result lands in seed_* when sd_busy falls.
    //
    // Depthwise needs no division at all: cc is the tile index and the window
    // index is the base itself, so phase 0 finishes it in one cycle.
    // `chan` is the depthwise source plane. It is passed in rather than read
    // from oc_tile because the caller in C_NEXT assigns oc_tile non-blocking in
    // the same cycle: reading it here would capture the PREVIOUS channel, and
    // the first output position of every new depthwise channel would reduce
    // over the wrong input plane. (Positions 1+ were correct, which is exactly
    // how it presented -- six wrong pixels, all at oy=0 ox=0.)
    task automatic sd_start(input [15:0] tile, input [15:0] chan);
        reg [31:0] base;
        begin
            base       = tile * ARRAY_SIZE;   // constant multiply
            sd_base    <= base;
            seed_r_abs <= base;
            if (g_dw) begin
                // base % k_sq and base / k_sq are not used depthwise.
                seed_kk  <= base[15:0];
                seed_cc  <= chan;
                sd_num   <= {16'h0, base[15:0]};  // decompose kk into (ky,kx)
                sd_quot  <= 16'd0;
                sd_phase <= 2'd2;
                sd_busy  <= 1'b1;
            end else begin
                sd_num   <= base;                 // divide by k_sq first
                sd_quot  <= 16'd0;
                sd_phase <= 2'd0;
                sd_busy  <= 1'b1;
            end
        end
    endtask

    // Reset the decomposition to the first element of a given ic_tile.
    //
    // Non-blocking throughout: these registers are also driven by
    // step_reduction() inside the same always block, and mixing blocking and
    // non-blocking assignments to one register is a race that simulates and
    // synthesises differently.
    //
    // A1: this used to compute `base % k_sq`, `base / k_sq`, `kk_seed / g_k`
    // and `kk_seed % g_k` inline. It is called once per ic_tile AND once per
    // output position (C_NEXT's `pos` branch), so those variable dividers sat
    // in the per-position path: 148 logic levels / 92 CARRY4, a 41.4 ns path
    // that missed 50 MHz by 21.5 ns.
    //
    // The seed depends only on the tile, so on the `pos` branch it is the same
    // value every time. The serial divider below computes it once, when the
    // tile changes, into seed_*; this restores from those registers. No
    // divider remains in any FSM path.
    task automatic seed_reduction;
        begin
            r_abs <= seed_r_abs;
            kk    <= seed_kk;
            cc    <= seed_cc;
            kk_y  <= seed_kk_y;
            kk_x  <= seed_kk_x;
        end
    endtask

    // =========================================================================
    // FSM
    // =========================================================================
    localparam [4:0]
        C_IDLE     = 5'd0,
        C_WLOAD    = 5'd1,   // burst-read the weight tile
        C_BLOAD    = 5'd2,   // burst-read the bias vector
        C_CFG      = 5'd3,   // program system_top (IMG_DIM then CTRL)
        C_CFG_W    = 5'd4,
        C_ACT      = 5'd5,   // gather one lowered activation column
        C_ACT_W    = 5'd6,
        C_RUN      = 5'd7,   // array streams, wait sys_done
        C_ACCUM    = 5'd8,   // fold output_data into acc_buf
        C_REQ      = 5'd9,   // requantize + activation
        C_STORE    = 5'd10,  // write INT8 results back
        C_STORE_W  = 5'd11,
        C_NEXT     = 5'd12,
        C_DONE     = 5'd13,
        C_ERR      = 5'd14,
        C_SILU     = 5'd15,  // apply SiLU to the requantized lanes
        C_REQ_M    = 5'd16;  // second half of the pipelined requantize

    reg [4:0] state;
    reg [15:0] beat_cnt;
    reg [7:0]  cfg_step;
    reg        run_armed;   // sys_done seen low since this run's START

    // Placed after beat_cnt's declaration, not next to `state`: these are read
    // by the host over JTAG to tell a memory stall apart from a stalled loop.
    assign dbg_conv0 = {beat_cnt, 3'b000, state};
    assign dbg_conv1 = {oc_tile, ic_tile};

    // Destination byte address of the lane currently being stored. Broken out
    // because C_STORE needs it three times (address, data lane, strobe lane)
    // and recomputing it inline invites the three from drifting apart.
    // Output channel this store beat belongs to: depthwise passes carry the
    // channel in oc_tile and emit one byte, dense emits ARRAY_SIZE with lane
    // beat_cnt selecting the channel within the tile.
    wire [31:0] st_channel   = g_dw ? {16'h0, oc_tile}
                                    : (oc_tile*ARRAY_SIZE + beat_cnt);
    wire [31:0] st_byte_addr = g_dst + st_channel*oplane_sz + pos;
    integer    ri;

    // ---- SiLU activation ----------------------------------------------------
    // Sequential (3-cycle) because it is a table lookup with a per-layer scale
    // applied around it, so it cannot live inside requant()'s combinational
    // path. One instance, walked over the lanes -- the same reasoning that
    // serialises the requant multiplier.
    reg  signed [7:0] silu_x;
    reg               silu_vin;
    wire signed [7:0] silu_y;
    wire              silu_vout;

    silu_unit u_silu (
        .clk(clk), .rst_n(rst_n),
        .x(silu_x), .scale_q88(g_act_scale), .valid_in(silu_vin),
        .y(silu_y), .valid_out(silu_vout)
    );

    reg [15:0] silu_issue;   // lane being fed in
    reg [15:0] silu_recv;    // lane being written back

    // ---- requantize one accumulator to INT8 --------------------------------
    // Matches vector_unit.sv exactly: bias add, Q0.16 multiply, arithmetic
    // shift, clamp, then activation. Kept inline (not the vector_unit instance)
    // because this path is one lane at a time and reuses the same DSP.
    // The multiply half of the requantize, registered into rq_prod by C_REQ.
    // Splitting it out is what took the conv engine off the critical path:
    // as one combinational function this was a 64-bit multiply AND a variable
    // shift, reached through a 16-way mux on acc_buf and written back through
    // another -- the worst path in the design once the softmax divide was
    // fixed, at -4.9 ns.
    //
    // WIDEN BEFORE MULTIPLYING.
    //
    // This was `rq_mul = (a + b) * $signed({1'b0, g_rq_mult});`, relying on the
    // 64-bit assignment context to size the multiply. It does not survive
    // synthesis/simulation reliably: the product was evaluated at 32 bits and
    // wrapped, so any layer whose (acc + bias) is large enough that the Q0.16
    // multiply needs more than 32 bits produced a result of the WRONG SIGN --
    // and then saturated to the opposite rail.
    //
    // Measured in tb_top_sequencer: acc = -10,449 with bias = -583,437,254
    // gives s0 = -583,447,703. s0 * 8192 = -4.779e12, which needs 43 bits.
    // Truncated to 32 it becomes +895,938,560; >>> 22 is +213, clamped to
    // +127, where the correct answer is -128. Two of eight output channels in
    // that bench were wrong -- exactly the ones whose random bias was large.
    //
    // Both operands are now explicitly 64-bit signed, so the multiply is
    // 64-bit by construction rather than by context.
    function automatic signed [63:0] rq_mul(input signed [ACC_WIDTH-1:0] a,
                                            input signed [ACC_WIDTH-1:0] b);
        reg signed [63:0] s0, mult;
        begin
            s0   = $signed(a);          // sign-extends to 64
            s0   = s0 + $signed(b);
            mult = $signed({48'd0, g_rq_mult});   // unsigned Q0.16, so positive
            rq_mul = s0 * mult;
        end
    endfunction

    // The shift-and-clamp half, applied to the registered product.
    function automatic signed [7:0] requant_p(input signed [63:0] prod);
        reg signed [63:0] sh;
        reg signed [7:0]  r;
        begin
            sh   = prod >>> g_rq_shift;
            if      (sh >  127) r =  8'sd127;
            else if (sh < -128) r = -8'sd128;
            else                r = sh[7:0];
            // SILU is NOT applied here: it needs a table lookup and three
            // cycles, so it runs as a separate pass over acc_buf (C_SILU).
            // This used to fall through `default` for act==2, which left every
            // one of the network's 102 convs linear -- silently, because a
            // linear network still produces plausible-looking numbers.
            case (g_act)
                4'd1:    requant_p = (r < 0) ? 8'sd0 : r;   // RELU
                default: requant_p = r;                     // NONE / SILU
            endcase
        end
    endfunction

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state     <= C_IDLE;
            busy      <= 1'b0; done <= 1'b0; error <= 1'b0; fsm_state <= 5'd0;
            rq_prod   <= 64'sd0;
            rd_start  <= 1'b0; rd_addr <= 64'h0; rd_len <= 8'd0;
            wr_start  <= 1'b0; wr_addr <= 64'h0; wr_len <= 8'd0; wr_data <= 64'h0; wr_strb <= 8'h00;
            s_awvalid <= 1'b0; s_wvalid <= 1'b0; s_bready <= 1'b0;
            s_awaddr  <= 64'h0; s_wdata <= 32'h0; s_wstrb <= 4'h0;
            oc_tile   <= 16'd0; ic_tile <= 16'd0; pos <= 32'd0;
            wtile_base <= 32'd0;
            oy_base   <= 32'sd0; ox_base <= 32'sd0;
            r_idx     <= 16'd0; beat_cnt <= 16'd0; cfg_step <= 8'd0;
            bias_tile <= 16'd0; bias_tile_valid <= 1'b0;
            silu_x <= 8'sd0; silu_vin <= 1'b0;
            silu_issue <= 16'd0; silu_recv <= 16'd0;
            run_armed <= 1'b0;
            sd_busy   <= 1'b0; sd_phase <= 2'd3;
            wload_rd_done <= 1'b0; wload_rd_err <= 1'b0; rd_inflight <= 1'b0;
        end else begin
            rd_start  <= 1'b0;
            if (rd_done) rd_inflight <= 1'b0;
            wr_start  <= 1'b0;
            fsm_state <= state;


            // ---- A1 serial seed divider -------------------------------------
            // phase 0: sd_num = base, divide by k_sq  -> cc = quot, kk = rem
            // phase 2: sd_num = kk,   divide by g_k   -> kk_y = quot, kk_x = rem
            // One restoring-subtract per cycle; k_sq and g_k are both nonzero
            // (g_k is forced to 1 when the descriptor says 0).
            if (sd_busy) begin
                case (sd_phase)
                2'd0: begin
                    if (sd_num >= {16'h0, k_sq}) begin
                        sd_num  <= sd_num - {16'h0, k_sq};
                        sd_quot <= sd_quot + 16'd1;
                    end else begin
                        seed_cc  <= sd_quot;          // base / k_sq
                        seed_kk  <= sd_num[15:0];     // base % k_sq
                        sd_quot  <= 16'd0;
                        sd_phase <= 2'd2;             // now split kk into ky,kx
                    end
                end
                2'd2: begin
                    if (sd_num >= {28'h0, g_k}) begin
                        sd_num  <= sd_num - {28'h0, g_k};
                        sd_quot <= sd_quot + 16'd1;
                    end else begin
                        seed_kk_y <= sd_quot[3:0];    // kk / g_k
                        seed_kk_x <= sd_num[3:0];     // kk % g_k
                        sd_busy   <= 1'b0;
                        sd_phase  <= 2'd3;
                    end
                end
                default: sd_busy <= 1'b0;
                endcase
            end

            case (state)
            // ------------------------------------------------------------
            C_IDLE: begin
                busy <= 1'b0;
                if (start) begin
                    g_in_w  <= in_w;  g_in_h  <= in_h;  g_in_c  <= in_c;
                    g_out_w <= out_w; g_out_h <= out_h; g_out_c <= out_c;
                    g_k     <= (kernel==0) ? 4'd1 : kernel;
                    g_s     <= (stride==0) ? 4'd1 : stride;
                    g_p     <= pad;   g_act <= act_type;
                    g_rq_mult <= rq_mult; g_rq_shift <= rq_shift;
                    g_dw    <= depthwise;
                    g_act_scale <= act_scale;
                    g_src   <= src_addr; g_dst <= dst_addr;
                    g_wgt   <= wgt_addr; g_bias <= bias_addr;
                    oc_tile <= 16'd0; ic_tile <= 16'd0; pos <= 32'd0;
                    // Channel 0: base is zero for both dense and depthwise.
                    wtile_base <= 32'd0;
                    // Position (0,0): both bases are simply -pad. The PORT is
                    // used, not g_p -- g_p is being latched from it in this
                    // same cycle, so reading g_p here would take the previous
                    // layer's padding.
                    oy_base <= -$signed({28'h0, pad});
                    ox_base <= -$signed({28'h0, pad});
                    oy      <= 16'd0; ox <= 16'd0;
                    k_sq    <= ((kernel==0) ? 4'd1 : kernel) *
                               ((kernel==0) ? 4'd1 : kernel);
                    plane_sz  <= in_h  * in_w;
                    oplane_sz <= out_h * out_w;
                    req_idx   <= 16'd0;
                    bias_tile_valid <= 1'b0;
                    r_idx   <= 16'd0; r_abs <= 32'd0;
                    kk      <= 16'd0; cc <= 16'd0;
                    kk_y    <= 4'd0;  kk_x <= 4'd0;
                    // A1: tile 0's seed is the all-zero decomposition
                    // (base = 0 * ARRAY_SIZE), so it needs no divider pass --
                    // prime the cache directly and leave sd_busy low.
                    seed_r_abs <= 32'd0; seed_kk <= 16'd0; seed_cc <= 16'd0;
                    seed_kk_y  <= 4'd0;  seed_kk_x <= 4'd0;
                    sd_busy    <= 1'b0;  sd_phase  <= 2'd3;
                    wload_rd_done <= 1'b0; wload_rd_err <= 1'b0;
                    busy    <= 1'b1; done <= 1'b0; error <= 1'b0;
                    state   <= C_WLOAD;
                    beat_cnt<= 16'd0;
                end
            end

            // ------------------------------------------------------------
            // Weight tiles are emitted in exactly the loop order used here, so
            // the tile for (oc_tile, ic_tile) is at a flat sequential offset.
            C_WLOAD: begin
                // !rd_inflight, NOT !rd_start: rd_start is a one-cycle
                // pulse, so gating on it re-fires this request every cycle
                // until the first beat arrives.
                if (beat_cnt == 16'd0 && !rd_inflight) begin
                    rd_addr  <= {32'h0, g_wgt + (wtile_idx * WTILE_BYTES)};
                    rd_len   <= WTILE_BEATS[7:0];
                    rd_start <= 1'b1;
                    rd_inflight <= 1'b1;
                end
                if (rd_data_valid) begin
                    weight_buf[beat_cnt*8+0] <= rd_data[7:0];
                    weight_buf[beat_cnt*8+1] <= rd_data[15:8];
                    weight_buf[beat_cnt*8+2] <= rd_data[23:16];
                    weight_buf[beat_cnt*8+3] <= rd_data[31:24];
                    weight_buf[beat_cnt*8+4] <= rd_data[39:32];
                    weight_buf[beat_cnt*8+5] <= rd_data[47:40];
                    weight_buf[beat_cnt*8+6] <= rd_data[55:48];
                    weight_buf[beat_cnt*8+7] <= rd_data[63:56];
                    beat_cnt <= beat_cnt + 16'd1;
                end
                // A1: the seed divider for this tile was kicked off in
                // C_NEXT (or at start) and runs concurrently with the burst
                // above. Hold here until it lands, then load the cursor from
                // the cache. In practice it always finishes first -- the
                // divider is tens of cycles, the burst is hundreds -- so this
                // costs nothing, but correctness must not depend on that.
                if (rd_done) begin
                    wload_rd_done <= 1'b1;
                    wload_rd_err  <= rd_error;
                end
                // A1: the seed divider for this tile was kicked off in C_NEXT
                // (or at start) and runs concurrently with the burst above.
                // Hold here until BOTH have landed, then load the cursor from
                // the cache. In practice the divider always finishes first --
                // tens of cycles against a burst of hundreds -- but
                // correctness must not depend on that.
                if ((rd_done || wload_rd_done) && !sd_busy) begin
                    wload_rd_done <= 1'b0;
                    if (rd_error || wload_rd_err) begin
                        error <= 1'b1; wload_rd_err <= 1'b0; state <= C_ERR;
                    end else begin
                        beat_cnt <= 16'd0;
                        seed_reduction();
                        r_idx    <= 16'd0;
                        // Bias is per output channel, so it is valid for the
                        // whole oc_tile. With pos outside ic_tile the first
                        // tile comes round once per position, so reload only
                        // at the very start of an oc_tile.
                        // Reload the bias block whenever the oc_tile it
                        // belongs to changes. Depthwise advances oc_tile once
                        // per CHANNEL, so it crosses a block every ARRAY_SIZE
                        // passes, not only at the start of the layer.
                        state    <= (ic_tile == 0 && pos == 0 &&
                                     (bias_tile_valid == 1'b0 ||
                                      bias_tile != wgt_oc_tile))
                                    ? C_BLOAD : C_ACT;
                    end
                end
            end

            // ------------------------------------------------------------
            // Bias is per output channel, INT32, loaded once per oc_tile.
            C_BLOAD: begin
                if (beat_cnt == 16'd0 && !rd_inflight) begin
                    // Depthwise: oc_tile is a channel, so the ARRAY_SIZE-entry
                    // bias block it lives in starts at wgt_oc_tile.
                    rd_addr  <= {32'h0, g_bias + wgt_oc_tile*ARRAY_SIZE*4};
                    rd_len   <= (ARRAY_SIZE/2);
                    rd_start <= 1'b1;
                    rd_inflight <= 1'b1;
                end
                if (rd_data_valid) begin
                    bias_buf[beat_cnt*2+0] <= rd_data[31:0];
                    bias_buf[beat_cnt*2+1] <= rd_data[63:32];
                    beat_cnt <= beat_cnt + 16'd1;
                end
                if (rd_done) begin
                    if (rd_error) begin error <= 1'b1; state <= C_ERR; end
                    else begin
                        beat_cnt <= 16'd0;
                        // pos is NOT reset here: C_BLOAD is now reached only at
                        // the start of an oc_tile, where C_NEXT has already set
                        // pos, and clearing it would restart the position walk.
                        bias_tile       <= wgt_oc_tile;
                        bias_tile_valid <= 1'b1;
                        state           <= C_ACT;
                    end
                end
            end

            // ------------------------------------------------------------
            // Program system_top: IMG_DIM = {rows, cols} then CTRL = START.
            // rows must exceed ARRAY_SIZE for the systolic wavefront to drain
            // (Stage 3A: K=32 broke the reference tb, K=96 is the proven
            // value) -- so the row count is padded to 4*ARRAY_SIZE.
            C_CFG: begin
                case (cfg_step)
                // system_top's legacy FSM parks in S_DONE and holds sys_done
                // high "until soft_reset" (control_unit.sv:21). The conv engine
                // restarts the array once per OUTPUT POSITION, so without a
                // reset between runs only the first position ever computes:
                // every later start_pulse is ignored in S_DONE and the array
                // returns a stale (at power-up, X) result. Pulse CTRL[1] first,
                // then IMG_DIM, then CTRL[0].
                8'd0: begin
                    s_awaddr  <= 64'h00;                          // REG_CTRL
                    s_wdata   <= 32'h2;                           // soft_reset
                    s_wstrb   <= 4'hF;
                    s_awvalid <= 1'b1; s_wvalid <= 1'b1;
                    cfg_step  <= 8'd6;
                end
                8'd6: begin
                    if (s_awvalid && s_awready) s_awvalid <= 1'b0;
                    if (s_wvalid  && s_wready)  s_wvalid  <= 1'b0;
                    if (!s_awvalid && !s_wvalid) begin
                        s_bready <= 1'b1;
                        cfg_step <= 8'd7;
                    end
                end
                8'd7: if (s_bvalid && s_bready) begin
                    s_bready <= 1'b0;
                    cfg_step <= 8'd8;
                end
                // Drop soft_reset again: it is a level, not a pulse, and the
                // FSM cannot leave S_IDLE while it is held.
                8'd8: begin
                    s_awaddr  <= 64'h00;                          // REG_CTRL
                    s_wdata   <= 32'h0;
                    s_wstrb   <= 4'hF;
                    s_awvalid <= 1'b1; s_wvalid <= 1'b1;
                    cfg_step  <= 8'd9;
                end
                8'd9: begin
                    if (s_awvalid && s_awready) s_awvalid <= 1'b0;
                    if (s_wvalid  && s_wready)  s_wvalid  <= 1'b0;
                    if (!s_awvalid && !s_wvalid) begin
                        s_bready <= 1'b1;
                        cfg_step <= 8'd10;
                    end
                end
                8'd10: if (s_bvalid && s_bready) begin
                    s_bready <= 1'b0;
                    cfg_step <= 8'd11;
                end
                8'd11: begin
                    s_awaddr  <= 64'h10;                          // REG_IMG_DIM
                    s_wdata   <= {16'(4*ARRAY_SIZE), 16'(ARRAY_SIZE)};
                    s_wstrb   <= 4'hF;
                    s_awvalid <= 1'b1; s_wvalid <= 1'b1;
                    cfg_step  <= 8'd1;
                end
                8'd1: begin
                    if (s_awvalid && s_awready) s_awvalid <= 1'b0;
                    if (s_wvalid  && s_wready)  s_wvalid  <= 1'b0;
                    if (!s_awvalid && !s_wvalid) begin
                        s_bready <= 1'b1;
                        cfg_step <= 8'd2;
                    end
                end
                8'd2: if (s_bvalid && s_bready) begin
                    s_bready <= 1'b0;
                    cfg_step <= 8'd3;
                end
                8'd3: begin
                    s_awaddr  <= 64'h00;                          // REG_CTRL
                    s_wdata   <= 32'h1;                           // START
                    s_wstrb   <= 4'hF;
                    s_awvalid <= 1'b1; s_wvalid <= 1'b1;
                    cfg_step  <= 8'd4;
                end
                8'd4: begin
                    if (s_awvalid && s_awready) s_awvalid <= 1'b0;
                    if (s_wvalid  && s_wready)  s_wvalid  <= 1'b0;
                    if (!s_awvalid && !s_wvalid) begin
                        s_bready <= 1'b1;
                        cfg_step <= 8'd5;
                    end
                end
                8'd5: if (s_bvalid && s_bready) begin
                    s_bready  <= 1'b0;
                    cfg_step  <= 8'd0;
                    r_idx     <= 16'd0;
                    run_armed <= 1'b0;
                    state     <= C_RUN;
                end
                default: cfg_step <= 8'd0;
                endcase
            end

            // ------------------------------------------------------------
            // Gather the ARRAY_SIZE-element lowered activation column for the
            // current output position, one element per AXI read.
            //
            // This runs BEFORE C_CFG, not after. The array samples input_data
            // from the cycle it leaves S_IDLE, so starting it first meant it
            // loaded weights and streamed activations while this state was
            // still fetching them one slow read at a time -- the column was
            // half-built for most of the run. Single-tile layers happened to
            // survive; anything with more than one ic_tile did not.
            //
            // This runs BEFORE C_CFG, not after. The array samples input_data
            // from the cycle it leaves S_IDLE, so starting it first meant it
            // loaded weights and streamed activations while this state was
            // still fetching them one slow read at a time -- the column was
            // half-built for most of the run. Single-tile layers happened to
            // survive; anything with more than one ic_tile did not.
            C_ACT: begin
                if (!in_range) begin
                    act_col[r_idx] <= 8'd0;           // padding / past the end
                    if (r_idx == ARRAY_SIZE-1) begin
                        act_shadow[r_idx] <= 8'd0;   // this lane is padding
                        for (ri = 0; ri < ARRAY_SIZE-1; ri = ri + 1)
                            act_shadow[ri] <= act_col[ri];
                        r_idx    <= 16'd0;
                        beat_cnt <= 16'd0;
                        cfg_step <= 8'd0;
                        state    <= C_CFG;
                    end else begin
                        r_idx <= r_idx + 16'd1;
                        step_reduction();
                    end
                end else begin
                    rd_addr  <= {32'h0, g_src + src_off};
                    rd_len   <= 8'd1;
                    rd_start <= 1'b1;
                    rd_inflight <= 1'b1;
                    state    <= C_ACT_W;
                end
            end

            C_ACT_W: begin
                if (rd_data_valid) begin
                    // Byte select within the 8-byte beat.
                    act_col[r_idx] <= rd_data[{src_off[2:0], 3'b000} +: 8];
                end
                if (rd_done) begin
                    if (rd_error) begin error <= 1'b1; state <= C_ERR; end
                    else if (r_idx == ARRAY_SIZE-1) begin
                        act_shadow[r_idx] <= rd_data[{src_off[2:0], 3'b000} +: 8];
                        for (ri = 0; ri < ARRAY_SIZE-1; ri = ri + 1)
                            act_shadow[ri] <= act_col[ri];
                        r_idx    <= 16'd0;
                        beat_cnt <= 16'd0;
                        cfg_step <= 8'd0;
                        state    <= C_CFG;
                    end else begin
                        r_idx <= r_idx + 16'd1;
                        step_reduction();
                        state <= C_ACT;
                    end
                end
            end

            // ------------------------------------------------------------
            // sys_done is system_top's REGISTERED done_r, and CTRL[1]
            // (soft_reset) returns that FSM to S_IDLE without clearing done_r
            // until the following cycle. Waiting on sys_done alone therefore
            // matches the PREVIOUS run's completion and samples output_data
            // before the array has recomputed it -- which showed up as a
            // single wrong ic_tile per output position, the rest correct.
            //
            // Wait for the array to be observably running first, then for it
            // to finish.
            // Wait out the array by counting, not by handshaking.
            //
            // sys_busy/sys_done are system_top's REGISTERED busy_r/done_r, and
            // CTRL[1] (soft_reset) returns that FSM to S_IDLE without clearing
            // them until the following cycle. Either strobe therefore still
            // describes the PREVIOUS run for a cycle or two after a restart,
            // and sampling output_data on it yields the previous position's
            // result -- which appeared as one wrong ic_tile per output
            // position, with the others correct.
            //
            // The run length is fully determined: S_LOADW takes ARRAY_SIZE
            // cycles, S_WPULSE one, S_STREAM num_acts (= 4*ARRAY_SIZE, the row
            // count C_CFG programs), and the diagonal wavefront needs
            // 2*ARRAY_SIZE more to reach the bottom row. RUN_CYCLES covers all
            // of it with margin, so no strobe is consulted at all.
            // Wait for the array the same way the known-good direct bench
            // (000Working/verify_sim/tb_system_top_fix.sv, and tb_array_probe)
            // does: hold until sys_done, then let output_data settle. Counting
            // cycles instead samples at the wrong instant.
            //
            // sys_done is system_top's registered done_r and still describes
            // the PREVIOUS run for a cycle after CTRL[1] returns that FSM to
            // S_IDLE, so wait for it to fall first. C_CFG has just written
            // soft_reset, so this resolves within a few cycles.
            // Wait for the array the same way the known-good direct bench
            // (tb_array_probe) does: hold until sys_done, then let output_data
            // settle in C_ACCUM.
            //
            // sys_done is system_top's registered done_r and still describes
            // the PREVIOUS run for a cycle after CTRL[1] returns that FSM to
            // S_IDLE, so wait for it to fall first. C_CFG has just written
            // soft_reset, so this resolves within a few cycles.
            //
            // Waiting on sys_busy to RISE instead was tried and is worse: busy
            // is registered too, and on a fast restart it can still be high
            // from the previous run, so the wait completes immediately.
            C_RUN: begin
                if (!run_armed) begin
                    if (!sys_done) run_armed <= 1'b1;
                end else if (sys_done) begin
                    run_armed <= 1'b0;
                    beat_cnt  <= 16'd0;
                    state     <= C_ACCUM;
                end
            end

            // output_data lags sys_done by the register_bank pipeline; the
            // reference tb waits 4 cycles, so reuse that proven delay.
            C_ACCUM: begin
                if (beat_cnt == 16'd4) begin
                    beat_cnt <= 16'd0;
                    for (ri = 0; ri < ARRAY_SIZE; ri = ri + 1)
                        acc_buf[ri] <= (ic_tile == 0)
                                     ? $signed(output_data[ri*ACC_WIDTH +: ACC_WIDTH])
                                     : acc_buf[ri] +
                                       $signed(output_data[ri*ACC_WIDTH +: ACC_WIDTH]);
                    // is_last_ic now means "this position's reduction is
                    // complete", which is exactly when requantizing is legal.
                    state <= is_last_ic ? C_REQ : C_NEXT;
                end else beat_cnt <= beat_cnt + 16'd1;
            end

            // ------------------------------------------------------------
            // Only reached on the final ic_tile, so the reduction is complete
            // and clamping to INT8 here is the single lossy step, as intended.
            // Requantize ONE lane per cycle.
            //
            // The obvious form is a for-loop over all ARRAY_SIZE lanes, but
            // that unrolls into ARRAY_SIZE parallel 33-bit multipliers -- 24
            // DSPs, measured, and the single largest consumer outside the
            // systolic array itself. Serializing costs 24 cycles per output
            // position (negligible against the AXI reads that feed it) and
            // brings the requant path down to one multiplier.
            //
            // Only reached on the final ic_tile, so the reduction is complete
            // and clamping to INT8 here is the single lossy step, as intended.
            // Depthwise produces one lane per pass, taken from array column
            // dw_col and biased by that channel, so it requantizes into
            // acc_buf[0] and stores a single byte.
            // Multiply only: the product is registered and the shift, clamp
            // and activation happen next cycle in C_REQ_M. One lane per pass,
            // exactly as before -- the lane count is unchanged, each lane just
            // takes two cycles instead of one.
            C_REQ: begin
                rq_prod <= g_dw ? rq_mul(acc_buf[dw_col],  bias_buf[dw_col])
                                : rq_mul(acc_buf[req_idx], bias_buf[req_idx]);
                state   <= C_REQ_M;
            end

            C_REQ_M: begin
                if (g_dw) begin
                    acc_buf[0] <= {{(ACC_WIDTH-8){1'b0}}, requant_p(rq_prod)};
                    req_idx <= 16'd0;
                    state   <= (g_act == 4'd2) ? C_SILU : C_STORE;
                end else begin
                    acc_buf[req_idx] <= {{(ACC_WIDTH-8){1'b0}},
                                         requant_p(rq_prod)};
                    if (req_idx == ARRAY_SIZE-1) begin
                        req_idx <= 16'd0;
                        state   <= (g_act == 4'd2) ? C_SILU : C_STORE;
                    end else begin
                        req_idx <= req_idx + 16'd1;
                        state   <= C_REQ;
                    end
                end
            end

            // Walk the requantized lanes through silu_unit. Feeding and
            // retiring run concurrently: silu_issue presents lanes, silu_recv
            // collects them in the same order three cycles later.
            C_SILU: begin
                if (silu_issue < n_lanes) begin
                    silu_x   <= acc_buf[silu_issue][7:0];
                    silu_vin <= 1'b1;
                    silu_issue <= silu_issue + 16'd1;
                end else begin
                    silu_vin <= 1'b0;
                end

                if (silu_vout) begin
                    acc_buf[silu_recv] <= {{(ACC_WIDTH-8){1'b0}}, silu_y};
                    if (silu_recv == n_lanes - 16'd1) begin
                        silu_issue <= 16'd0;
                        silu_recv  <= 16'd0;
                        silu_vin   <= 1'b0;
                        state      <= C_STORE;
                    end else begin
                        silu_recv <= silu_recv + 16'd1;
                    end
                end
            end

            // Results are INT8, ARRAY_SIZE channels for one spatial position,
            // scattered across channel planes in CHW -- so this is ARRAY_SIZE
            // single-byte writes, not one burst. Slow but correct; the CHW->
            // tiled-layout optimization is documented as future work.
            // One INT8 per beat. The byte must be placed in the lane the
            // address selects and the strobe must enable only that lane --
            // wr_data used to sit in lane 0 with an all-ones strobe upstream,
            // so every store wrote 8 bytes and zeroed the 7 that followed it.
            C_STORE: begin
                // 8-byte ALIGNED. wr_data and wr_strb below already place the
                // byte in lane st_byte_addr[2:0] of the 64-bit beat; carrying
                // those same bits in the address applies the offset a second
                // time downstream and scatters the store. Same defect as
                // yolo_elem_engine's E_WR.
                wr_addr  <= {32'h0, st_byte_addr & 32'hFFFF_FFF8};
                wr_data  <= {56'h0, acc_buf[beat_cnt][7:0]} << {st_byte_addr[2:0], 3'b000};
                wr_strb  <= 8'h01 << st_byte_addr[2:0];
                wr_len   <= 8'd1;
                wr_start <= 1'b1;
                state    <= C_STORE_W;
            end

            C_STORE_W: begin
                if (wr_done) begin
                    if (wr_error) begin error <= 1'b1; state <= C_ERR; end
                    else if (beat_cnt == n_lanes-1) begin
                        beat_cnt <= 16'd0;
                        state    <= C_NEXT;
                    end else begin
                        beat_cnt <= beat_cnt + 16'd1;
                        state    <= C_STORE;
                    end
                end
            end

            // ------------------------------------------------------------
            // Loop nest advance: pos -> ic_tile -> oc_tile.
            // Loop nest advance: pos -> ic_tile -> oc_tile.
            //
            // oy/ox track `pos` as a raster counter rather than being recovered
            // with pos/out_w and pos%out_w, and the reduction cursor is reseeded
            // per ic_tile. That keeps every divider out of the per-element
            // address path -- see the note above the address generator.
            // Loop nest: oc_tile -> pos -> ic_tile. The reduction for ONE
            // output position runs to completion before the next position
            // starts, because acc_buf holds ARRAY_SIZE accumulators for a
            // SINGLE position.
            //
            // The original order was oc_tile -> ic_tile -> pos, which walked
            // every position for one ic_tile before advancing the tile. That
            // is what the module header describes ("accumulators live in the
            // output BRAM across the whole ic_tile loop"), but that BRAM was
            // never built: with a single-position acc_buf, the partial sum for
            // position P was added to whatever position happened to be
            // processed last, so every multi-ic_tile layer -- which is every
            // real layer in the network -- silently produced garbage.
            //
            // Holding all positions instead would need n_pos*ARRAY_SIZE INT32
            // (26 MB at 640x640x16), so the loop order is what has to change.
            // The cost is that the weight tile is re-read once per position
            // rather than once per tile; that is a bandwidth problem, and
            // bandwidth is what Phase C of the migration plan is for.
            C_NEXT: begin
                if (ic_tile < n_ic_tiles - 1) begin
                    ic_tile  <= ic_tile + 16'd1;
                    r_idx    <= 16'd0;
                    sd_start(ic_tile + 16'd1, oc_tile);
                    beat_cnt <= 16'd0;
                    state    <= C_WLOAD;
                end else if (pos < n_pos - 1) begin
                    pos      <= pos + 32'd1;
                    // Recomputed from the NEW oy/ox. These two multiplies are
                    // the only ones left in the address path, and they now
                    // happen once per output position instead of once per
                    // gathered element.
                    if (ox == g_out_w - 1) begin
                        ox <= 16'd0;
                        oy <= oy + 16'd1;
                        ox_base <= -$signed({28'h0, g_p});
                        oy_base <= $signed({16'h0, oy + 16'd1})
                                     * $signed({28'h0, g_s})
                                 - $signed({28'h0, g_p});
                    end else begin
                        ox <= ox + 16'd1;
                        ox_base <= $signed({16'h0, ox + 16'd1})
                                     * $signed({28'h0, g_s})
                                 - $signed({28'h0, g_p});
                    end
                    ic_tile  <= 16'd0;
                    r_idx    <= 16'd0;
                    sd_start(16'd0, oc_tile);
                    beat_cnt <= 16'd0;
                    state    <= C_WLOAD;
                end else if (oc_tile < n_oc_tiles - 1) begin
                    oc_tile  <= oc_tile + 16'd1;
                    // The one multiply left, and it happens once per output
                    // channel rather than once per weight-tile fetch. For
                    // depthwise, wgt_oc_tile is oc_tile/ARRAY_SIZE, so the base
                    // only moves every ARRAY_SIZE channels.
                    wtile_base <= (g_dw ? ((oc_tile + 16'd1) / ARRAY_SIZE)
                                        :  (oc_tile + 16'd1)) * n_ic_tiles;
                    ic_tile  <= 16'd0;
                    pos      <= 32'd0;
                    oy       <= 16'd0; ox <= 16'd0;
                    oy_base  <= -$signed({28'h0, g_p});
                    ox_base  <= -$signed({28'h0, g_p});
                    r_idx    <= 16'd0;
                    sd_start(16'd0, oc_tile + 16'd1);  // the channel being switched TO
                    beat_cnt <= 16'd0;
                    state    <= C_WLOAD;
                end else begin
                    state <= C_DONE;
                end
            end

            // ------------------------------------------------------------
            C_DONE: begin
                busy  <= 1'b0;
                done  <= 1'b1;
                state <= C_IDLE;
            end

            C_ERR: begin
                busy  <= 1'b0;
                done  <= 1'b1;
                error <= 1'b1;
                state <= C_IDLE;
            end

            default: state <= C_IDLE;
            endcase

            if (state != C_IDLE && done) done <= 1'b0;
        end
    end

endmodule
