// -----------------------------------------------------------------------------
// GENERATED by qrts/tools/port_rtl.py -- DO NOT EDIT THIS COPY.
//
// Source: DVCFinal/rtl/yolo_descriptor_pkg.svh
//
// Edit the source and re-run the porter:
//     python qrts/tools/port_rtl.py
//
// Xilinx synthesis attributes have been rewritten for Quartus. See the porter
// for what is rewritten and what still needs hand work.
// -----------------------------------------------------------------------------
// =============================================================================
// yolo_descriptor_pkg.svh — the layer-descriptor ISA
//
// This header is the single contract between three things that must agree
// byte-for-byte or the accelerator walks garbage:
//
//   tools/export_yolo26n.py   writes descriptors  (offline, build host)
//   rtl/yolo_layer_sequencer.sv reads descriptors (hardware, runtime)
//   sw/yolo_model.h           mirrors the layout  (C, for the loader/checker)
//
// A descriptor is a fixed 64-byte record so the sequencer can fetch one with a
// single 8-beat AXI burst and index the table with a shift instead of a
// multiply. Fixed size costs a little DRAM (~100 layers * 64 B = 6.4 KB) and
// buys a much simpler fetch FSM -- the right trade at this scale.
//
// Everything is little-endian, matching both RISC-V and the AXI byte lanes.
//
// ---------------------------------------------------------------------------
// Descriptor layout (offsets in bytes)
// ---------------------------------------------------------------------------
//   0x00  [31:0]  op            LAYER_OP_*
//   0x04  [31:0]  flags         LAYER_F_*
//   0x08  [31:0]  src0_addr     primary input feature map (byte address)
//   0x0C  [31:0]  src1_addr     second input (Concat/Add), else 0
//   0x10  [31:0]  dst_addr      output feature map
//   0x14  [31:0]  wgt_addr      INT8 weight tile base
//   0x18  [31:0]  bias_addr     INT32 bias vector base
//   0x1C  [15:0]  in_w          input width
//         [31:16] in_h          input height
//   0x20  [15:0]  in_c          input channels  (src0)
//         [31:16] in_c1         input channels  (src1, Concat only)
//   0x24  [15:0]  out_w         output width
//         [31:16] out_h         output height
//   0x28  [15:0]  out_c         output channels
//         [31:16] groups        conv groups (1 = dense, in_c = depthwise)
//   0x2C  [3:0]   kernel        1,3,5
//         [7:4]   stride
//         [11:8]  pad
//         [15:12] act_type      0 NONE, 1 RELU, 2 SILU
//         [31:16] requant_mult  unsigned Q0.16 multiplier
//   0x30  [4:0]   requant_shift
//         [15:5]  reserved
//         [31:16] act_scale   codes per unit for this layer's output, Q8.8.
//                             Only meaningful when act_type is SILU: the INT8
//                             code -> real value mapping differs per layer, so
//                             the activation cannot be one fixed table.
//   0x34  [31:0]  aux0          op-specific (see below)
//   0x38  [31:0]  aux1          op-specific
//   0x3C  [31:0]  next_off      byte offset to next descriptor, 0 = end of list
//
// aux0/aux1 by op:
//   MAXPOOL   aux0 = pool window (5 for SPPF)
//   UPSAMPLE  aux0 = scale factor (2)
//   CONCAT    aux0 = src0 channel count already in in_c; aux1 unused
//   DETECT    aux0 = stride of this pyramid level (8/16/32)
//             aux1 = address of the 4-entry anchor/scale block
//   SPLIT     aux0 = channel offset into src0, aux1 = channel count
// =============================================================================
`ifndef YOLO_DESCRIPTOR_PKG_SVH
`define YOLO_DESCRIPTOR_PKG_SVH

localparam integer DESC_BYTES     = 64;
localparam integer DESC_BEATS     = DESC_BYTES/8;   // 8 beats on the 64-bit bus
localparam integer DESC_SHIFT     = 6;              // log2(DESC_BYTES)

// ---- ops ------------------------------------------------------------------
// Deliberately small. Everything YOLO26n needs decomposes into these; the
// exporter does the decomposition so the hardware never parses a graph.
localparam [31:0] LAYER_OP_END      = 32'd0;   // terminate the list
localparam [31:0] LAYER_OP_CONV     = 32'd1;   // conv + bias + requant + act
localparam [31:0] LAYER_OP_ADD      = 32'd2;   // residual add (INT8 in/out)
localparam [31:0] LAYER_OP_CONCAT   = 32'd3;   // channel concat, src0 then src1
localparam [31:0] LAYER_OP_UPSAMPLE = 32'd4;   // nearest, factor aux0
localparam [31:0] LAYER_OP_MAXPOOL  = 32'd5;   // SPPF, window aux0, stride 1
localparam [31:0] LAYER_OP_SPLIT    = 32'd6;   // channel slice (C3k2/C2PSA)
localparam [31:0] LAYER_OP_SOFTMAX  = 32'd7;   // attention rows (C2PSA)
localparam [31:0] LAYER_OP_DETECT   = 32'd8;   // decode one pyramid level
localparam [31:0] LAYER_OP_TOPK     = 32'd9;   // final box selection, no NMS

// ---- flags ----------------------------------------------------------------
localparam [31:0] LAYER_F_DEPTHWISE = 32'h0000_0001;
localparam [31:0] LAYER_F_BIAS      = 32'h0000_0002;  // bias_addr valid
localparam [31:0] LAYER_F_LAST      = 32'h0000_0004;  // last descriptor
localparam [31:0] LAYER_F_IRQ       = 32'h0000_0008;  // raise done irq here

// ---- activation encodings (match vector_unit.sv) --------------------------
localparam [3:0] ACT_NONE = 4'd0;
localparam [3:0] ACT_RELU = 4'd1;
localparam [3:0] ACT_SILU = 4'd2;

// ---- descriptor field extraction ------------------------------------------
// The sequencer holds the fetched descriptor as 16 32-bit words; these keep the
// slicing in one place so a layout change cannot drift between call sites.
`define DESC_OP(d)            (d[0])
`define DESC_FLAGS(d)         (d[1])
`define DESC_SRC0(d)          (d[2])
`define DESC_SRC1(d)          (d[3])
`define DESC_DST(d)           (d[4])
`define DESC_WGT(d)           (d[5])
`define DESC_BIAS(d)          (d[6])
`define DESC_IN_W(d)          (d[7][15:0])
`define DESC_IN_H(d)          (d[7][31:16])
`define DESC_IN_C(d)          (d[8][15:0])
`define DESC_IN_C1(d)         (d[8][31:16])
`define DESC_OUT_W(d)         (d[9][15:0])
`define DESC_OUT_H(d)         (d[9][31:16])
`define DESC_OUT_C(d)         (d[10][15:0])
`define DESC_GROUPS(d)        (d[10][31:16])
`define DESC_KERNEL(d)        (d[11][3:0])
`define DESC_STRIDE(d)        (d[11][7:4])
`define DESC_PAD(d)           (d[11][11:8])
`define DESC_ACT(d)           (d[11][15:12])
`define DESC_RQ_MULT(d)       (d[11][31:16])
`define DESC_RQ_SHIFT(d)      (d[12][4:0])
`define DESC_ACT_SCALE(d)     (d[12][31:16])
`define DESC_AUX0(d)          (d[13])
`define DESC_AUX1(d)          (d[14])
`define DESC_NEXT(d)          (d[15])

`endif
