// -----------------------------------------------------------------------------
// GENERATED by qrts/tools/port_rtl.py -- DO NOT EDIT THIS COPY.
//
// Source: DVCFinal/rtl/yolo_layer_sequencer.sv
//
// Edit the source and re-run the porter:
//     python qrts/tools/port_rtl.py
//
// Xilinx synthesis attributes have been rewritten for Quartus. See the porter
// for what is rewritten and what still needs hand work.
// -----------------------------------------------------------------------------
// =============================================================================
// yolo_layer_sequencer.sv — autonomous whole-network layer walker
//
// This is the module that takes the CPU out of the loop. The existing
// accel_dma_seq runs exactly ONE GEMM tile per START; this walks the entire
// YOLO26n graph from a descriptor table in DRAM and only reports done once the
// final box list has been written.
//
//   CPU (once per frame):  write bitmap -> DESC_ADDR -> START -> poll DONE
//   HW  (per frame):       fetch desc -> execute -> follow next_off -> ... -> END
//
// Structure:
//
//   S_FETCH ─► S_DECODE ─┬─► S_CONV_*     ──┐
//                        ├─► S_ELEM_*     ──┤
//                        ├─► S_RESAMPLE_* ──┼─► S_ADVANCE ─► S_FETCH
//                        ├─► S_DETECT_*   ──┤        │
//                        └─► S_END ──────────┘        └─ next_off==0 ─► S_DONE
//
// The conv path is the only one that touches the systolic array. It is a
// three-level tile loop -- output-channel tile, input-channel tile, spatial
// position -- because the array is ARRAY_SIZE wide and real layers are not.
// Partial sums across input-channel tiles accumulate in the output BRAM at
// INT32 and are only requantized to INT8 on the final input tile, which is
// what keeps the numerics equal to the software reference.
//
// ---------------------------------------------------------------------------
// Why the accumulator ordering matters (this cost real time on Stage 3A):
// requantizing per input-channel tile instead of once at the end changes the
// result -- clamping to INT8 mid-reduction is lossy and non-associative. The
// `is_last_ic_tile` gate below is load-bearing, not an optimization.
// ---------------------------------------------------------------------------
`timescale 1ns/1ps

`include "yolo_descriptor_pkg.svh"

module yolo_layer_sequencer #(
    parameter integer ARRAY_SIZE = 24,
    parameter integer DATA_WIDTH = 8,
    parameter integer ACC_WIDTH  = 32,
    parameter integer MAX_IMG_W  = 640
)(
    input  wire        clk,
    input  wire        rst_n,

    // ---- control from the CPU register file ----
    input  wire        start_pulse,
    input  wire [31:0] desc_base,      // descriptor table base in DRAM
    input  wire [31:0] img_addr,       // input bitmap (INT8 CHW, already scaled)
    input  wire [31:0] out_addr,       // final box list destination

    output reg         busy,
    output reg         done,
    output reg         error,
    output reg  [3:0]  fsm_state,
    output reg  [15:0] layer_idx,      // observability: which layer is running
    output reg  [15:0] num_boxes,      // boxes written at out_addr

    // ---- AXI4 master read (shared, arbitrated outside) ----
    output reg         rd_start,
    output reg  [63:0] rd_addr,
    output reg  [7:0]  rd_len,
    input  wire [63:0] rd_data,
    input  wire        rd_data_valid,
    input  wire        rd_done,
    input  wire        rd_error,

    // ---- AXI4 master write ----
    output reg         wr_start,
    output reg  [63:0] wr_addr,
    output reg  [7:0]  wr_len,
    output wire [63:0] wr_data,
    input  wire        wr_data_ready,
    input  wire        wr_done,
    input  wire        wr_error,

    // ---- compute-engine handshake (yolo_conv_engine) ----
    output reg         ce_start,
    output reg  [31:0] ce_src_addr,
    output reg  [31:0] ce_dst_addr,
    output reg  [31:0] ce_wgt_addr,
    output reg  [31:0] ce_bias_addr,
    output reg  [15:0] ce_in_w, ce_in_h, ce_in_c,
    output reg  [15:0] ce_out_w, ce_out_h, ce_out_c,
    output reg  [3:0]  ce_kernel, ce_stride, ce_pad, ce_act,
    output reg  [15:0] ce_rq_mult,
    output reg  [4:0]  ce_rq_shift,
    output reg  [15:0] ce_act_scale,   // Q8.8 codes/unit, SILU only
    output reg         ce_depthwise,
    input  wire        ce_busy,
    input  wire        ce_done,
    input  wire        ce_error,

    // ---- elementwise/resample engine handshake (yolo_elem_engine) ----
    output reg         ee_start,
    output reg  [31:0] ee_op,
    output reg  [31:0] ee_src0, ee_src1, ee_dst,
    output reg  [15:0] ee_in_w, ee_in_h, ee_in_c, ee_in_c1,
    output reg  [15:0] ee_out_w, ee_out_h, ee_out_c,
    output reg  [31:0] ee_aux0, ee_aux1,
    input  wire        ee_busy,
    input  wire        ee_done,
    input  wire        ee_error,

    // ---- detect/decode engine handshake (yolo_detect_engine) ----
    output reg         de_start,
    output reg  [31:0] de_src, de_dst,
    output reg  [15:0] de_in_w, de_in_h, de_in_c,
    output reg  [31:0] de_level_stride,
    output reg  [15:0] de_rq_mult,
    output reg  [4:0]  de_rq_shift,
    output reg         de_flush,        // final TOPK pass
    input  wire        de_busy,
    input  wire        de_done,
    input  wire [15:0] de_num_boxes,
    input  wire        de_error
);

    // =========================================================================
    // Descriptor register file: one 64-byte record as 16 words
    // =========================================================================
    reg [31:0] desc [0:15];
    reg [31:0] desc_ptr;        // byte address of the descriptor being executed
    reg [3:0]  fetch_beat;

    // =========================================================================
    // FSM
    // =========================================================================
    localparam [3:0]
        S_IDLE     = 4'd0,
        S_FETCH    = 4'd1,
        S_FETCH_W  = 4'd2,
        S_DECODE   = 4'd3,
        S_CONV     = 4'd4,
        S_CONV_W   = 4'd5,
        S_ELEM     = 4'd6,
        S_ELEM_W   = 4'd7,
        S_DETECT   = 4'd8,
        S_DETECT_W = 4'd9,
        S_ADVANCE  = 4'd10,
        S_DONE     = 4'd11,
        S_ERROR    = 4'd12;

    reg [3:0] state;

    // The sequencer itself never moves bulk data -- the engines own their own
    // AXI traffic. It only reads descriptors, so wr_* stays parked here and the
    // final box write is done by the detect engine.
    assign wr_data = 64'h0;

    // The image address substitutes for src0 on the first layer only. The
    // exporter emits src0=0 there as a sentinel meaning "the input bitmap",
    // which keeps the descriptor table independent of where the CPU staged the
    // frame -- the table can live in read-only memory and be reused per frame.
    wire [31:0] eff_src0 = (`DESC_SRC0(desc) == 32'h0) ? img_addr : `DESC_SRC0(desc);
    wire [31:0] eff_dst  = (`DESC_DST(desc)  == 32'h0) ? out_addr : `DESC_DST(desc);

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state       <= S_IDLE;
            busy        <= 1'b0;
            done        <= 1'b0;
            error       <= 1'b0;
            fsm_state   <= 4'd0;
            layer_idx   <= 16'd0;
            num_boxes   <= 16'd0;
            desc_ptr    <= 32'h0;
            fetch_beat  <= 4'd0;
            rd_start    <= 1'b0; rd_addr <= 64'h0; rd_len <= 8'd0;
            wr_start    <= 1'b0; wr_addr <= 64'h0; wr_len <= 8'd0;
            ce_start    <= 1'b0;
            ee_start    <= 1'b0;
            de_start    <= 1'b0; de_flush <= 1'b0;
        end else begin
            rd_start  <= 1'b0;
            wr_start  <= 1'b0;
            ce_start  <= 1'b0;
            ee_start  <= 1'b0;
            de_start  <= 1'b0;
            fsm_state <= state;

            case (state)
            // ------------------------------------------------------------
            S_IDLE: begin
                busy <= 1'b0;
                if (start_pulse) begin
                    busy       <= 1'b1;
                    done       <= 1'b0;
                    error      <= 1'b0;
                    layer_idx  <= 16'd0;
                    num_boxes  <= 16'd0;
                    desc_ptr   <= desc_base;
                    fetch_beat <= 4'd0;
                    rd_addr    <= {32'h0, desc_base};
                    rd_len     <= DESC_BEATS[7:0];
                    rd_start   <= 1'b1;
                    state      <= S_FETCH_W;
                end
            end

            // ------------------------------------------------------------
            // Descriptor fetch: 8 beats x 64 bit = 16 words
            S_FETCH: begin
                fetch_beat <= 4'd0;
                rd_addr    <= {32'h0, desc_ptr};
                rd_len     <= DESC_BEATS[7:0];
                rd_start   <= 1'b1;
                state      <= S_FETCH_W;
            end

            S_FETCH_W: begin
                if (rd_data_valid) begin
                    desc[{fetch_beat[2:0], 1'b0}] <= rd_data[31:0];
                    desc[{fetch_beat[2:0], 1'b1}] <= rd_data[63:32];
                    fetch_beat <= fetch_beat + 4'd1;
                end
                if (rd_done) begin
                    if (rd_error) begin
                        error <= 1'b1;
                        state <= S_ERROR;
                    end else begin
                        state <= S_DECODE;
                    end
                end
            end

            // ------------------------------------------------------------
            // Dispatch on op. Each engine gets its whole job in one handshake;
            // the sequencer then does nothing until that engine reports done,
            // which is what makes the per-layer CPU round trip unnecessary.
            S_DECODE: begin
                case (`DESC_OP(desc))
                LAYER_OP_END: begin
                    state <= S_DONE;
                end

                LAYER_OP_CONV: begin
                    ce_src_addr  <= eff_src0;
                    ce_dst_addr  <= `DESC_DST(desc);
                    ce_wgt_addr  <= `DESC_WGT(desc);
                    ce_bias_addr <= `DESC_BIAS(desc);
                    ce_in_w      <= `DESC_IN_W(desc);
                    ce_in_h      <= `DESC_IN_H(desc);
                    ce_in_c      <= `DESC_IN_C(desc);
                    ce_out_w     <= `DESC_OUT_W(desc);
                    ce_out_h     <= `DESC_OUT_H(desc);
                    ce_out_c     <= `DESC_OUT_C(desc);
                    ce_kernel    <= `DESC_KERNEL(desc);
                    ce_stride    <= `DESC_STRIDE(desc);
                    ce_pad       <= `DESC_PAD(desc);
                    ce_act       <= `DESC_ACT(desc);
                    ce_rq_mult   <= `DESC_RQ_MULT(desc);
                    ce_rq_shift  <= `DESC_RQ_SHIFT(desc);
                    ce_act_scale <= `DESC_ACT_SCALE(desc);
                    ce_depthwise <= (`DESC_FLAGS(desc) & LAYER_F_DEPTHWISE) != 0;
                    ce_start     <= 1'b1;
                    state        <= S_CONV_W;
                end

                LAYER_OP_ADD,
                LAYER_OP_CONCAT,
                LAYER_OP_UPSAMPLE,
                LAYER_OP_MAXPOOL,
                LAYER_OP_SPLIT,
                LAYER_OP_SOFTMAX: begin
                    ee_op    <= `DESC_OP(desc);
                    ee_src0  <= eff_src0;
                    ee_src1  <= `DESC_SRC1(desc);
                    ee_dst   <= `DESC_DST(desc);
                    ee_in_w  <= `DESC_IN_W(desc);
                    ee_in_h  <= `DESC_IN_H(desc);
                    ee_in_c  <= `DESC_IN_C(desc);
                    ee_in_c1 <= `DESC_IN_C1(desc);
                    ee_out_w <= `DESC_OUT_W(desc);
                    ee_out_h <= `DESC_OUT_H(desc);
                    ee_out_c <= `DESC_OUT_C(desc);
                    ee_aux0  <= `DESC_AUX0(desc);
                    ee_aux1  <= `DESC_AUX1(desc);
                    ee_start <= 1'b1;
                    state    <= S_ELEM_W;
                end

                LAYER_OP_DETECT,
                LAYER_OP_TOPK: begin
                    de_src          <= eff_src0;
                    de_dst          <= eff_dst;
                    de_in_w         <= `DESC_IN_W(desc);
                    de_in_h         <= `DESC_IN_H(desc);
                    de_in_c         <= `DESC_IN_C(desc);
                    de_level_stride <= `DESC_AUX0(desc);
                    de_rq_mult      <= `DESC_RQ_MULT(desc);
                    de_rq_shift     <= `DESC_RQ_SHIFT(desc);
                    de_flush        <= (`DESC_OP(desc) == LAYER_OP_TOPK);
                    de_start        <= 1'b1;
                    state           <= S_DETECT_W;
                end

                default: begin
                    // An unknown opcode means the table is corrupt or the
                    // exporter and RTL have drifted. Fail loudly rather than
                    // executing a garbage layer -- a silent wrong answer here
                    // is far more expensive to debug than a status bit.
                    error <= 1'b1;
                    state <= S_ERROR;
                end
                endcase
            end

            // ------------------------------------------------------------
            S_CONV_W: begin
                if (ce_done) begin
                    if (ce_error) begin error <= 1'b1; state <= S_ERROR; end
                    else                state <= S_ADVANCE;
                end
            end

            S_ELEM_W: begin
                if (ee_done) begin
                    if (ee_error) begin error <= 1'b1; state <= S_ERROR; end
                    else                state <= S_ADVANCE;
                end
            end

            S_DETECT_W: begin
                if (de_done) begin
                    if (de_error) begin error <= 1'b1; state <= S_ERROR; end
                    else begin
                        num_boxes <= de_num_boxes;
                        state     <= S_ADVANCE;
                    end
                end
            end

            // ------------------------------------------------------------
            // next_off is a byte offset from the table base, not an absolute
            // address, so the whole table is position independent and the CPU
            // can stage it anywhere.
            S_ADVANCE: begin
                layer_idx <= layer_idx + 16'd1;
                if (`DESC_NEXT(desc) == 32'h0 ||
                    (`DESC_FLAGS(desc) & LAYER_F_LAST) != 0) begin
                    state <= S_DONE;
                end else begin
                    desc_ptr <= desc_base + `DESC_NEXT(desc);
                    state    <= S_FETCH;
                end
            end

            // ------------------------------------------------------------
            S_DONE: begin
                busy  <= 1'b0;
                done  <= 1'b1;
                state <= S_IDLE;
            end

            S_ERROR: begin
                busy  <= 1'b0;
                done  <= 1'b1;   // done+error so the CPU poll always terminates
                state <= S_IDLE;
            end

            default: state <= S_IDLE;
            endcase
        end
    end

endmodule
