// -----------------------------------------------------------------------------
// GENERATED by qrts/tools/port_rtl.py -- DO NOT EDIT THIS COPY.
//
// Source: DVCFinal/rtl/yolo_elem_engine.sv
//
// Edit the source and re-run the porter:
//     python qrts/tools/port_rtl.py
//
// Xilinx synthesis attributes have been rewritten for Quartus. See the porter
// for what is rewritten and what still needs hand work.
// -----------------------------------------------------------------------------
// =============================================================================
// yolo_elem_engine.sv — non-GEMM layer ops
//
// Everything in YOLO26n that is not a convolution and not the detect head:
// residual Add, channel Concat, nearest Upsample, SPPF MaxPool, the channel
// Split that C3k2/C2PSA use, and the attention Softmax in C2PSA.
//
// These are all memory-movement or elementwise ops. None of them touch the
// systolic array, which is what lets the sequencer keep the array loaded with
// the next weight tile while these run -- though that overlap is NOT exploited
// here (the sequencer serializes engines); it is noted in docs as future work.
//
// All feature maps are INT8 CHW: element (c,y,x) at c*H*W + y*W + x.
//
// A note on Concat: it is implemented as two block copies rather than a
// pointer trick because the conv engine's address generator assumes a
// contiguous CHW map. Making Concat free would require the conv engine to walk
// a scatter list, which is a much larger change for a layer that is a small
// fraction of the frame time.
// =============================================================================
`timescale 1ns/1ps

`include "yolo_descriptor_pkg.svh"

module yolo_elem_engine #(
    parameter integer DATA_WIDTH = 8
)(
    input  wire        clk,
    input  wire        rst_n,

    // ---- job from the sequencer ----
    input  wire        start,
    input  wire [31:0] op,
    input  wire [31:0] src0, src1, dst,
    input  wire [15:0] in_w, in_h, in_c, in_c1,
    input  wire [15:0] out_w, out_h, out_c,
    input  wire [31:0] aux0, aux1,

    output reg         busy,
    output reg         done,
    output reg         error,
    // 5 bits, not 4: the state encoding outgrew a nibble when the softmax
    // normalisation became a serial divide. Left at 4, E_SM_DIV (16) would be
    // truncated to 0 and the debug register would report E_IDLE while the
    // engine was mid-divide.
    output reg  [4:0]  fsm_state,

    // ---- AXI4 master read ----
    output reg         rd_start,
    output reg  [63:0] rd_addr,
    output reg  [7:0]  rd_len,
    input  wire [63:0] rd_data,
    input  wire        rd_data_valid,
    input  wire        rd_done,
    input  wire        rd_error,

    // ---- AXI4 master write ----
    output reg         wr_start,
    output reg  [63:0] wr_addr,
    output reg  [7:0]  wr_len,
    output reg  [63:0] wr_data,
    output reg  [7:0]  wr_strb,
    input  wire        wr_data_ready,
    input  wire        wr_done,
    input  wire        wr_error
);

    // Latched job
    reg [31:0] g_op, g_src0, g_src1, g_dst, g_aux0, g_aux1;
    reg [15:0] g_in_w, g_in_h, g_in_c, g_in_c1, g_out_w, g_out_h, g_out_c;

    // Iteration state: a flat output element counter, decoded per op.
    reg [31:0] idx, total;

    // Destination byte address of the element being written, used by E_WR for
    // both the data lane shift and the strobe.
    wire [31:0] e_dst_addr = g_dst + idx;
    reg signed [15:0] acc8;          // running max for pooling
    reg [7:0]  operand_a, operand_b;
    reg [3:0]  sub;                  // sub-step within one output element


    // -----------------------------------------------------------------------
    // Output position, as an odometer rather than a division.
    //
    // These used to be  oc = idx/(out_h*out_w),  oy = (idx%..)/out_w,  etc.
    // `idx` only ever advances by one, so the quotients are a plain counter
    // and the dividers bought nothing. What they cost was everything: the
    // divides and the variable multiplies below them synthesised into a
    // 585-level, 509-CARRY4 ripple whose worst path measured 109.8 ns against
    // a 20 ns clock -- WNS -89.9 across 17005 endpoints, i.e. the entire
    // timing failure of the design. Keep this an odometer.
    // -----------------------------------------------------------------------
    reg [15:0] oc, oy, ox;

    // oc*in_h*in_w, maintained incrementally: a variable three-way multiply in
    // the address path is the other half of the same problem.
    reg [31:0] oc_plane;     // oc      * in_h * in_w
    reg [31:0] plane_sz;     // in_h    * in_w,  latched once per job
    reg [31:0] cat_plane;    // cat_c   * plane_sz
    reg [31:0] spl_plane;    // (aux0+oc)*plane_sz
    reg [31:0] oy_row;       // oy      * in_w

    // -----------------------------------------------------------------------
    // SOFTMAX state
    //
    // Softmax normalises across CHANNELS at one spatial position:
    //     y[c] = exp(x[c] - max) / sum_c exp(x[c] - max)
    //
    // That needs two passes over the channel axis before a single output byte
    // can be written, so it cannot use the one-element-in/one-element-out loop
    // the other ops share. This walks positions in the outer loop and channels
    // twice in the inner one.
    //
    // Until now LAYER_OP_SOFTMAX fell through `default` and copied its input.
    // Both C2PSA attention blocks therefore had no attention at all -- the
    // scores went straight through unnormalised, which is a plausible-looking
    // wrong answer rather than a failure.
    //
    // Subtracting the max before exp is not an optimisation: without it
    // exp overflows for any positive score, and with INT8 inputs the whole
    // row can be positive.
    // -----------------------------------------------------------------------

    // exp(-d/16) in Q0.8 for d = 0..255, i.e. arguments 0 down to -16.
    // Everything below -16 is < 1e-7 and rounds to zero at this precision.
    // Loaded from a generated file: Quartus will not fold $exp at elaboration
    // (the same reason silu_unit reads a table instead of building one).
    (* romstyle = "M9K" *) reg [7:0] exp_rom [0:255];
    initial $readmemh("softmax_exp.mem", exp_rom);

    reg [15:0] sm_pos;        // spatial position being normalised
    reg [15:0] sm_ch;         // channel within the position
    reg signed [7:0] sm_max;  // running max over the channel axis
    reg [23:0] sm_sum;        // sum of exp terms, Q0.8 accumulated
    reg [7:0]  sm_exp;        // exp term for the channel in flight

    // Serial divider for the softmax normalisation. See E_SM_DIV.
    reg [23:0] sd_num, sd_den, sd_q, sd_rem;
    reg [4:0]  sd_i;
    reg        sd_busy;
    reg [23:0] sd_rem_n;
    reg [1:0]  sm_phase;      // 0 = find max, 1 = sum, 2 = emit

    // Channel stride at a fixed position: CHW, so consecutive channels are a
    // whole plane apart.
    wire [31:0] sm_src_off = sm_ch * plane_sz + {16'h0, sm_pos};
    wire [31:0] sm_dst_off = sm_ch * plane_sz + {16'h0, sm_pos};

    // exp(x - max) with both in INT8 codes. The table steps by 1/16 of a code,
    // so the index is 16*(max - x), saturating at the bottom of the table.
    wire [15:0] sm_delta16 = ({8'h0, sm_max} - {8'h0, operand_a}) << 4;
    wire [7:0]  sm_idx = (sm_delta16 > 16'd255) ? 8'd255 : sm_delta16[7:0];

    // ---- per-op source address for the current output element --------------
    // UPSAMPLE: nearest neighbour, source pixel is (oy/f, ox/f). The factor is
    // 2 for every upsample in yolo26n, so this is a shift, not a divide.
    wire [15:0] up_f  = g_aux0[15:0];
    reg  [4:0]  up_sh;                    // log2(up_f), latched at job start
    wire [15:0] up_y  = oy >> up_sh;
    wire [15:0] up_x  = ox >> up_sh;
    wire [31:0] up_off = oc_plane + up_y*g_in_w + up_x;

    // CONCAT: channels [0,in_c) come from src0, [in_c, in_c+in_c1) from src1.
    wire       cat_hi   = (oc >= g_in_c);
    wire [31:0] cat_off = cat_plane + oy_row + ox;
    wire [31:0] cat_base= cat_hi ? g_src1 : g_src0;

    // SPLIT: a channel window of src0 starting at aux0, aux1 channels wide.
    wire [31:0] spl_off = spl_plane + oy_row + ox;

    // ADD: same position in both maps.
    wire [31:0] add_off = oc_plane + oy_row + ox;

    // MAXPOOL: SPPF uses window aux0, stride 1, pad aux0/2 so H,W are preserved.
    // pk walks 0..pool_k*pool_k-1 one step at a time, so its row/column are a
    // second odometer -- same reason as above.
    reg  [3:0]  pk;                       // index within the pool window
    reg  [3:0]  pk_y, pk_x;               // pk / pool_k, pk % pool_k
    wire [15:0] pool_k = g_aux0[15:0];
    wire [15:0] pool_p = pool_k >> 1;
    wire signed [31:0] py = $signed({16'h0, oy}) - $signed({16'h0, pool_p})
                          + $signed({28'h0, pk_y});
    wire signed [31:0] px = $signed({16'h0, ox}) - $signed({16'h0, pool_p})
                          + $signed({28'h0, pk_x});
    wire pool_in_range = (py >= 0) && (py < $signed({16'h0, g_in_h})) &&
                         (px >= 0) && (px < $signed({16'h0, g_in_w}));
    wire [31:0] pool_off = oc_plane + $unsigned(py)*g_in_w + $unsigned(px);

    // =========================================================================
    // FSM
    // =========================================================================
    localparam [4:0]
        E_IDLE   = 5'd0,
        E_RD_A   = 5'd1,
        E_RD_AW  = 5'd2,
        E_RD_B   = 5'd3,
        E_RD_BW  = 5'd4,
        E_COMPUTE= 5'd5,
        E_WR     = 5'd6,
        E_WR_W   = 5'd7,
        E_NEXT   = 5'd8,
        E_DONE   = 5'd9,
        E_ERR    = 5'd10,
        E_WR_GO  = 5'd11,   // wr_data settled, assert wr_start
        E_SM_RD  = 5'd12,   // softmax: fetch one channel
        E_SM_RDW = 5'd13,
        E_SM_STEP= 5'd14,   // softmax: fold it into max / sum, or emit
        E_SM_WRW = 5'd15,
        E_SM_DIV = 5'd16;   // serial divide for the softmax normalisation

    reg [4:0] state;

    // Address of operand A for the current op/element.
    reg [31:0] a_base, a_off;
    always @(*) begin
        a_base = g_src0;
        a_off  = add_off;
        case (g_op)
            LAYER_OP_UPSAMPLE: begin a_base = g_src0; a_off = up_off;  end
            LAYER_OP_CONCAT:   begin a_base = cat_base; a_off = cat_off; end
            LAYER_OP_SPLIT:    begin a_base = g_src0; a_off = spl_off; end
            LAYER_OP_MAXPOOL:  begin a_base = g_src0; a_off = pool_off; end
            default:           begin a_base = g_src0; a_off = add_off; end
        endcase
    end

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state    <= E_IDLE;
            busy     <= 1'b0; done <= 1'b0; error <= 1'b0; fsm_state <= 5'd0;
            rd_start <= 1'b0; rd_addr <= 64'h0; rd_len <= 8'd0;
            wr_start <= 1'b0; wr_addr <= 64'h0; wr_len <= 8'd0; wr_data <= 64'h0; wr_strb <= 8'h00;
            idx      <= 32'd0; total <= 32'd0; pk <= 4'd0; sub <= 4'd0;
            sm_pos <= 16'd0; sm_ch <= 16'd0; sm_max <= 8'sd0;
            sm_sum <= 24'd0; sm_exp <= 8'd0; sm_phase <= 2'd0;
            sd_num <= 24'd0; sd_den <= 24'd0; sd_q <= 24'd0;
            sd_rem <= 24'd0; sd_i <= 5'd0; sd_busy <= 1'b0;
            acc8     <= 16'sh0;
            oc       <= 16'd0; oy <= 16'd0; ox <= 16'd0;
            pk_y     <= 4'd0;  pk_x <= 4'd0;
            oc_plane <= 32'd0; plane_sz <= 32'd0;
            cat_plane<= 32'd0; spl_plane<= 32'd0; oy_row <= 32'd0;
            up_sh    <= 5'd0;
        end else begin
            rd_start  <= 1'b0;
            wr_start  <= 1'b0;
            fsm_state <= state;

            case (state)
            // ------------------------------------------------------------
            E_IDLE: begin
                busy <= 1'b0;
                if (start) begin
                    g_op    <= op;
                    g_src0  <= src0; g_src1 <= src1; g_dst <= dst;
                    g_in_w  <= in_w; g_in_h <= in_h; g_in_c <= in_c;
                    g_in_c1 <= in_c1;
                    g_out_w <= out_w; g_out_h <= out_h; g_out_c <= out_c;
                    g_aux0  <= aux0; g_aux1 <= aux1;
                    total   <= out_w * out_h * out_c;
                    sm_pos   <= 16'd0; sm_ch <= 16'd0;
                    sm_sum   <= 24'd0; sm_phase <= 2'd0;
                    sm_max   <= 8'sd0;
                    idx     <= 32'd0;
                    pk      <= 4'd0;
                    // Odometer starts at (0,0,0); every derived product is
                    // therefore zero except the per-job constants.
                    oc      <= 16'd0; oy <= 16'd0; ox <= 16'd0;
                    pk_y    <= 4'd0;  pk_x <= 4'd0;
                    oc_plane<= 32'd0; oy_row <= 32'd0;
                    plane_sz<= in_h * in_w;
                    // SPLIT's channel window is offset by aux0 from the start.
                    spl_plane <= aux0[15:0] * (in_h * in_w);
                    // CONCAT at oc=0 reads src0 channel 0, so cat_c = 0.
                    cat_plane <= 32'd0;
                    // Upsample factors in yolo26n are powers of two; encode
                    // log2 so the source pixel is a shift.
                    up_sh   <= (aux0[15:0] == 16'd8) ? 5'd3 :
                               (aux0[15:0] == 16'd4) ? 5'd2 :
                               (aux0[15:0] == 16'd2) ? 5'd1 : 5'd0;
                    acc8    <= -16'sd128;
                    busy    <= 1'b1; done <= 1'b0; error <= 1'b0;
                    // Softmax needs two passes over the channel axis per
                    // position, so it runs its own loop rather than the
                    // shared one-element-at-a-time walk.
                    state   <= (op == LAYER_OP_SOFTMAX) ? E_SM_RD : E_RD_A;
                end
            end

            // ------------------------------------------------------------
            E_RD_A: begin
                if (g_op == LAYER_OP_MAXPOOL && !pool_in_range) begin
                    // Outside the map contributes nothing to a max over a
                    // ReLU/SiLU output; -128 is the INT8 identity for max.
                    operand_a <= 8'h80;
                    state     <= E_COMPUTE;
                end else begin
                    rd_addr  <= {32'h0, a_base + a_off};
                    rd_len   <= 8'd1;
                    rd_start <= 1'b1;
                    state    <= E_RD_AW;
                end
            end

            E_RD_AW: begin
                if (rd_data_valid)
                    operand_a <= rd_data[{a_off[2:0], 3'b000} +: 8];
                if (rd_done) begin
                    if (rd_error) begin error <= 1'b1; state <= E_ERR; end
                    else state <= (g_op == LAYER_OP_ADD) ? E_RD_B : E_COMPUTE;
                end
            end

            // Second operand: only Add needs one.
            E_RD_B: begin
                rd_addr  <= {32'h0, g_src1 + add_off};
                rd_len   <= 8'd1;
                rd_start <= 1'b1;
                state    <= E_RD_BW;
            end

            E_RD_BW: begin
                if (rd_data_valid)
                    operand_b <= rd_data[{add_off[2:0], 3'b000} +: 8];
                if (rd_done) begin
                    if (rd_error) begin error <= 1'b1; state <= E_ERR; end
                    else state <= E_COMPUTE;
                end
            end

            // ------------------------------------------------------------
            E_COMPUTE: begin
                case (g_op)
                LAYER_OP_ADD: begin
                    // Saturating INT8 add. Both operands share a scale by
                    // construction -- the exporter forces the two branches of a
                    // residual to a common scale, so no rescale is needed here.
                    begin : do_add
                        reg signed [15:0] s;
                        s = $signed(operand_a) + $signed(operand_b);
                        if      (s >  127) wr_data <= {56'h0,  8'sd127};
                        else if (s < -128) wr_data <= {56'h0, -8'sd128};
                        else               wr_data <= {56'h0, s[7:0]};
                    end
                    state <= E_WR;
                end

                LAYER_OP_MAXPOOL: begin
                    if ($signed(operand_a) > acc8) acc8 <= $signed(operand_a);
                    if (pk == pool_k*pool_k - 1) begin
                        pk      <= 4'd0;
                        pk_y    <= 4'd0;
                        pk_x    <= 4'd0;
                        wr_data <= {56'h0,
                                    ($signed(operand_a) > acc8)
                                      ? operand_a : acc8[7:0]};
                        state   <= E_WR;
                    end else begin
                        pk    <= pk + 4'd1;
                        // pk_y/pk_x track pk/pool_k and pk%pool_k without a
                        // divider: pk advances by one, so they are an odometer.
                        if (pk_x == pool_k[3:0] - 4'd1) begin
                            pk_x <= 4'd0;
                            pk_y <= pk_y + 4'd1;
                        end else begin
                            pk_x <= pk_x + 4'd1;
                        end
                        state <= E_RD_A;
                    end
                end

                default: begin
                    // Concat / Split / Upsample are pure copies.
                    wr_data <= {56'h0, operand_a};
                    state   <= E_WR;
                end
                endcase
            end

            // ------------------------------------------------------------
            // Every op above leaves its INT8 result in lane 0 of wr_data.
            // Shift it into the lane the destination address selects and
            // enable only that lane: with an all-ones strobe a single-byte
            // store also writes its 7 neighbours, and since idx advances by
            // one each iteration those neighbours are the bytes written next.
            // Every op above leaves its INT8 result in lane 0 of wr_data. Shift
            // it into the lane the destination address selects and enable only
            // that lane: with an all-ones strobe a single-byte store also
            // writes its 7 neighbours, and since idx advances by one each
            // iteration those neighbours are the bytes written next.
            //
            // The shift happens HERE, one state before wr_start, so wr_data is
            // already in its final position on the cycle the master samples it.
            // Doing both in the same state asserts wr_start alongside a
            // non-blocking update that has not landed yet.
            E_WR: begin
                wr_addr <= {32'h0, e_dst_addr};
                wr_data <= {56'h0, wr_data[7:0]} << {e_dst_addr[2:0], 3'b000};
                wr_strb <= 8'h01 << e_dst_addr[2:0];
                wr_len  <= 8'd1;
                state   <= E_WR_GO;
            end

            E_WR_GO: begin
                wr_start <= 1'b1;
                state    <= E_WR_W;
            end

            E_WR_W: begin
                if (wr_done) begin
                    if (wr_error) begin error <= 1'b1; state <= E_ERR; end
                    else if (g_op == LAYER_OP_SOFTMAX) begin
                        // Next channel at this position, then the next
                        // position with a fresh max/sum.
                        if (sm_ch == g_in_c - 16'd1) begin
                            sm_ch    <= 16'd0;
                            sm_phase <= 2'd0;
                            sm_sum   <= 24'd0;
                            if (sm_pos == g_in_w * g_in_h - 16'd1)
                                state <= E_DONE;
                            else begin
                                sm_pos <= sm_pos + 16'd1;
                                state  <= E_SM_RD;
                            end
                        end else begin
                            sm_ch <= sm_ch + 16'd1;
                            state <= E_SM_RD;
                        end
                    end
                    else state <= E_NEXT;
                end
            end

            // ---- softmax ---------------------------------------------------
            E_SM_RD: begin
                rd_addr  <= {32'h0, g_src0 + sm_src_off};
                rd_len   <= 8'd1;
                rd_start <= 1'b1;
                state    <= E_SM_RDW;
            end

            E_SM_RDW: begin
                if (rd_data_valid)
                    operand_a <= rd_data[{sm_src_off[2:0], 3'b000} +: 8];
                if (rd_done) begin
                    if (rd_error) begin error <= 1'b1; state <= E_ERR; end
                    else state <= E_SM_STEP;
                end
            end

            E_SM_STEP: begin
                case (sm_phase)
                // Pass 0: largest score in this position's channel vector.
                2'd0: begin
                    if (sm_ch == 16'd0 ||
                        $signed(operand_a) > $signed(sm_max))
                        sm_max <= $signed(operand_a);
                    if (sm_ch == g_in_c - 16'd1) begin
                        sm_ch    <= 16'd0;
                        sm_sum   <= 24'd0;
                        sm_phase <= 2'd1;
                        state    <= E_SM_RD;
                    end else begin
                        sm_ch <= sm_ch + 16'd1;
                        state <= E_SM_RD;
                    end
                end

                // Pass 1: total of exp(x - max) over the same vector.
                2'd1: begin
                    sm_sum <= sm_sum + {16'h0, exp_rom[sm_idx]};
                    if (sm_ch == g_in_c - 16'd1) begin
                        sm_ch    <= 16'd0;
                        sm_phase <= 2'd2;
                        state    <= E_SM_RD;
                    end else begin
                        sm_ch <= sm_ch + 16'd1;
                        state <= E_SM_RD;
                    end
                end

                // Pass 2: emit exp(x - max) / sum, as an INT8 code.
                //
                // The result is a probability in [0,1]; the exporter gives the
                // consumer a scale of 127 codes per unit, so the code is
                // 127 * exp/sum. Computed as (exp * 127) / sum with the
                // division done by the same restoring loop used elsewhere --
                // sum is not a constant, so there is nothing to hoist.
                2'd2: begin
                    sm_exp  <= exp_rom[sm_idx];
                    wr_data <= 64'h0;
                    state   <= E_SM_WRW;
                end

                default: sm_phase <= 2'd0;
                endcase
            end

            // Divide, then store one byte. The divide is short: numerator is
            // at most 127*255 and the quotient fits in 8 bits.
            // Start the serial divide. `num / sm_sum` was written here as a
            // single-cycle variable divide, and it was the design's critical
            // path by a wide margin: the whole -53.5 ns of setup failure at
            // 50 MHz, on every one of the six worst paths.
            //
            // The comment that used to sit here said the divide was "short"
            // because the quotient fits in 8 bits. That is the wrong measure --
            // divider hardware is sized by the OPERANDS, and both are 24 bits.
            // This is the same defect the plan's A1 rewrite removed from the
            // conv engine's reduction seed.
            E_SM_WRW: begin
                sd_num   <= {8'h0, sm_exp} * 24'd127;
                sd_den   <= sm_sum;
                sd_q     <= 24'd0;
                sd_rem   <= 24'd0;
                sd_i     <= 5'd23;
                // A zero sum means every exp term was zero; the quotient is
                // then defined as zero rather than dividing by it.
                sd_busy  <= (sm_sum != 24'd0);
                state    <= E_SM_DIV;
            end

            // One restoring-division step per cycle: 24 cycles for a 24-bit
            // numerator. Softmax runs once per channel over a handful of
            // channels, so the cost is invisible next to the memory traffic
            // the layer already does.
            E_SM_DIV: begin
                if (!sd_busy) begin
                    wr_data <= {56'h0, (sd_q > 24'd127) ? 8'd127 : sd_q[7:0]}
                               << {sm_dst_off[2:0], 3'b000};
                    wr_strb <= 8'h01 << sm_dst_off[2:0];
                    wr_addr <= {32'h0, g_dst + sm_dst_off};
                    wr_len  <= 8'd1;
                    state   <= E_WR_GO;
                end else begin
                    sd_rem_n = {sd_rem[22:0], sd_num[sd_i]};
                    if (sd_rem_n >= sd_den) begin
                        sd_rem     <= sd_rem_n - sd_den;
                        sd_q[sd_i] <= 1'b1;
                    end else begin
                        sd_rem <= sd_rem_n;
                    end
                    if (sd_i == 5'd0) sd_busy <= 1'b0;
                    else              sd_i    <= sd_i - 5'd1;
                end
            end

            E_NEXT: begin
                acc8 <= -16'sd128;
                if (idx == total - 1) state <= E_DONE;
                else begin
                    idx   <= idx + 32'd1;
                    state <= E_RD_A;

                    // Advance (oc,oy,ox) and every product derived from it.
                    // Each carry costs one add, versus the divider chain this
                    // replaced. ox is the fast axis, matching the flat layout
                    // of `idx` that the write side uses (g_dst + idx).
                    if (ox == g_out_w - 16'd1) begin
                        ox <= 16'd0;
                        if (oy == g_out_h - 16'd1) begin
                            oy       <= 16'd0;
                            oy_row   <= 32'd0;
                            oc       <= oc + 16'd1;
                            oc_plane <= oc_plane + plane_sz;
                            // CONCAT: channels below in_c index src0 directly;
                            // at/above it they index src1 from zero again, so
                            // the plane offset restarts at that boundary.
                            cat_plane <= ((oc + 16'd1) == g_in_c)
                                       ? 32'd0
                                       : cat_plane + plane_sz;
                            spl_plane <= spl_plane + plane_sz;
                        end else begin
                            oy     <= oy + 16'd1;
                            oy_row <= oy_row + {16'h0, g_in_w};
                        end
                    end else begin
                        ox <= ox + 16'd1;
                    end
                end
            end

            // ------------------------------------------------------------
            E_DONE: begin
                busy <= 1'b0; done <= 1'b1; state <= E_IDLE;
            end

            E_ERR: begin
                busy <= 1'b0; done <= 1'b1; error <= 1'b1; state <= E_IDLE;
            end

            default: state <= E_IDLE;
            endcase

            if (state != E_IDLE && done) done <= 1'b0;
        end
    end

endmodule
