// -----------------------------------------------------------------------------
// GENERATED by qrts/tools/port_rtl.py -- DO NOT EDIT THIS COPY.
//
// Source: DVCFinal/rtl/yolo_detect_engine.sv
//
// Edit the source and re-run the porter:
//     python qrts/tools/port_rtl.py
//
// Xilinx synthesis attributes have been rewritten for Quartus. See the porter
// for what is rewritten and what still needs hand work.
// -----------------------------------------------------------------------------
// =============================================================================
// yolo_detect_engine.sv — YOLO26n decode head, no NMS
//
// This module is the reason the whole frame can run without the CPU.
//
// YOLO26n was exported with end2end=True and reg_max=1 (verified from the
// checkpoint). Two consequences, and both of them remove hardware:
//
//   reg_max=1   The box branch is a plain 4-value distance (l,t,r,b) per cell_i.
//               With reg_max=16 the head would need a 16-bin softmax and an
//               expectation sum per side (DFL) -- ~64 multiply-accumulates and
//               an exp LUT per anchor. At reg_max=1 the "DFL" collapses to the
//               identity, so decode is four adds and two shifts.
//
//   end2end     The head is trained one-to-one, so duplicate boxes are already
//               suppressed by the model. No IoU matrix, no sort-by-score with
//               pairwise suppression, no iterative loop with data-dependent
//               runtime. Selection is a single confidence threshold plus a
//               top-K, which is a streaming pass.
//
// Together those are what make the head a fixed-latency streaming operation
// instead of the usual variable-time NMS that almost always ends up back on the
// CPU. Nothing here loops on data.
//
// ---------------------------------------------------------------------------
// Input layout, per pyramid level (P3 stride 8, P4 16, P5 32)
// ---------------------------------------------------------------------------
// The exporter arranges the head output as one INT8 CHW map with 84 channels:
//   channels  0..3   box distances l,t,r,b  (in stride units, Q_BOX fixed point)
//   channels  4..83  class scores           (INT8, requantized logits)
// which is exactly `no = nc + 4*reg_max = 80 + 4 = 84` from the checkpoint.
//
// Decode for cell_i (y,x) at level stride S:
//   cx = (x + 0.5) * S            anchor centre
//   cy = (y + 0.5) * S
//   x1 = cx - l*S     y1 = cy - t*S
//   x2 = cx + r*S     y2 = cy + b*S
// Emitted in Q4 fixed point (1/16 pixel) so the CPU never sees a float.
//
// ---------------------------------------------------------------------------
// Output record: 16 bytes per box, written to dst
// ---------------------------------------------------------------------------
//   0x0 [15:0]  x1   Q12.4 pixels
//   0x2 [15:0]  y1
//   0x4 [15:0]  x2
//   0x6 [15:0]  y2
//   0x8 [15:0]  score  (INT8 logit sign-extended, higher is better)
//   0xA [15:0]  class  (0..79)
//   0xC [31:0]  reserved / level stride, for debug
// =============================================================================
`timescale 1ns/1ps

module yolo_detect_engine #(
    parameter integer NUM_CLASSES = 80,
    parameter integer MAX_BOXES   = 300,   // matches the checkpoint's max_det
    parameter integer BOX_BYTES   = 16
)(
    input  wire        clk,
    input  wire        rst_n,

    // ---- job from the sequencer ----
    input  wire        start,
    input  wire [31:0] src,            // 84-channel INT8 head output
    input  wire [31:0] dst,            // box list destination
    input  wire [15:0] in_w, in_h, in_c,
    input  wire [31:0] level_stride,   // 8, 16 or 32
    input  wire [15:0] rq_mult,
    input  wire [4:0]  rq_shift,
    input  wire        flush,          // TOPK pass: write the list out

    output reg         busy,
    output reg         done,
    output reg         error,
    output reg  [3:0]  fsm_state,
    output reg  [15:0] num_boxes,

    // ---- score threshold, from the CPU register file ----
    input  wire signed [7:0] conf_thresh,

    // ---- AXI4 master read ----
    output reg         rd_start,
    output reg  [63:0] rd_addr,
    output reg  [7:0]  rd_len,
    input  wire [63:0] rd_data,
    input  wire        rd_data_valid,
    input  wire        rd_done,
    input  wire        rd_error,

    // ---- AXI4 master write ----
    output reg         wr_start,
    output reg  [63:0] wr_addr,
    output reg  [7:0]  wr_len,
    output reg  [63:0] wr_data,
    // Boxes are written as whole 8-byte beats at aligned addresses, so every
    // lane is live. Present for interface uniformity with the other masters.
    output wire [7:0]  wr_strb,
    input  wire        wr_data_ready,
    input  wire        wr_done,
    input  wire        wr_error
);

    assign wr_strb = 8'hFF;

    localparam integer Q_SHIFT = 4;   // output boxes in 1/16 pixel

    // Latched job
    reg [31:0] g_src, g_dst, g_stride;
    reg [15:0] g_w, g_h;

    // Cell walk
    reg [31:0] cell_i, n_cells;
    // Raster position tracked as counters rather than recovered with
    // cell_i / g_w and cell_i % g_w -- variable divides in a per-cell path.
    reg  [15:0] cy_i, cx_i;

    // Per-cell_i gathered values
    reg signed [7:0] bdist [0:3];       // l,t,r,b
    reg signed [7:0] best_score;
    reg [15:0]       best_class;
    reg [7:0]        ch;               // channel cursor

    // The kept-box list. Held in a BRAM-inferable array and only written out on
    // the flush pass, so the three pyramid levels accumulate into one list and
    // the CPU gets a single contiguous result.
    // 300 x 128 bits = 38,400 bits. This MUST land in block RAM: built out of
    // flip-flops it cost 34,000 registers and 26,315 logic elements, making
    // this engine the largest thing in the design and putting dvcon_top over
    // the EP4CE115's 114,480 LE.
    //
    // What stopped the inference was reading it ASYNCHRONOUSLY, and reading
    // two different slices of the same word in one expression:
    //
    //     wr_data <= (wr_beat == 0) ? box_ram[wr_idx][63:0]
    //                               : box_ram[wr_idx][127:64];
    //
    // No block-RAM primitive has that shape. The inferrable form is a single
    // registered read port, addressed outside the array access, with the
    // slicing done afterwards on the registered output -- see box_q below.
    (* ramstyle = "M9K" *) reg [127:0] box_ram [0:MAX_BOXES-1];

    reg [127:0] box_q;                       // registered read data
    reg [15:0]  box_raddr;                   // read address, one per cycle
    reg [127:0] box_wdata;
    reg [15:0]  box_waddr;
    reg         box_we;

    always @(posedge clk) begin
        if (box_we) box_ram[box_waddr] <= box_wdata;
        box_q <= box_ram[box_raddr];
    end
    reg [15:0]  box_count;
    reg [15:0]  wr_idx;
    reg [2:0]   wr_beat;

    // ---- decode arithmetic -------------------------------------------------
    //
    // The pyramid stride is always 8, 16 or 32 -- a power of two, one per
    // level. Multiplying by it therefore costs nothing: log2(stride) is
    // latched at start and every "* stride" becomes a shift.
    //
    // Written as `* g_stride`, these six expressions synthesised into six wide
    // multipliers (measured in the synthesis log's multiplier table). The
    // systolic array needs every DSP on this part, so none of them can be
    // spent on address arithmetic that a shifter does exactly.
    reg [5:0] g_stride_log2;

    // Anchor centre in Q4 pixels: (cell + 0.5) * stride.
    wire [31:0] cx_q = (((cx_i << 1) + 1) << g_stride_log2) << (Q_SHIFT-1);
    wire [31:0] cy_q = (((cy_i << 1) + 1) << g_stride_log2) << (Q_SHIFT-1);
    // Distances are INT8 in stride units; scale to Q4 pixels.
    wire signed [31:0] l_q = ($signed(bdist[0]) <<< g_stride_log2) <<< Q_SHIFT;
    wire signed [31:0] t_q = ($signed(bdist[1]) <<< g_stride_log2) <<< Q_SHIFT;
    wire signed [31:0] r_q = ($signed(bdist[2]) <<< g_stride_log2) <<< Q_SHIFT;
    wire signed [31:0] b_q = ($signed(bdist[3]) <<< g_stride_log2) <<< Q_SHIFT;

    wire signed [31:0] x1 = $signed(cx_q) - l_q;
    wire signed [31:0] y1 = $signed(cy_q) - t_q;
    wire signed [31:0] x2 = $signed(cx_q) + r_q;
    wire signed [31:0] y2 = $signed(cy_q) + b_q;

    function automatic [15:0] clamp16(input signed [31:0] v);
        if (v < 0)            clamp16 = 16'd0;
        else if (v > 32'sd65535) clamp16 = 16'hFFFF;
        else                  clamp16 = v[15:0];
    endfunction

    // Channel c of cell_i (cy,cx) in CHW.
    // ch*g_h*g_w chains two variable multiplies; hw_plane is that product
    // computed once when the job is latched.
    reg  [31:0] hw_plane;
    wire [31:0] ch_off = ch*hw_plane + cy_i*g_w + cx_i;

    // =========================================================================
    // FSM
    // =========================================================================
    localparam [3:0]
        D_IDLE    = 4'd0,
        D_RD      = 4'd1,
        D_RD_W    = 4'd2,
        D_EVAL    = 4'd3,
        D_KEEP    = 4'd4,
        D_NEXT    = 4'd5,
        D_FLUSH   = 4'd6,
        D_FLUSH_W = 4'd7,
        D_DONE    = 4'd8,
        D_ERR     = 4'd9,
        // One cycle for box_ram's registered read to present box_q. A block
        // RAM cannot be read asynchronously, so the address is issued in
        // D_FLUSH and the data used in D_FLUSH_D.
        D_FLUSH_D = 4'd10;

    reg [3:0] state;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state     <= D_IDLE;
            busy      <= 1'b0; done <= 1'b0; error <= 1'b0; fsm_state <= 4'd0;
            rd_start  <= 1'b0; rd_addr <= 64'h0; rd_len <= 8'd0;
            wr_start  <= 1'b0; wr_addr <= 64'h0; wr_len <= 8'd0; wr_data <= 64'h0;
            cell_i      <= 32'd0; ch <= 8'd0;
            box_count <= 16'd0; num_boxes <= 16'd0;
            wr_idx    <= 16'd0; wr_beat <= 3'd0;
            best_score<= -8'sd128; best_class <= 16'd0;
            box_we    <= 1'b0; box_waddr <= 16'd0; box_raddr <= 16'd0;
            box_wdata <= 128'h0;
        end else begin
            rd_start  <= 1'b0;
            wr_start  <= 1'b0;
            // Default low: D_KEEP raises it for exactly one cycle. Left
            // asserted it would rewrite the array every cycle.
            box_we    <= 1'b0;
            fsm_state <= state;

            case (state)
            // ------------------------------------------------------------
            D_IDLE: begin
                busy <= 1'b0;
                if (start) begin
                    g_src    <= src;   g_dst <= dst;
                    g_w      <= in_w;  g_h   <= in_h;
                    g_stride <= level_stride;
                    // Strides are 8/16/32 by construction (P3/P4/P5). Anything
                    // else means the descriptor is wrong; default to 3 (=8) so
                    // the decode stays bounded rather than shifting wildly.
                    case (level_stride)
                        32'd8:   g_stride_log2 <= 6'd3;
                        32'd16:  g_stride_log2 <= 6'd4;
                        32'd32:  g_stride_log2 <= 6'd5;
                        default: g_stride_log2 <= 6'd3;
                    endcase
                    n_cells  <= in_w * in_h;
                    hw_plane <= in_w * in_h;
                    cy_i     <= 16'd0;
                    cx_i     <= 16'd0;
                    cell_i     <= 32'd0;
                    ch       <= 8'd0;
                    best_score <= -8'sd128;
                    best_class <= 16'd0;
                    busy     <= 1'b1; done <= 1'b0; error <= 1'b0;
                    if (flush) begin
                        // TOPK pass: nothing to decode, just emit the list that
                        // the three level passes accumulated.
                        wr_idx  <= 16'd0;
                        wr_beat <= 3'd0;
                        state   <= (box_count == 0) ? D_DONE : D_FLUSH;
                    end else begin
                        state <= D_RD;
                    end
                end
            end

            // ------------------------------------------------------------
            // Walk all 84 channels of one cell_i: 4 distances then 80 scores.
            D_RD: begin
                rd_addr  <= {32'h0, g_src + ch_off};
                rd_len   <= 8'd1;
                rd_start <= 1'b1;
                state    <= D_RD_W;
            end

            D_RD_W: begin
                if (rd_data_valid) begin
                    if (ch < 8'd4) begin
                        bdist[ch[1:0]] <= rd_data[{ch_off[2:0], 3'b000} +: 8];
                    end else begin
                        // Argmax over classes, streaming -- no score buffer and
                        // no sort, which is only valid because end2end already
                        // guarantees one box per object.
                        if ($signed(rd_data[{ch_off[2:0], 3'b000} +: 8]) >
                            best_score) begin
                            best_score <= $signed(rd_data[{ch_off[2:0], 3'b000} +: 8]);
                            best_class <= {8'h0, ch} - 16'd4;
                        end
                    end
                end
                if (rd_done) begin
                    if (rd_error) begin error <= 1'b1; state <= D_ERR; end
                    else if (ch == NUM_CLASSES + 4 - 1) begin
                        ch    <= 8'd0;
                        state <= D_EVAL;
                    end else begin
                        ch    <= ch + 8'd1;
                        state <= D_RD;
                    end
                end
            end

            // ------------------------------------------------------------
            D_EVAL: begin
                // Single threshold. No IoU, no suppression loop.
                if (best_score >= conf_thresh && box_count < MAX_BOXES)
                    state <= D_KEEP;
                else
                    state <= D_NEXT;
            end

            D_KEEP: begin
                box_waddr <= box_count;
                box_we    <= 1'b1;
                box_wdata <= {
                    g_stride[15:0],           // [127:112] debug: level stride
                    best_class,               // [111:96]
                    {{8{best_score[7]}}, best_score}, // [95:80] sign extended
                    16'h0,                    // [79:64] pad
                    clamp16(y2),              // [63:48]
                    clamp16(x2),              // [47:32]
                    clamp16(y1),              // [31:16]
                    clamp16(x1)               // [15:0]
                };
                box_count <= box_count + 16'd1;
                state     <= D_NEXT;
            end

            D_NEXT: begin
                best_score <= -8'sd128;
                best_class <= 16'd0;
                if (cell_i == n_cells - 1) begin
                    num_boxes <= box_count;
                    state     <= D_DONE;
                end else begin
                    cell_i  <= cell_i + 32'd1;
                    if (cx_i == g_w - 1) begin
                        cx_i <= 16'd0;
                        cy_i <= cy_i + 16'd1;
                    end else begin
                        cx_i <= cx_i + 16'd1;
                    end
                    state <= D_RD;
                end
            end

            // ------------------------------------------------------------
            // Flush: 16 bytes per box = 2 beats each.
            // Issue the read address; box_q is valid the cycle after.
            D_FLUSH: begin
                box_raddr <= wr_idx;
                wr_addr   <= {32'h0, g_dst + wr_idx*BOX_BYTES + wr_beat*8};
                wr_len    <= 8'd1;
                state     <= D_FLUSH_D;
            end

            D_FLUSH_D: begin
                wr_data  <= (wr_beat == 3'd0) ? box_q[63:0] : box_q[127:64];
                wr_start <= 1'b1;
                state    <= D_FLUSH_W;
            end

            D_FLUSH_W: begin
                if (wr_done) begin
                    if (wr_error) begin error <= 1'b1; state <= D_ERR; end
                    else if (wr_beat == 3'd0) begin
                        wr_beat <= 3'd1;
                        state   <= D_FLUSH;
                    end else if (wr_idx == box_count - 1) begin
                        num_boxes <= box_count;
                        box_count <= 16'd0;   // reset for the next frame
                        state     <= D_DONE;
                    end else begin
                        wr_beat <= 3'd0;
                        wr_idx  <= wr_idx + 16'd1;
                        state   <= D_FLUSH;
                    end
                end
            end

            // ------------------------------------------------------------
            D_DONE: begin
                busy <= 1'b0; done <= 1'b1; state <= D_IDLE;
            end

            D_ERR: begin
                busy <= 1'b0; done <= 1'b1; error <= 1'b1; state <= D_IDLE;
            end

            default: state <= D_IDLE;
            endcase

            if (state != D_IDLE && done) done <= 1'b0;
        end
    end

endmodule
