// -----------------------------------------------------------------------------
// GENERATED by qrts/tools/port_rtl.py -- DO NOT EDIT THIS COPY.
//
// Source: DVCFinal/rtl/yolo_axi_arbiter.sv
//
// Edit the source and re-run the porter:
//     python qrts/tools/port_rtl.py
//
// Xilinx synthesis attributes have been rewritten for Quartus. See the porter
// for what is rewritten and what still needs hand work.
// -----------------------------------------------------------------------------
// =============================================================================
// yolo_axi_arbiter.sv — 4-to-1 mux onto the single AXI4 master port
//
// The socket in Top.vhd gives the accelerator exactly ONE AXI master. Four
// things want it: the sequencer (descriptor fetch), the conv engine, the
// elementwise engine, and the detect engine.
//
// Fixed priority is correct here and simpler than round-robin, because the
// sequencer serializes the engines by construction -- it never starts a second
// engine while one is running, so at most one engine requester is ever active
// at a time. The arbiter therefore never actually arbitrates between engines;
// it only muxes. Priority exists so that a design error (two engines live at
// once) degrades into a deterministic stall rather than corrupted interleaved
// bursts on the bus.
//
// Grant is LOCKED for the whole transaction. Releasing on rd_done/wr_done
// alone would be wrong: a new requester could win the port between the address
// phase and the data phase and interleave its beats into another master's
// burst. The lock is held from rd_start/wr_start to the matching done.
// =============================================================================
`timescale 1ns/1ps

module yolo_axi_arbiter (
    input  wire        clk,
    input  wire        rst_n,

    // ---- requester 0: layer sequencer (descriptor fetch) ----
    input  wire        s0_rd_start, input wire [63:0] s0_rd_addr, input wire [7:0] s0_rd_len,
    output wire [63:0] s0_rd_data,  output wire s0_rd_data_valid, output wire s0_rd_done, output wire s0_rd_error,
    input  wire        s0_wr_start, input wire [63:0] s0_wr_addr, input wire [7:0] s0_wr_len,
    input  wire [63:0] s0_wr_data,  input wire [7:0] s0_wr_strb,  output wire s0_wr_data_ready, output wire s0_wr_done, output wire s0_wr_error,

    // ---- requester 1: conv engine ----
    input  wire        s1_rd_start, input wire [63:0] s1_rd_addr, input wire [7:0] s1_rd_len,
    output wire [63:0] s1_rd_data,  output wire s1_rd_data_valid, output wire s1_rd_done, output wire s1_rd_error,
    input  wire        s1_wr_start, input wire [63:0] s1_wr_addr, input wire [7:0] s1_wr_len,
    input  wire [63:0] s1_wr_data,  input wire [7:0] s1_wr_strb,  output wire s1_wr_data_ready, output wire s1_wr_done, output wire s1_wr_error,

    // ---- requester 2: elementwise engine ----
    input  wire        s2_rd_start, input wire [63:0] s2_rd_addr, input wire [7:0] s2_rd_len,
    output wire [63:0] s2_rd_data,  output wire s2_rd_data_valid, output wire s2_rd_done, output wire s2_rd_error,
    input  wire        s2_wr_start, input wire [63:0] s2_wr_addr, input wire [7:0] s2_wr_len,
    input  wire [63:0] s2_wr_data,  input wire [7:0] s2_wr_strb,  output wire s2_wr_data_ready, output wire s2_wr_done, output wire s2_wr_error,

    // ---- requester 3: detect engine ----
    input  wire        s3_rd_start, input wire [63:0] s3_rd_addr, input wire [7:0] s3_rd_len,
    output wire [63:0] s3_rd_data,  output wire s3_rd_data_valid, output wire s3_rd_done, output wire s3_rd_error,
    input  wire        s3_wr_start, input wire [63:0] s3_wr_addr, input wire [7:0] s3_wr_len,
    input  wire [63:0] s3_wr_data,  input wire [7:0] s3_wr_strb,  output wire s3_wr_data_ready, output wire s3_wr_done, output wire s3_wr_error,

    // ---- downstream: the one real axi4_master ----
    output reg         m_rd_start, output reg [63:0] m_rd_addr, output reg [7:0] m_rd_len,
    input  wire [63:0] m_rd_data,  input wire m_rd_data_valid, input wire m_rd_done, input wire m_rd_error,
    output reg         m_wr_start, output reg [63:0] m_wr_addr, output reg [7:0] m_wr_len,
    output reg [63:0]  m_wr_data,  output reg [7:0] m_wr_strb,
    input wire m_wr_data_ready, input wire m_wr_done, input wire m_wr_error
);

    // =========================================================================
    // Read channel grant
    // =========================================================================
    reg [1:0] rd_grant_r;     // who owns the channel once locked
    reg       rd_locked;

    wire [3:0] rd_req = {s3_rd_start, s2_rd_start, s1_rd_start, s0_rd_start};

    // Requesters assert *_rd_start for a SINGLE cycle. Selecting with a
    // registered grant loses that pulse: the grant moves to the winner on the
    // next edge, by which time start has already dropped and the master never
    // sees a request. The engine then waits forever for a done that cannot
    // come.
    //
    // So the winner is chosen combinationally and only the LOCK is registered.
    // While unlocked, rd_grant is the highest-priority requester this cycle, so
    // its start reaches the master immediately; once locked, it is the
    // requester that won, so the rest of the burst stays with it.
    wire [1:0] rd_sel = rd_req[0] ? 2'd0 :
                        rd_req[1] ? 2'd1 :
                        rd_req[2] ? 2'd2 : 2'd3;
    wire [1:0] rd_grant = rd_locked ? rd_grant_r : rd_sel;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            rd_grant_r <= 2'd0;
            rd_locked  <= 1'b0;
        end else if (!rd_locked) begin
            if (|rd_req) begin
                rd_grant_r <= rd_sel;
                rd_locked  <= 1'b1;
            end
        end else if (m_rd_done) begin
            rd_locked <= 1'b0;
        end
    end

    always @(*) begin
        case (rd_grant)
        2'd0: begin m_rd_start = s0_rd_start; m_rd_addr = s0_rd_addr; m_rd_len = s0_rd_len; end
        2'd1: begin m_rd_start = s1_rd_start; m_rd_addr = s1_rd_addr; m_rd_len = s1_rd_len; end
        2'd2: begin m_rd_start = s2_rd_start; m_rd_addr = s2_rd_addr; m_rd_len = s2_rd_len; end
        default: begin m_rd_start = s3_rd_start; m_rd_addr = s3_rd_addr; m_rd_len = s3_rd_len; end
        endcase
    end

    // Read data fans out to everyone; only the granted requester's valid/done
    // strobes are asserted, so the others ignore the bus.
    assign s0_rd_data = m_rd_data;
    assign s1_rd_data = m_rd_data;
    assign s2_rd_data = m_rd_data;
    assign s3_rd_data = m_rd_data;

    assign s0_rd_data_valid = m_rd_data_valid && (rd_grant == 2'd0);
    assign s1_rd_data_valid = m_rd_data_valid && (rd_grant == 2'd1);
    assign s2_rd_data_valid = m_rd_data_valid && (rd_grant == 2'd2);
    assign s3_rd_data_valid = m_rd_data_valid && (rd_grant == 2'd3);

    assign s0_rd_done = m_rd_done && (rd_grant == 2'd0);
    assign s1_rd_done = m_rd_done && (rd_grant == 2'd1);
    assign s2_rd_done = m_rd_done && (rd_grant == 2'd2);
    assign s3_rd_done = m_rd_done && (rd_grant == 2'd3);

    assign s0_rd_error = m_rd_error && (rd_grant == 2'd0);
    assign s1_rd_error = m_rd_error && (rd_grant == 2'd1);
    assign s2_rd_error = m_rd_error && (rd_grant == 2'd2);
    assign s3_rd_error = m_rd_error && (rd_grant == 2'd3);

    // =========================================================================
    // Write channel grant (independent of the read channel)
    // =========================================================================
    reg [1:0] wr_grant_r;
    reg       wr_locked;

    wire [3:0] wr_req = {s3_wr_start, s2_wr_start, s1_wr_start, s0_wr_start};

    // Same single-cycle-pulse problem as the read channel above, and the same
    // fix. This one was load-bearing: with the sequencer occupying slot 0 the
    // grant sat at 0, the conv engine's slot-1 wr_start pulse never reached the
    // master, and the engine parked in C_STORE_W forever on the first store of
    // the first layer.
    wire [1:0] wr_sel = wr_req[0] ? 2'd0 :
                        wr_req[1] ? 2'd1 :
                        wr_req[2] ? 2'd2 : 2'd3;
    wire [1:0] wr_grant = wr_locked ? wr_grant_r : wr_sel;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            wr_grant_r <= 2'd0;
            wr_locked  <= 1'b0;
        end else if (!wr_locked) begin
            if (|wr_req) begin
                wr_grant_r <= wr_sel;
                wr_locked  <= 1'b1;
            end
        end else if (m_wr_done) begin
            wr_locked <= 1'b0;
        end
    end

    // The byte strobe follows the granted requester exactly like wr_data --
    // it is part of the beat, not of the address phase.
    always @(*) begin
        case (wr_grant)
        2'd0: begin m_wr_start = s0_wr_start; m_wr_addr = s0_wr_addr; m_wr_len = s0_wr_len; m_wr_data = s0_wr_data; m_wr_strb = s0_wr_strb; end
        2'd1: begin m_wr_start = s1_wr_start; m_wr_addr = s1_wr_addr; m_wr_len = s1_wr_len; m_wr_data = s1_wr_data; m_wr_strb = s1_wr_strb; end
        2'd2: begin m_wr_start = s2_wr_start; m_wr_addr = s2_wr_addr; m_wr_len = s2_wr_len; m_wr_data = s2_wr_data; m_wr_strb = s2_wr_strb; end
        default: begin m_wr_start = s3_wr_start; m_wr_addr = s3_wr_addr; m_wr_len = s3_wr_len; m_wr_data = s3_wr_data; m_wr_strb = s3_wr_strb; end
        endcase
    end

    assign s0_wr_data_ready = m_wr_data_ready && (wr_grant == 2'd0);
    assign s1_wr_data_ready = m_wr_data_ready && (wr_grant == 2'd1);
    assign s2_wr_data_ready = m_wr_data_ready && (wr_grant == 2'd2);
    assign s3_wr_data_ready = m_wr_data_ready && (wr_grant == 2'd3);

    assign s0_wr_done = m_wr_done && (wr_grant == 2'd0);
    assign s1_wr_done = m_wr_done && (wr_grant == 2'd1);
    assign s2_wr_done = m_wr_done && (wr_grant == 2'd2);
    assign s3_wr_done = m_wr_done && (wr_grant == 2'd3);

    assign s0_wr_error = m_wr_error && (wr_grant == 2'd0);
    assign s1_wr_error = m_wr_error && (wr_grant == 2'd1);
    assign s2_wr_error = m_wr_error && (wr_grant == 2'd2);
    assign s3_wr_error = m_wr_error && (wr_grant == 2'd3);

endmodule
