#!/usr/bin/env python3
"""Emit the SDRAM memory map and wire protocol as both a C header and a
SystemVerilog header, from one definition.

The map is a contract between three things that are edited independently: the
RTL, the host driver, and the model exporter. If any two disagree the symptom
is not a crash -- the accelerator reads weights from where the image is, and
produces detections that look plausible and are wrong. That failure survives
code review because every file involved is individually correct.

So neither side gets to write the numbers down. Both include a generated file,
and this script is the only place the values exist.

    python tools/gen_memmap.py            # writes both headers
    python tools/gen_memmap.py --check    # non-zero exit if they are stale
"""

import argparse
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
QRTS = HERE.parent

# ---------------------------------------------------------------------------
# The map. Sizes are what the model and frame actually need, with the arena
# taking the remainder; see MIGRATION-PLAN.md.
# ---------------------------------------------------------------------------
REGIONS = [
    ("MODEL", 0x0000_0000, 4 << 20,
     "model blob: 32-byte header + 181 x 64 B descriptors + weights"),
    ("FRAME", 0x0040_0000, 2 << 20,
     "input frame, INT8 CHW 3x640x640 = 1,228,800 B"),
    ("BOXES", 0x0060_0000, 64 << 10,
     "box list: 300 x 16-byte records, Q12.4"),
    ("ARENA", 0x0080_0000, 56 << 20,
     "feature-map arena (exporter --fmap-base)"),
    ("FRAME2", 0x0400_0000, 64 << 20,
     "second frame buffer, for double buffering"),
]

SDRAM_BYTES = 128 << 20

# ---------------------------------------------------------------------------
# Wire protocol. Only the opcodes the FPGA implements are listed: control went
# to JTAG, so eth_cmd_engine handles bulk writes and the ACK window only.
# ---------------------------------------------------------------------------
ETHERTYPE = 0x88B5
HDR_BYTES = 16
MAX_PAYLOAD = 1408          # a multiple of 128: whole SDRAM bursts
ACK_WINDOW = 64

OPCODES = [
    ("WRITE_MEM", 0x01, "payload -> SDRAM at addr"),
    ("ACK_REQ",   0x06, "reply with the 64-bit received bitmap"),
    ("ACK",       0x10, "FPGA -> host: the bitmap"),
]

# Register offsets, as dvcon_regs implements them (word indices).
REGISTERS = [
    ("CTRL",        0x00, "bit0 START, bit1 soft reset, bit2 ucode mode"),
    ("STATUS",      0x01, "bit0 busy, bit1 done, bit2 error"),
    ("DESC_ADDR",   0x06, "descriptor table base"),
    ("IMG_ADDR",    0x07, "input frame base"),
    ("BOX_ADDR",    0x08, "box list base"),
    ("CONF_THRESH", 0x09, "INT8 confidence threshold"),
    ("NUM_BOXES",   0x0A, "boxes written by the last frame"),
    ("IDENT",       0x0F, "0xDC, ARRAY_SIZE, build id"),
    # Answered inside jtag_ctrl from wires, not by the accelerator's register
    # block. Read-only, and the first thing to check during bring-up.
    ("ETH_GOOD",    0x3A, "ethernet frames with a good FCS"),
    ("ETH_BAD",     0x3B, "ethernet frames that failed FCS"),
    ("ETH_CMD",     0x3C, "command frames accepted"),
    ("ETH_BITMAP",  0x3D, "low 32 bits of the ACK window bitmap"),
    ("MEMADDR",     0x3E, "SDRAM read cursor (write)"),
    ("MEMDATA",     0x3F, "word at the cursor; post-increments (read)"),
]


def c_header():
    L = []
    L.append("/* GENERATED by qrts/tools/gen_memmap.py -- do not edit. */")
    L.append("#ifndef DVCON_MEMMAP_H")
    L.append("#define DVCON_MEMMAP_H")
    L.append("")
    L.append("#include <stdint.h>")
    L.append("")
    L.append(f"#define DVCON_SDRAM_BYTES  {SDRAM_BYTES}u")
    L.append("")
    for name, base, size, why in REGIONS:
        L.append(f"/* {why} */")
        L.append(f"#define DVCON_{name}_BASE  0x{base:08X}u")
        L.append(f"#define DVCON_{name}_SIZE  {size}u")
    L.append("")
    L.append(f"#define DVCON_ETHERTYPE    0x{ETHERTYPE:04X}u")
    L.append(f"#define DVCON_HDR_BYTES    {HDR_BYTES}u")
    L.append(f"#define DVCON_MAX_PAYLOAD  {MAX_PAYLOAD}u")
    L.append(f"#define DVCON_ACK_WINDOW   {ACK_WINDOW}u")
    L.append("")
    for name, op, why in OPCODES:
        L.append(f"#define DVCON_OP_{name}  0x{op:02X}u  /* {why} */")
    L.append("")
    for name, off, why in REGISTERS:
        L.append(f"#define DVCON_REG_{name}  0x{off:02X}u  /* {why} */")
    L.append("")
    L.append("/* Command header, big endian on the wire. */")
    L.append("struct dvcon_hdr {")
    L.append("    uint8_t  ver;")
    L.append("    uint8_t  opcode;")
    L.append("    uint8_t  flags;")
    L.append("    uint8_t  rsv;")
    L.append("    uint32_t seq;")
    L.append("    uint32_t addr;")
    L.append("    uint16_t len;")
    L.append("    uint16_t rsv2;")
    L.append("};")
    L.append("")
    L.append("#endif /* DVCON_MEMMAP_H */")
    return "\n".join(L) + "\n"


def sv_header():
    L = []
    L.append("// GENERATED by qrts/tools/gen_memmap.py -- do not edit.")
    L.append("`ifndef DVCON_MEMMAP_VH")
    L.append("`define DVCON_MEMMAP_VH")
    L.append("")
    for name, base, size, why in REGIONS:
        L.append(f"// {why}")
        L.append(f"`define DVCON_{name}_BASE 32'h{base:08X}")
        L.append(f"`define DVCON_{name}_SIZE 32'd{size}")
    L.append("")
    L.append(f"`define DVCON_ETHERTYPE   16'h{ETHERTYPE:04X}")
    L.append(f"`define DVCON_MAX_PAYLOAD 16'd{MAX_PAYLOAD}")
    L.append(f"`define DVCON_ACK_WINDOW  {ACK_WINDOW}")
    L.append("")
    for name, op, why in OPCODES:
        L.append(f"`define DVCON_OP_{name} 8'h{op:02X}   // {why}")
    L.append("")
    for name, off, why in REGISTERS:
        L.append(f"`define DVCON_REG_{name} 6'h{off:02X}  // {why}")
    L.append("")
    L.append("`endif")
    return "\n".join(L) + "\n"


def overlap_check():
    """A map whose regions overlap is the bug this file exists to prevent."""
    spans = sorted((b, b + s, n) for n, b, s, _ in REGIONS)
    for (b0, e0, n0), (b1, e1, n1) in zip(spans, spans[1:]):
        if e0 > b1:
            sys.exit(f"map error: {n0} (0x{b0:08X}..0x{e0:08X}) overlaps "
                     f"{n1} (0x{b1:08X})")
    top = spans[-1][1]
    if top > SDRAM_BYTES:
        sys.exit(f"map error: regions end at 0x{top:08X}, past the "
                 f"{SDRAM_BYTES // (1 << 20)} MB of SDRAM")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the generated files are stale")
    args = ap.parse_args()

    overlap_check()

    targets = {
        QRTS / "sw" / "dvcon_memmap.h": c_header(),
        QRTS / "rtl" / "dvcon_memmap.vh": sv_header(),
    }

    stale = False
    for path, text in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        if args.check:
            print(f"  stale: {path}")
            stale = True
        else:
            path.write_text(text, encoding="utf-8")
            print(f"  wrote {path}")

    if args.check and stale:
        sys.exit("memory map headers are stale -- run tools/gen_memmap.py")
    if args.check:
        print("  memory map headers are current")


if __name__ == "__main__":
    main()
