#!/usr/bin/env python3
"""Emit the SDRAM memory map and wire protocol as both a C header and a
SystemVerilog header, from one definition.

The map is a contract between three things that are edited independently: the
RTL, the host driver, and the model exporter. If any two disagree the symptom
is not a crash -- the accelerator reads weights from where the image is, and
produces detections that look plausible and are wrong. That failure survives
code review because every file involved is individually correct.

So neither side gets to write the numbers down. Both include a generated file,
and this script is the only place the values exist.

    python tools/gen_memmap.py            # writes both headers
    python tools/gen_memmap.py --check    # non-zero exit if they are stale
"""

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
QRTS = HERE.parent

# ---------------------------------------------------------------------------
# The map. Sizes are what the model and frame actually need, with the arena
# taking the remainder; see MIGRATION-PLAN.md.
# ---------------------------------------------------------------------------
REGIONS = [
    ("MODEL", 0x0000_0000, 4 << 20,
     "model blob: 32-byte header + 181 x 64 B descriptors + weights"),
    ("FRAME", 0x0040_0000, 2 << 20,
     "input frame, INT8 CHW 3x640x640 = 1,228,800 B"),
    ("BOXES", 0x0060_0000, 64 << 10,
     "box list: 300 x 16-byte records, Q12.4"),
    ("ARENA", 0x0080_0000, 56 << 20,
     "feature-map arena (exporter --fmap-base)"),
    ("FRAME2", 0x0400_0000, 64 << 20,
     "second frame buffer, for double buffering"),
]

SDRAM_BYTES = 128 << 20

# ---------------------------------------------------------------------------
# Wire protocol. Only the opcodes the FPGA implements are listed: control went
# to JTAG, so eth_cmd_engine handles bulk writes and the ACK window only.
# ---------------------------------------------------------------------------
ETHERTYPE = 0x88B5
HDR_BYTES = 16
MAX_PAYLOAD = 1408          # a multiple of 128: whole SDRAM bursts
ACK_WINDOW = 64

OPCODES = [
    ("WRITE_MEM", 0x01, "payload -> SDRAM at addr"),
    ("ACK_REQ",   0x06, "reply with the 64-bit received bitmap"),
    ("ACK",       0x10, "FPGA -> host: the bitmap"),
]

# Register offsets as WORD indices. Avalon is word addressed, so these are the
# byte offsets in dvcon_regs.sv's header divided by four -- getting that wrong
# aliases the whole map to four times its size.
#
# 0x00..0x0C are the accelerator's own registers, forwarded by dvcon_regs.
# 0x33..0x3F are answered inside jtag_ctrl from wires and never reach the
# accelerator; check_registers() below verifies those against the RTL, because
# IDENT was wrong here for a while (0x0F instead of 0x0C) and a host built
# against it reads a register that is not IDENT at all.
REGISTERS = [
    ("CTRL",        0x00, "bit0 START (self-clearing), bit1 MODE 0=GEMM 1=YOLO, "
                          "bit2 ENGINE 0=sequencer 1=microcode"),
    ("STATUS",      0x01, "[0]busy [1]done [2]error [7:4]fsm, read-only"),
    ("SRC_ADDR",    0x02, "GEMM activations"),
    ("DST_ADDR",    0x03, "GEMM results"),
    ("IMG_DIM",     0x04, "{K, ARRAY_SIZE}"),
    ("WEIGHT_ADDR", 0x05, "weight blob base"),
    ("DESC_ADDR",   0x06, "descriptor table base"),
    ("IMG_ADDR",    0x07, "input frame base"),
    ("BOX_ADDR",    0x08, "box list base"),
    ("CONF_THRESH", 0x09, "INT8 confidence threshold"),
    ("NUM_BOXES",   0x0A, "boxes written by the last frame, read-only"),
    ("LAYER_IDX",   0x0B, "which descriptor is executing, read-only"),
    ("IDENT",       0x0C, "{8'hDC, ARRAY_SIZE, build id}, read-only"),

    # Answered inside jtag_ctrl from wires. Read-only unless noted.
    ("SD_TAP",      0x33, "SDRAM read capture tap 0..3 (write)"),
    ("DBG_DSEL",    0x34, "which descriptor word to read back (write)"),
    ("DBG_DVAL",    0x35, "desc[DSEL] as the sequencer latched it"),
    ("ETH_DROP",    0x36, "words the ethernet write queue could not accept"),
    ("DBG_SRC",     0x37, "conv src address the sequencer decoded"),
    ("DBG_DST",     0x38, "conv dst address the sequencer decoded"),
    ("ETH_FILT",    0x39, "good FCS but addressed to someone else"),
    ("ETH_GOOD",    0x3A, "ethernet frames with a good FCS"),
    ("ETH_BAD",     0x3B, "ethernet frames that failed FCS"),
    ("ETH_CMD",     0x3C, "command frames accepted"),
    ("ETH_BITMAP",  0x3D, "low 32 bits of the ACK window bitmap"),
    ("MEMADDR",     0x3E, "SDRAM cursor (write)"),
    ("MEMDATA",     0x3F, "word at the cursor; post-increments (read and write)"),
]



def c_header():
    L = []
    L.append("/* GENERATED by qrts/tools/gen_memmap.py -- do not edit. */")
    L.append("#ifndef DVCON_MEMMAP_H")
    L.append("#define DVCON_MEMMAP_H")
    L.append("")
    L.append("#include <stdint.h>")
    L.append("")
    L.append(f"#define DVCON_SDRAM_BYTES  {SDRAM_BYTES}u")
    L.append("")
    for name, base, size, why in REGIONS:
        L.append(f"/* {why} */")
        L.append(f"#define DVCON_{name}_BASE  0x{base:08X}u")
        L.append(f"#define DVCON_{name}_SIZE  {size}u")
    L.append("")
    L.append(f"#define DVCON_ETHERTYPE    0x{ETHERTYPE:04X}u")
    L.append(f"#define DVCON_HDR_BYTES    {HDR_BYTES}u")
    L.append(f"#define DVCON_MAX_PAYLOAD  {MAX_PAYLOAD}u")
    L.append(f"#define DVCON_ACK_WINDOW   {ACK_WINDOW}u")
    L.append("")
    for name, op, why in OPCODES:
        L.append(f"#define DVCON_OP_{name}  0x{op:02X}u  /* {why} */")
    L.append("")
    for name, off, why in REGISTERS:
        L.append(f"#define DVCON_REG_{name}  0x{off:02X}u  /* {why} */")
    L.append("")
    L.append("/* Command header, big endian on the wire. */")
    L.append("struct dvcon_hdr {")
    L.append("    uint8_t  ver;")
    L.append("    uint8_t  opcode;")
    L.append("    uint8_t  flags;")
    L.append("    uint8_t  rsv;")
    L.append("    uint32_t seq;")
    L.append("    uint32_t addr;")
    L.append("    uint16_t len;")
    L.append("    uint16_t rsv2;")
    L.append("};")
    L.append("")
    L.append("#endif /* DVCON_MEMMAP_H */")
    return "\n".join(L) + "\n"


def sv_header():
    L = []
    L.append("// GENERATED by qrts/tools/gen_memmap.py -- do not edit.")
    L.append("`ifndef DVCON_MEMMAP_VH")
    L.append("`define DVCON_MEMMAP_VH")
    L.append("")
    for name, base, size, why in REGIONS:
        L.append(f"// {why}")
        L.append(f"`define DVCON_{name}_BASE 32'h{base:08X}")
        L.append(f"`define DVCON_{name}_SIZE 32'd{size}")
    L.append("")
    L.append(f"`define DVCON_ETHERTYPE   16'h{ETHERTYPE:04X}")
    L.append(f"`define DVCON_MAX_PAYLOAD 16'd{MAX_PAYLOAD}")
    L.append(f"`define DVCON_ACK_WINDOW  {ACK_WINDOW}")
    L.append("")
    for name, op, why in OPCODES:
        L.append(f"`define DVCON_OP_{name} 8'h{op:02X}   // {why}")
    L.append("")
    for name, off, why in REGISTERS:
        L.append(f"`define DVCON_REG_{name} 6'h{off:02X}  // {why}")
    L.append("")
    L.append("`endif")
    return "\n".join(L) + "\n"


def check_registers():
    """Verify the register offsets against the RTL that implements them.

    IDENT sat here as 0x0F for a while when dvcon_regs answers it at byte 0x30,
    i.e. word 0x0C. Nothing caught it: the generated header was internally
    consistent, the JTAG script had its own copy of the number, and the Tcl
    self-check stubbed whatever the script asked for -- so the check passed
    while a real read went to the wrong register. Numbers duplicated across
    files need a check that reads BOTH, not one that reads the copy.
    """
    problems = []
    want = dict((n, o) for n, o, _ in REGISTERS)

    # jtag_ctrl's localparams: REG_<NAME> = 6'h<offset>
    jc = (QRTS / "rtl" / "platform" / "jtag_ctrl.sv").read_text(encoding="utf-8")
    alias = {"ETH_BM": "ETH_BITMAP", "DBG_DVAL": "DBG_DVAL"}
    for m in re.finditer(r"REG_(\w+)\s*=\s*6'h([0-9A-Fa-f]{2})", jc):
        name = alias.get(m.group(1), m.group(1))
        off = int(m.group(2), 16)
        if name not in want:
            problems.append(f"jtag_ctrl has REG_{m.group(1)} = 0x{off:02X}, "
                            f"missing from this table")
        elif want[name] != off:
            problems.append(f"{name}: this table says 0x{want[name]:02X}, "
                            f"jtag_ctrl.sv says 0x{off:02X}")

    # dvcon_regs answers IDENT at a byte offset; Avalon is word addressed.
    dr = (QRTS / "rtl" / "platform" / "dvcon_regs.sv").read_text(encoding="utf-8")
    m = re.search(r"byte_off\s*==\s*8'h([0-9A-Fa-f]{2})", dr)
    if m:
        ident_word = int(m.group(1), 16) // 4
        if want.get("IDENT") != ident_word:
            problems.append(
                f"IDENT: this table says 0x{want.get('IDENT'):02X}, but "
                f"dvcon_regs answers it at byte 0x{m.group(1)} = word "
                f"0x{ident_word:02X}")

    if problems:
        for p in problems:
            print(f"  register mismatch: {p}")
        sys.exit("  register table disagrees with the RTL")


def overlap_check():
    """A map whose regions overlap is the bug this file exists to prevent."""
    spans = sorted((b, b + s, n) for n, b, s, _ in REGIONS)
    for (b0, e0, n0), (b1, e1, n1) in zip(spans, spans[1:]):
        if e0 > b1:
            sys.exit(f"map error: {n0} (0x{b0:08X}..0x{e0:08X}) overlaps "
                     f"{n1} (0x{b1:08X})")
    top = spans[-1][1]
    if top > SDRAM_BYTES:
        sys.exit(f"map error: regions end at 0x{top:08X}, past the "
                 f"{SDRAM_BYTES // (1 << 20)} MB of SDRAM")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the generated files are stale")
    args = ap.parse_args()

    overlap_check()
    check_registers()

    targets = {
        QRTS / "sw" / "dvcon_memmap.h": c_header(),
        QRTS / "rtl" / "dvcon_memmap.vh": sv_header(),
    }

    stale = False
    for path, text in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        if args.check:
            print(f"  stale: {path}")
            stale = True
        else:
            path.write_text(text, encoding="utf-8")
            print(f"  wrote {path}")

    if args.check and stale:
        sys.exit("memory map headers are stale -- run tools/gen_memmap.py")
    if args.check:
        print("  memory map headers are current")


if __name__ == "__main__":
    main()
