#!/usr/bin/env python3
"""Pull the accelerator core RTL into qrts/rtl/core/ and retarget it at Quartus.

Idempotent by design: run it again after any Phase-A fix in DVCFinal and the
Cyclone IV tree picks the change up. Nothing here is hand-edited afterwards --
if a core file needs a change, change it upstream and re-run this.

Source precedence
-----------------
Two directories hold the accelerator sources and they overlap:

    DVCFinal/rtl/                        the files Phase A actually fixes
    DVCon_2026/.../ACCELERATOR_IP/       everything else, plus STALE COPIES
                                         of the rtl/ files (put there by
                                         'DVCFinal/build.sh install')

DVCFinal/rtl/ wins for every name it provides. This is the same trap that made
'build.sh sim' silently test the wrong code: xvlog only warns when a later file
redefines a module, so the stale IP copy quietly replaced the fixed one.

axi4_master.sv is a special case -- it lives only in ACCELERATOR_IP but carries
a Phase-A fix (the wr_strb byte-enable), so it is taken from there and is NOT
pristine upstream. It is also the file the Avalon shim replaces, so it is
copied for reference and excluded from the Quartus build.

Attribute rewriting
-------------------
Xilinx synthesis attributes mean nothing to Quartus. The ram_style rewrite in
particular is not cosmetic: Quartus ignores the Xilinx spelling and those
arrays silently become LE register files, which on a 114k-LE part is the
difference between fitting and not.

    (* ram_style = "block" *)        ->  (* ramstyle = "M9K" *)
    (* use_dsp = "yes" *)            ->  (* multstyle = "dsp" *)
    (* rom_style = "distributed" *)  ->  (* romstyle = "logic" *)

Only real attribute syntax is rewritten. Several of these strings also appear
in prose comments explaining what the attribute does; rewriting those would
make the comments describe the wrong tool.

What this script deliberately does NOT fix
------------------------------------------
Three things need human work and are reported, not patched:

  * silu_lut.sv builds its ROM in an initial block with $exp/$rtoi real math.
    Vivado folds that at elaboration; Quartus will not. Needs a .mif.
  * accel_dma_seq.sv's $fatal elaboration guard is ignored by Quartus.
  * Unpacked array module ports may need flattening to packed vectors if
    Quartus Lite's cross-boundary support complains.
"""

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
QRTS = HERE.parent
REPO = QRTS.parent

FIXED_RTL = REPO / "DVCFinal" / "rtl"
IP_DIR = REPO / "DVCon_2026" / "DVCon_SoC_SRC" / "ACCELERATOR_IP"
DEST = QRTS / "rtl" / "core"

# Files that do not travel to Cyclone IV at all.
#
# Only ONE now. Accelerator_Top, yolo_axi4_slave_regs, axi4_lite_slave and
# axi4_master were excluded while dvcon_top was going to rebuild the accelerator
# hierarchy from its engines. It does not: it instantiates Accelerator_Top
# whole, with dvcon_regs feeding its AXI slave and axi_to_avalon bridging its
# AXI master.
#
# That decision is about verification. Accelerator_Top is the module
# tb_top_sequencer drives end to end -- one START walking a descriptor chain
# through the real engines with bit-exact conv output. Rebuilding the hierarchy
# for the board would mean that result no longer describes what ships.
#
# soc_axi4_slave_regs really does belong to the old SoC and not the
# accelerator.
EXCLUDE_FROM_BUILD = {
    "soc_axi4_slave_regs.sv",
}

# Copied for reference but not compiled: the Avalon master is written against
# this file's handshake, so it must be readable next to it.
REFERENCE_ONLY = {"axi4_master.sv"}

ATTR_REWRITES = [
    # (compiled pattern, replacement, human description)
    (re.compile(r'\(\*\s*ram_style\s*=\s*"block"\s*\*\)'),
     '(* ramstyle = "M9K" *)',
     'ram_style="block" -> ramstyle="M9K"'),
    (re.compile(r'\(\*\s*ram_style\s*=\s*"distributed"\s*\*\)'),
     '(* ramstyle = "logic" *)',
     'ram_style="distributed" -> ramstyle="logic"'),
    (re.compile(r'\(\*\s*use_dsp\s*=\s*"yes"\s*\*\)'),
     '(* multstyle = "dsp" *)',
     'use_dsp="yes" -> multstyle="dsp"'),
    (re.compile(r'\(\*\s*use_dsp\s*=\s*"no"\s*\*\)'),
     '(* multstyle = "logic" *)',
     'use_dsp="no" -> multstyle="logic"'),
    (re.compile(r'\(\*\s*rom_style\s*=\s*"distributed"\s*\*\)'),
     '(* romstyle = "logic" *)',
     'rom_style="distributed" -> romstyle="logic"'),
    (re.compile(r'\(\*\s*rom_style\s*=\s*"block"\s*\*\)'),
     '(* romstyle = "M9K" *)',
     'rom_style="block" -> romstyle="M9K"'),
]

HEADER = """// -----------------------------------------------------------------------------
// GENERATED by qrts/tools/port_rtl.py -- DO NOT EDIT THIS COPY.
//
// Source: {src}
//
// Edit the source and re-run the porter:
//     python qrts/tools/port_rtl.py
//
// Xilinx synthesis attributes have been rewritten for Quartus. See the porter
// for what is rewritten and what still needs hand work.
// -----------------------------------------------------------------------------
"""


def is_in_comment(line: str, col: int) -> bool:
    """True if column `col` of `line` sits inside a // comment.

    Attribute-looking text appears in prose in several files ("(* use_dsp *)
    hints Vivado to..."). Rewriting those would leave comments describing the
    wrong tool, so they are left alone.
    """
    idx = line.find("//")
    return idx != -1 and idx < col


def rewrite_attributes(text: str):
    """Apply the Xilinx->Quartus attribute rewrites outside comments.

    Returns (new_text, {description: count}).
    """
    counts = {}
    out_lines = []
    for line in text.split("\n"):
        for pattern, repl, desc in ATTR_REWRITES:
            while True:
                m = pattern.search(line)
                if m is None or is_in_comment(line, m.start()):
                    break
                line = line[:m.start()] + repl + line[m.end():]
                counts[desc] = counts.get(desc, 0) + 1
        out_lines.append(line)
    return "\n".join(out_lines), counts


def collect_sources():
    """Map basename -> source Path, with DVCFinal/rtl/ taking precedence."""
    if not IP_DIR.is_dir():
        sys.exit(f"accelerator IP not found: {IP_DIR}")
    if not FIXED_RTL.is_dir():
        sys.exit(f"fixed RTL not found: {FIXED_RTL}")

    sources = {}
    shadowed = []

    for path in sorted(IP_DIR.glob("*.sv")) + sorted(IP_DIR.glob("*.svh")):
        sources[path.name] = path
    for path in sorted(FIXED_RTL.glob("*.sv")) + sorted(FIXED_RTL.glob("*.svh")):
        if path.name in sources:
            shadowed.append(path.name)
        sources[path.name] = path

    return sources, shadowed


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="report what would change without writing anything")
    args = ap.parse_args()

    sources, shadowed = collect_sources()
    DEST.mkdir(parents=True, exist_ok=True)

    total_rewrites = {}
    written = 0
    unchanged = 0
    build_files = []

    for name in sorted(sources):
        src = sources[name]
        text = src.read_text(encoding="utf-8")
        ported, counts = rewrite_attributes(text)
        for k, v in counts.items():
            total_rewrites[k] = total_rewrites.get(k, 0) + v

        try:
            rel = src.relative_to(REPO)
        except ValueError:
            rel = src
        content = HEADER.format(src=rel.as_posix()) + ported

        dst = DEST / name
        if dst.exists() and dst.read_text(encoding="utf-8") == content:
            unchanged += 1
        elif args.check:
            print(f"  would update: {name}")
            written += 1
        else:
            dst.write_text(content, encoding="utf-8", newline="")
            written += 1

        if name.endswith(".sv") and name not in EXCLUDE_FROM_BUILD:
            build_files.append(name)

    # The .qsf reads this list, so the file set is defined in exactly one place.
    manifest = DEST / "core_files.txt"
    manifest_text = (
        "# Generated by qrts/tools/port_rtl.py -- core RTL compiled into the\n"
        "# Quartus project, one basename per line, relative to rtl/core/.\n"
        "#\n"
        "# Excluded (Xilinx-only, replaced by rtl/platform/):\n"
        + "".join(f"#   {n}\n" for n in sorted(EXCLUDE_FROM_BUILD))
        + "".join(f"{n}\n" for n in build_files)
    )
    if not args.check:
        manifest.write_text(manifest_text, encoding="utf-8", newline="")

    # The same list as a Tcl fragment the .qsf sources. A .qsf cannot loop over
    # a manifest, and hand-maintaining a second copy of the file list is how it
    # drifts -- a file added here and forgotten there is a link error at best
    # and a stale module silently kept at worst.
    tcl = QRTS / "quartus" / "core_files.tcl"
    tcl_text = (
        "## Generated by qrts/tools/port_rtl.py -- do not edit.\n"
        "## Sourced by dvcon.qsf. Re-run the porter after changing the core.\n\n"
        + "".join(
            'set_global_assignment -name SYSTEMVERILOG_FILE '
            '"../rtl/core/{}"\n'.format(n) for n in build_files)
    )
    if not args.check:
        tcl.parent.mkdir(parents=True, exist_ok=True)
        tcl.write_text(tcl_text, encoding="utf-8", newline="")

    print(f"port_rtl: {written} written, {unchanged} unchanged -> {DEST}")
    print("          file list -> quartus/core_files.tcl")
    if shadowed:
        print(f"\n  DVCFinal/rtl/ took precedence over the stale IP copy for "
              f"{len(shadowed)} file(s):")
        for n in shadowed:
            print(f"    {n}")
    if total_rewrites:
        print("\n  attribute rewrites:")
        for desc in sorted(total_rewrites):
            print(f"    {total_rewrites[desc]:3d}  {desc}")

    print(f"\n  {len(build_files)} file(s) in the Quartus build, "
          f"{len(EXCLUDE_FROM_BUILD)} excluded")
    for n in sorted(REFERENCE_ONLY):
        if n in sources:
            print(f"    {n}: copied for reference only "
                  f"(avalon_mm_master.sv must match its handshake)")

    print("""
  Still needs hand work -- the porter cannot fix these:
    silu_lut.sv       initial-block ROM uses $exp/$rtoi real math. Vivado folds
                      it at elaboration, Quartus will not. Needs a .mif.
    accel_dma_seq.sv  $fatal elaboration guard is ignored by Quartus. Moot if
                      the legacy path is dropped.
    unpacked ports    systolic_array/accelerator/system_top/yolo_conv_engine
                      pass unpacked arrays across module boundaries. Try as-is;
                      flatten to packed vectors if Analysis & Synthesis balks.""")


if __name__ == "__main__":
    main()
