// GENERATED by qrts/tools/gen_memmap.py -- do not edit.
`ifndef DVCON_MEMMAP_VH
`define DVCON_MEMMAP_VH

// model blob: 32-byte header + 181 x 64 B descriptors + weights
`define DVCON_MODEL_BASE 32'h00000000
`define DVCON_MODEL_SIZE 32'd4194304
// input frame, INT8 CHW 3x640x640 = 1,228,800 B
`define DVCON_FRAME_BASE 32'h00400000
`define DVCON_FRAME_SIZE 32'd2097152
// box list: 300 x 16-byte records, Q12.4
`define DVCON_BOXES_BASE 32'h00600000
`define DVCON_BOXES_SIZE 32'd65536
// feature-map arena (exporter --fmap-base)
`define DVCON_ARENA_BASE 32'h00800000
`define DVCON_ARENA_SIZE 32'd58720256
// second frame buffer, for double buffering
`define DVCON_FRAME2_BASE 32'h04000000
`define DVCON_FRAME2_SIZE 32'd67108864

`define DVCON_ETHERTYPE   16'h88B5
`define DVCON_MAX_PAYLOAD 16'd1408
`define DVCON_ACK_WINDOW  64

`define DVCON_OP_WRITE_MEM 8'h01   // payload -> SDRAM at addr
`define DVCON_OP_ACK_REQ 8'h06   // reply with the 64-bit received bitmap
`define DVCON_OP_ACK 8'h10   // FPGA -> host: the bitmap

`define DVCON_REG_CTRL 6'h00  // bit0 START, bit1 soft reset, bit2 ucode mode
`define DVCON_REG_STATUS 6'h01  // bit0 busy, bit1 done, bit2 error
`define DVCON_REG_DESC_ADDR 6'h06  // descriptor table base
`define DVCON_REG_IMG_ADDR 6'h07  // input frame base
`define DVCON_REG_BOX_ADDR 6'h08  // box list base
`define DVCON_REG_CONF_THRESH 6'h09  // INT8 confidence threshold
`define DVCON_REG_NUM_BOXES 6'h0A  // boxes written by the last frame
`define DVCON_REG_IDENT 6'h0F  // 0xDC, ARRAY_SIZE, build id
`define DVCON_REG_ETH_GOOD 6'h3A  // ethernet frames with a good FCS
`define DVCON_REG_ETH_BAD 6'h3B  // ethernet frames that failed FCS
`define DVCON_REG_ETH_CMD 6'h3C  // command frames accepted
`define DVCON_REG_ETH_BITMAP 6'h3D  // low 32 bits of the ACK window bitmap
`define DVCON_REG_MEMADDR 6'h3E  // SDRAM read cursor (write)
`define DVCON_REG_MEMDATA 6'h3F  // word at the cursor; post-increments (read)

`endif
