## ============================================================================
## dvcon.sdc — timing constraints for the DE2-115 build
##
## Read by TimeQuest. A design with no SDC is not "unconstrained but fine" --
## Quartus reports it as timing-clean because it has nothing to check, which is
## exactly how a design that cannot possibly meet timing gets signed off.
##
## The Xilinx build missed 50 MHz by 21.5 ns on a FASTER fabric (Kintex-7
## against Cyclone IV C7), so nothing here should be read as "this will close".
## These constraints exist so the tool can tell the truth about it.
## ============================================================================

## ----------------------------------------------------------------------------
## Primary clock
##
## CLOCK_50 is the board oscillator. The core currently runs directly off it
## because the PLL is not generated yet (see dvcon_top.sv); once it is, the
## derived clocks below become real and this stays as the PLL reference.
## ----------------------------------------------------------------------------
create_clock -name CLOCK_50 -period 20.000 [get_ports CLOCK_50]

## The Ethernet PHY drives its own receive clock. The design is MII at
## 100BASE-TX, so this is 25 MHz -- see dvcon_top.sv for why MII and not RGMII.
## A real asynchronous source, not a derived clock: the PHY's oscillator has no
## relationship to CLOCK_50.
##
## It was constrained at 8 ns (125 MHz, the gigabit case) while the front end
## was still unwritten. Leaving it there would over-constrain the receive path
## by five times and spend fitter effort closing timing the board never needs.
create_clock -name ENET0_RX_CLK -period 40.000 [get_ports ENET0_RX_CLK]

## The MII transmit clock, generated by dividing CLOCK_50 by two in the fabric.
## A divided clock is invisible to TimeQuest unless it is declared, and an
## undeclared clock means every flop it drives is simply not analysed.
##
## The target is the bare node name. Written as {dvcon_top:*|eth_tx_clk}
## it matched nothing, and Quartus said so -- 'Ignored
## create_generated_clock ... Argument <targets> is an empty collection',
## followed by 'Node: eth_tx_clk was determined to be a clock but was found
## without an associated clock assignment'. The compile still succeeded and
## the timing report still looked clean for that domain, because there was
## nothing in it. ALWAYS grep the log for 332049 and 332174.
create_generated_clock -name eth_tx_clk -source [get_ports CLOCK_50] \
    -divide_by 2 [get_registers {eth_tx_clk}]

## PLL outputs. derive_pll_clocks picks these up automatically once the PLL
## megafunction exists; keeping the call here means the SDC does not need
## editing at that point.
derive_pll_clocks
derive_clock_uncertainty

## ----------------------------------------------------------------------------
## Asynchronous clock groups
##
## The receive domain is genuinely independent of the core: separate crystal,
## no phase relationship, crossings handled by dcfifo. Without this declaration
## TimeQuest tries to close paths between them, reports enormous negative slack
## on crossings that are already safe, and buries the real failures.
##
## This is a promise about the RTL, not a way to silence the tool: every
## crossing between these groups must go through a dcfifo or a synchroniser.
## ----------------------------------------------------------------------------
set_clock_groups -asynchronous \
    -group [get_clocks CLOCK_50] \
    -group [get_clocks ENET0_RX_CLK]

## ----------------------------------------------------------------------------
## SDRAM
##
## The IS42S16320D is a source-synchronous device clocked by DRAM_CLK, which
## the FPGA generates. The standard DE2-115 arrangement is a PLL output phase
## shifted -3 ns relative to the controller clock, so data is stable at the
## memory when its clock edge arrives.
##
## These are placeholders until the PLL exists: they describe the timing the
## board needs, and the numbers come from the IS42S16320D datasheet at CAS 3.
##   tSU  1.5 ns   input setup at the memory
##   tHD  0.8 ns   input hold
##   tAC  5.4 ns   clock to output valid
##   tOH  2.5 ns   output hold
##
## They are commented out because constraining DRAM_CLK before it is a real
## generated clock produces errors, not warnings, and a .sdc that errors out
## leaves the WHOLE design unconstrained -- the failure mode this file exists
## to prevent.
##
## DRAM_CLK is currently the INVERSE of clk_sys, generated in the fabric
## rather than by a PLL (assign DRAM_CLK = ~clk_sys), which gives the memory
## half a period of setup -- the standard arrangement on this board, and why
## the design can be timed before the PLL exists.
##
## The generated clock is DECLARED below: without it the SDRAM pins are not
## analysed at all. The I/O delays stay commented out until a PLL provides a
## real phase shift, since checking them against a fabric-inverted clock
## would report a problem the board does not have.
## ----------------------------------------------------------------------------
create_generated_clock -name DRAM_CLK -source [get_ports CLOCK_50] -invert \
    [get_ports DRAM_CLK]

## Uncomment the I/O delays together with the PLL.
## ----------------------------------------------------------------------------
# create_generated_clock -name DRAM_CLK -source [get_pins {u_pll|...|clk[1]}] \
#     [get_ports DRAM_CLK]
#
# set_output_delay -clock DRAM_CLK -max  1.5 [get_ports {DRAM_ADDR[*] DRAM_BA[*] \
#     DRAM_CAS_N DRAM_RAS_N DRAM_WE_N DRAM_CS_N DRAM_CKE DRAM_DQM[*] DRAM_DQ[*]}]
# set_output_delay -clock DRAM_CLK -min -0.8 [get_ports {DRAM_ADDR[*] DRAM_BA[*] \
#     DRAM_CAS_N DRAM_RAS_N DRAM_WE_N DRAM_CS_N DRAM_CKE DRAM_DQM[*] DRAM_DQ[*]}]
#
# set_input_delay  -clock DRAM_CLK -max  5.4 [get_ports {DRAM_DQ[*]}]
# set_input_delay  -clock DRAM_CLK -min  2.5 [get_ports {DRAM_DQ[*]}]

## ----------------------------------------------------------------------------
## RGMII
##
## Also commented out until the DDR front end and its PLL clocks exist.
##
## The plan's decision, worth restating because it is easy to lose: program the
## 88E1111's OWN transmit clock delay (register 20) rather than phase-shifting
## in the FPGA. Closing 125 MHz source-synchronous timing on a C7 part is
## considerably harder than setting a PHY register, and the fallback if it
## still will not close is 100 Mbit MII, which swaps only the rgmii_* front end
## and leaves the 8-bit datapath untouched.
##
## RGMII receive: the PHY presents data centred on its clock edges when its
## internal delay is enabled, so the window is roughly +/- 1 ns.
## ----------------------------------------------------------------------------
# set_input_delay -clock ENET0_RX_CLK -max  1.0 \
#     [get_ports {ENET0_RX_DATA[*] ENET0_RX_DV}]
# set_input_delay -clock ENET0_RX_CLK -min -1.0 \
#     [get_ports {ENET0_RX_DATA[*] ENET0_RX_DV}]
# set_input_delay -clock ENET0_RX_CLK -max  1.0 \
#     [get_ports {ENET0_RX_DATA[*] ENET0_RX_DV}] -clock_fall -add_delay
# set_input_delay -clock ENET0_RX_CLK -min -1.0 \
#     [get_ports {ENET0_RX_DATA[*] ENET0_RX_DV}] -clock_fall -add_delay
#
# set_output_delay -clock ENET0_GTX_CLK -max  1.0 \
#     [get_ports {ENET0_TX_DATA[*] ENET0_TX_EN}]
# set_output_delay -clock ENET0_GTX_CLK -min -0.8 \
#     [get_ports {ENET0_TX_DATA[*] ENET0_TX_EN}]

## ----------------------------------------------------------------------------
## False paths
## ----------------------------------------------------------------------------

## KEY[0] is a mechanical button feeding a reset synchroniser. It is
## asynchronous by definition and the synchroniser is what makes it safe.
set_false_path -from [get_ports {KEY[*]}]

## LEDs are for a human eye. Constraining them wastes optimisation effort on
## paths where a hundred nanoseconds would be invisible.
set_false_path -to [get_ports {LEDR[*] LEDG[*]}]

## The PHY reset and MDIO are configuration-time signals, not datapath.
set_false_path -to   [get_ports {ENET0_RST_N ENET0_MDC}]
set_false_path -from [get_ports {ENET0_MDIO}]
set_false_path -to   [get_ports {ENET0_MDIO}]

## ----------------------------------------------------------------------------
## Multicycle paths
##
## Deliberately EMPTY. It is tempting to relax the conv engine's long
## arithmetic here to make a report go green, and that would be lying to
## whoever reads it next: the paths are genuinely long and the fix belongs in
## the RTL. The A1 rewrite removed four variable dividers from the reduction
## seed for exactly that reason.
##
## If something here really is multicycle -- the serial divider in silu_unit
## runs once per layer, not once per element -- it gets a constraint WITH a
## comment saying which structural property makes it safe.
## ----------------------------------------------------------------------------
