// =============================================================================
// mii_tx_adapter.sv — byte stream -> MII nibble stream, out of the system clock
//
// The mirror of mii_rx_adapter. eth_mac_tx produces a byte per cycle on
// clk_sys; MII wants two nibbles per byte, low nibble first, clocked at
// 25 MHz for 100BASE-TX.
//
// ---------------------------------------------------------------------------
// THE CLOCK ON PIN A17
// ---------------------------------------------------------------------------
// The DE2-115 labels that pin ENET1_GTX_CLK and the pin file calls the
// interface RGMII, but it is the 88E1111's transmit clock and its meaning
// depends on the mode the PHY is strapped into:
//
//   MII  (100BASE-TX)   the FPGA drives it at 25 MHz   <- what this does
//   GMII / RGMII        125 MHz for gigabit
//
// It is an output either way, which is why the top level's port list needs no
// change. MII at 100 Mbit is sufficient here: the largest transfer is the
// 2.8 MB model blob, about a quarter of a second on the wire, and it happens
// once at startup. RGMII would double the pin-level complexity (DDR on both
// edges, and a PHY-specific internal delay to negotiate) for a link that is
// not the bottleneck.
//
// ---------------------------------------------------------------------------
// CLOCK DOMAINS
// ---------------------------------------------------------------------------
// tx_clk is generated by dividing clk_sys, so it is phase-related rather than
// asynchronous -- but a divided clock is still a separate domain to the
// fitter, and treating it as one costs almost nothing. The FIFO is the same
// shape as the RX side's, and for the same reason: a byte every 8 tx_clk edges
// against a free-running 100 MHz writer is a stream, not a level.
// =============================================================================
`timescale 1ns/1ps

module mii_tx_adapter #(
    parameter integer AW = 4          // FIFO depth = 2**AW bytes
)(
    // ---- byte side, system clock ----
    input  wire       clk,
    input  wire       rst_n,
    input  wire [7:0] in_data,
    input  wire       in_valid,       // eth_mac_tx has a byte this cycle
    output wire       in_ready,       // FIFO has room

    // ---- MII side, tx_clk domain ----
    input  wire       tx_clk,
    output reg  [3:0] mii_txd,
    output reg        mii_tx_en
);

    localparam integer DEPTH = 1 << AW;

    reg [7:0] fifo [0:DEPTH-1];

    reg [AW:0] wptr_bin, wptr_gray;
    reg [AW:0] rptr_bin, rptr_gray;
    reg [AW:0] wptr_gray_s1, wptr_gray_s2;
    reg [AW:0] rptr_gray_s1, rptr_gray_s2;

    function automatic [AW:0] bin2gray(input [AW:0] b);
        bin2gray = b ^ (b >> 1);
    endfunction

    wire [AW:0] wptr_next = wptr_bin + 1'b1;
    wire full = (bin2gray(wptr_next) == {~rptr_gray_s2[AW:AW-1],
                                         rptr_gray_s2[AW-2:0]});
    assign in_ready = !full;

    // ---- write side, clk ----------------------------------------------------
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            wptr_bin  <= '0;
            wptr_gray <= '0;
        end else if (in_valid && !full) begin
            fifo[wptr_bin[AW-1:0]] <= in_data;
            wptr_bin  <= wptr_next;
            wptr_gray <= bin2gray(wptr_next);
        end
    end

    always @(posedge tx_clk or negedge rst_n) begin
        if (!rst_n) begin
            wptr_gray_s1 <= '0;
            wptr_gray_s2 <= '0;
        end else begin
            wptr_gray_s1 <= wptr_gray;
            wptr_gray_s2 <= wptr_gray_s1;
        end
    end

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            rptr_gray_s1 <= '0;
            rptr_gray_s2 <= '0;
        end else begin
            rptr_gray_s1 <= rptr_gray;
            rptr_gray_s2 <= rptr_gray_s1;
        end
    end

    wire empty = (rptr_gray == wptr_gray_s2);

    // ---- read side, tx_clk: one byte becomes two nibbles --------------------
    reg       phase;          // 0 = drive low nibble
    reg [7:0] cur;

    always @(posedge tx_clk or negedge rst_n) begin
        if (!rst_n) begin
            rptr_bin  <= '0;
            rptr_gray <= '0;
            phase     <= 1'b0;
            cur       <= 8'h0;
            mii_txd   <= 4'h0;
            mii_tx_en <= 1'b0;
        end else begin
            if (!phase) begin
                if (!empty) begin
                    cur       <= fifo[rptr_bin[AW-1:0]];
                    mii_txd   <= fifo[rptr_bin[AW-1:0]][3:0];   // low first
                    mii_tx_en <= 1'b1;
                    rptr_bin  <= rptr_bin + 1'b1;
                    rptr_gray <= bin2gray(rptr_bin + 1'b1);
                    phase     <= 1'b1;
                end else begin
                    // Gaps between frames are the normal state of an idle link.
                    mii_tx_en <= 1'b0;
                    mii_txd   <= 4'h0;
                end
            end else begin
                // The high nibble MUST go out even if the FIFO ran dry, or the
                // frame loses half a byte and every receiver drops it on FCS.
                mii_txd   <= cur[7:4];
                mii_tx_en <= 1'b1;
                phase     <= 1'b0;
            end
        end
    end

endmodule
